### ISSUE TITLE
Wish can use webp format directly

### ISSUE THREAD

**Issue by Annabelle1024** [onevcat/Kingfisher#1029]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [ ] I want to report a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

#### What

[Tell us about the issue]

#### Reproduce

[The steps to reproduce this issue. What is the url you were trying to load, where did you put your code, etc.]

#### Other Comment

[Add anything else here]

**Comment by onevcat** [comment]
I guess [KingfisherWebP](https://github.com/yeatse/KingfisherWebP) is good enough on this task.

It might still be needed to use something like libwebp as a dependency if we want to integrate WebP support in Kingfisher. Since it is not a cost-free dependency, we still need to provide another framework or subpod for it, which does not make things easier at all.

So there is no such plan now for Kingfisher. Just use KingfisherWebP should be fine!

**Comment by Dfmarulanda** [comment]
it seams that 
<img width="1172" alt="Screen Shot 2019-05-20 at 5 43 26 PM" src="https://user-images.githubusercontent.com/2466498/58056717-ccb70c00-7b27-11e9-9904-c553fbb9945a.png">
<img width="1080" alt="Screen Shot 2019-05-20 at 5 43 12 PM" src="https://user-images.githubusercontent.com/2466498/58056718-ccb70c00-7b27-11e9-8cd2-dd1a3f4588b9.png">

https://github.com/yeatse/KingfisherWebP very big memory leak issue.
