### ISSUE TITLE
 not synchronized callbacks when image is requested twice and is already in cache

### ISSUE THREAD

**Issue by NikoSahradyan** [onevcat/Kingfisher#1053]
Currently I'm using ImageView in `UIStackView`, at first I'm setting the `imageView.isHidden = true`, as we know `UIStackView` is changing the frame of the subview which is hidden, so after that for example the size of the imageView is becoming (0,30), and afterwards when I'm setting `imageView.isHidden = false` the ImageView is getting it's actual sizes. In my subclass of `UIImageView` after every change of `bounds` I'm resetting the image. Currently for each size I'm creating my own `ResizingImageProcessor` and appending it to `KingfisherOptionsInfo`.
 
Actual problem is that  `completionHandler`  of

`setImage(with resource: Resource?,
                         placeholder: Placeholder? = nil,
                         options: KingfisherOptionsInfo? = nil,
                         progressBlock: DownloadProgressBlock? = nil,
                         completionHandler: CompletionHandler? = nil) -> RetrieveImageTask`

method in first case is called later then for second case, that means that at first I'm receiving `image` for `ResizingImageProcessor` which I have created for (30x30) size and afterwards I'm receiving  `image` for `ResizingImageProcessor` which I have created for (0x30). But I have asked for the images in opposite order (first for (0x30) then for (30x30)) but received (first for (30x30) then for (0x30)).

I found from where this kind of asynchronization is coming from.

`ImageCache.swift` in method 
`retrieveImage(forKey key: String,
                               options: KingfisherOptionsInfo?,
                     completionHandler: ((Image?, CacheType) -> Void)?) -> RetrieveImageDiskTask?`

when callback is done from this part (is case of my (30x30))

`if let image = self.retrieveImageInMemoryCache(forKey: key, options: options) {
            options.callbackDispatchQueue.safeAsync {
                completionHandler(imageModifier.modify(image), .memory)
            }
}`
we are receiving the callback much more faster than from (which is case of my (0x30))

`            block = DispatchWorkItem(block: {
                // Begin to load image from disk
                if let image = sSelf.retrieveImageInDiskCache(forKey: key, options: options) {
                    if options.backgroundDecode {
                        sSelf.processQueue.async {

                            let result = image.kf.decoded
                            
                            sSelf.store(result,
                                        forKey: key,
                                        processorIdentifier: options.processor.identifier,
                                        cacheSerializer: options.cacheSerializer,
                                        toDisk: false,
                                        completionHandler: nil)
                            options.callbackDispatchQueue.safeAsync {
                                completionHandler(imageModifier.modify(result), .disk)
                                sSelf = nil
                            }
                        }
                    } else {
                        sSelf.store(image,
                                    forKey: key,
                                    processorIdentifier: options.processor.identifier,
                                    cacheSerializer: options.cacheSerializer,
                                    toDisk: false,
                                    completionHandler: nil
                        )
                        options.callbackDispatchQueue.safeAsync {
                            completionHandler(imageModifier.modify(image), .disk)
                            sSelf = nil
                        }
                    }
                } else {
                    // No image found from either memory or disk
                    options.callbackDispatchQueue.safeAsync {
                        completionHandler(nil, .none)
                        sSelf = nil
                    }
                }
            })
            
            sSelf.ioQueue.async(execute: block!)
`

**Comment by onevcat** [comment]
Ummm, yes, if your image is already cached in memory, it will be returned as soon as retrieved. So in your case, the latter one comes first.

If you really need the order, I suggest you can call the latter set image method in the completion handler of the first one. So your second one would definitely come after the first, in order. You can also add `.cacheOriginalImage` to the options of the first setting, so your second setting can reuse the downloaded image and only do processing, which would be faster.

**Comment by andrei-kuzma** [comment]
For me it's unexpected behaviour. The same issue can be potentially reproduced during cell reuse when previous image is loaded after current one.
The reason is that task is only "partially canceled" and even we run new task result of previous is applied. As all images are applied on main thread probably for now it's enough to check if task is not canceled or running task is the same as associated with UIImageView before applying result.

**Comment by onevcat** [comment]
> For me it's unexpected behavior. The same issue can be potentially reproduced during cell reuse when previous image is loaded after current one.

It will not happen, if you try to load images at different URL. The image view setting method will keep the last URL you are loading and call the completion handler only if the loaded one has the same URL as the last one. In your case, since you are loading images from the same URL (only the processor is different), so the completion handler called unexpectedly. A simple (and maybe better) workaround for your case is, instead of loading the image URL directly, you can add some extra queries to distinguish them, like `https://example.com/image.jpg?p=30x30` and `https://example.com/image.jpg?p=0x30`. Most servers will ignore the query if it does not recognize it, but Kingfisher will treat them as different resources so the completion handler will be called for the last set one. (Or you can just use the `identifier` of your processor as the query, which is unique for each kind of `ImageProcessor`)

It is a design defect to use URL as the image setting identifier (we didn't have the processor in the beginning). In Kingfisher version 5, I fixed it by letting users specify a customized identifier for every resource and not use the URL anymore.

**Comment by andrei-kuzma** [comment]
@onevcat 
Thank you for proposed fix.
Could you tell when you plan to release 5.0 version?

**Comment by onevcat** [comment]
Most work has been done in branch 5.0 and there is also some beta tag for it. But I still need some more time to polish the code and documentation. There is also a plan to use it first in my own projects before I can release it finally. Maybe it takes two or three weeks for these things.

**Comment by andrei-kuzma** [comment]
Hi @onevcat,
Is there any reason why support of iOS 9 was dropped in v5.0?

**Comment by onevcat** [comment]
The share for all iOS 9 and earlier is below 1.0%. I didn't find a reason to still support iOS 9.

And later I have a plan to adapt to `UIGraphicsImageRenderer` instead of a traditional `CGContext` drawing. It requires iOS 10+. I do not want to make the deploy target different in the same major version.
