### ISSUE TITLE
Prefetch images upon

### ISSUE THREAD

**Issue by kwalker0456** [onevcat/Kingfisher#1057]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [ ] I want to report a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

### Issue Description
When I am attempting to prefetch images, I am getting an empty array after the images are fetched the first time. I would like to have it prefetch each time app is opened.

#### What
When prefetching images through URLs, I look at the debug log and see that the prefetching did not occur because the images had already been downloaded. In my code, I am doing the prefetching in viewDidLoad. I was doing this in hopes that it would prefetch the images each time that viewDidLoad is called. I am new to iOS and this is my first client project, so perhaps I should be putting the prefetch code elsewhere.

[Tell us about the issue]

#### Reproduce
Put in some image URLs and use this part of the Cheat Sheet:

let urls = ["http://example.com/image1.jpg", "http://example.com/image2.jpg"]
           .map { URL(string: $0)! }
let prefetcher = ImagePrefetcher(urls: urls) {
    skippedResources, failedResources, completedResources in
    print("These resources are prefetched: \(completedResources)")
}
prefetcher.start()

// Later when you need to display these images:
imageView.kf.setImage(with: urls[0])

#### Other Comment

[Add anything else here]

**Comment by onevcat** [comment]
The prefetcher will not only download the images but also cache them to disk for later use. If the images are already in cache, it will not be downloaded again. I guess you can find them in the `skippedResources` array.

**Comment by kwalker0456** [comment]
I see. You were correct about them being in skippedResources. Would .forceRefresh be the only way to handle with KF? I am thinking I will use .forceRefresh based on a timer.

**Comment by onevcat** [comment]
Not sure what do you want to do...

Are you creating something like a carousel from a set of URLs? If so, you can just prefetch them as you did now and then just use `imageView.kf.setImage(with: url)` to get them from cache. Why do you want to redownload them?

**Comment by kwalker0456** [comment]
Basically yes. I only want to do it this way as my client doesn't like the way traditional carousels animate. He just wants it to switch to the next image with no carousel effect/animation, hence the timer. I want to redownload because he wants to be able to control what image is shown by changing the image at these fixed URLs.

**Comment by onevcat** [comment]
Kingfisher is using URL as the cache key by default. There are several ways for your needs:

1. Append a query for a different image at the same URL if possible. Like "https://example.com/image.jpg?id=1" and "https://example.com/image.jpg?id=2" means different images in Kingfisher. And it will redownload the version of "id=2" even when you have the image for "id=1" in the cache. But it requires you have a way to receive different queries from your server for different URL. This is the recommended way if you have control to your server.
2. Instead of using the URL directly, create an `ImageResource` with this URL, and a unique `cacheKey`. The idea is the same as above, but without the capability of reusing the image anymore, since as a client app, you have no idea on whether the images are changed or not on the server (in the same URL).
3. Set a `.targetCache` other than the default one in options parameter when you prefetch, then when you need to fetch them again, clear that cache.
