### ISSUE TITLE
Swift4.2使用版本4.10.2

### ISSUE THREAD

**Issue by SeongBrave** [onevcat/Kingfisher#1061]
喵神，您好，我在做私有库的时候报一下错误，麻烦看下什么原因呢?

![image](https://user-images.githubusercontent.com/10784393/49736264-977ad800-fcc4-11e8-824e-dc591646701d.png)

**Comment by onevcat** [comment]
There should be no such version as 4.10.2. Check the [release page](https://github.com/onevcat/Kingfisher/releases) to see all released Kingfisher version. For the latest of version 4, it should be 4.10.1, and it is both Swift 4.0 and 4.2 compatible. So check your build/pod lint environment, especially the `swift_version` setting in your podspec file.

Since it is not likely an issue of Kingfisher, but instead of a CocoaPods integration problem, I am closing it. To get more help, maybe discussing in the CocoaPods repo or Stackoverflow tag would be more helpful.

**Comment by SeongBrave** [comment]
喵神，您好，不好意思啊，我用的版本是4.10.1，我的错误是因为我使用的XcodeBuild 是9.4.1导致的，公司打包要求用xcode9.4.1的🤭
