### ISSUE TITLE
v5 issues and proposals

### ISSUE THREAD

**Issue by andrei-kuzma** [onevcat/Kingfisher#1065]
During migration to v5 we faced next issues

1. DownsamplingImageProcessor works differently for .data(...) and .image(...) as downsampling is not the same as resize with .none option.

2. DiskStorage creates directory during instance creation and if app cleanup cache directory, images will not be cached as
`config.fileManager.createFile(atPath: fileURL.path, contents: data, attributes: attributes)`
will fail and there is no any logs for that so clients can miss that.
Probably if that method fail we should check if directory exist, if not create it and create file again.

Potential improvements:
1. We have PR that adds a 'useFileDownloads" option, so that instead of using NSURLSession.DataTask it will use NSURLSession.DownloadTask.  (https://github.com/onevcat/Kingfisher/pull/883)
There is advice to use DownsamplingImageProcessor for that case. But probably we should combine both approaches. In that case NSData will not be loaded in memory and CGImageSourceCreateWithURL will be used instead of CGImageSourceCreateWithData.
The same trick can be done when we read originalImage from cache and want to apply downsampling  and other processors. We can get just url for it and create imageSource without reading data (now original image will be loaded in memory)

2. Probably it make sense to have one processor instead of two DownsamplingImageProcessor and ResizingImageProcessor.
CGImageSource allow us to get image size. It means that we can calculate proper size of thumbnail from DownsamplingImageProcessor according to chosen contentMode (now combination of downsampling and resizing with .aspectFill mode works incorrectly) and then resize that image if needed. So after downsampling we will get scaled in memory image with minimum size and best quality and then it will be resized ('cropped' for .apectFill for example)

**Comment by onevcat** [comment]
Thanks for the proposal.

#### For the issues part:

> DownsamplingImageProcessor works differently for .data(...) and .image(...)

As indicated in [the doc](http://onevcat.github.io/Kingfisher/Structs/DownsamplingImageProcessor.html), `DownsamplingImageProcessor` should be used as the first processor in the pipeline. Currently, if used by being appended to another processor, it just falls back to use the resizing processor. You are right on it, the resizing strategy is a bit different. So instead of simply use resizing as a fallback, I guess it would be better to follow the same way to create an image source and get thumbnail image from the source. I'd try to give it a fix soon.

> app cleanup cache directory, images will not be cached

If I am right, once the directory created, it will be always there, even you clear the disk cache. You could find [related code here](https://github.com/onevcat/Kingfisher/blob/master/Sources/Cache/DiskStorage.swift#L186-L191). The `skipCreatingDirectory` is only used in test cases for an injection purpose. In framework itself and for external users, the directory would be always recreated. (unless you delete the folder manually, instead of using Kingfisher's clear disk cache method. But this behavior should be out of our scape.)

#### For the improvements part

Thanks again for your PR on DownloadTask!

> NSData will not be loaded in memory and CGImageSourceCreateWithURL will be used instead of CGImageSourceCreateWithData

Underlying, `CGImageSourceCreateWithURL` read the data from the URL, and then create the image source from the data. So there should be no memory difference between them.

I am not 100% sure about it, but you can find some clue from [CGImageSource doc](https://developer.apple.com/documentation/imageio/cgimagesource?language=objc):

> CGImageSource objects abstract the data-reading task. An image source can read image data from a URL, a CFData object, or a data consumer.

Let me know if I am wrong with it.

> have one processor instead of two DownsamplingImageProcessor and ResizingImageProcessor 

Keeping `ResizingImageProcessor` unchanged is more or less a backward compatibility choice. Downsampling will just accept sizes smaller than the original image, with the same aspect ratio. However, the resizing processor could accept arbitrary sizes (and with any given content mode). So I guess there is not a good way to combine them in a good way and satisfy everyone after all.

But for most use cases (shrinking the image with the same ratio, that is, aspect fit), the `DownsamplingImageProcessor` should be chosen. For other purposes, such as a different content mode, users can choose resizing or downsampling followed by a resizing.

**Comment by andrei-kuzma** [comment]
> > DownsamplingImageProcessor works differently for .data(...) and .image(...)
> 
> As indicated in [the doc](http://onevcat.github.io/Kingfisher/Structs/DownsamplingImageProcessor.html), `DownsamplingImageProcessor` should be used as the first processor in the pipeline. Currently, if used by being appended to another processor, it just falls back to use the resizing processor. You are right on it, the resizing strategy is a bit different. So instead of simply use resizing as a fallback, I guess it would be better to follow the same way to create an image source and get thumbnail image from the source. I'd try to give it a fix soon.

In case when there is cached original image .image(...) will be used

> > app cleanup cache directory, images will not be cached
> 
> If I am right, once the directory created, it will be always there, even you clear the disk cache. You could find [related code here](https://github.com/onevcat/Kingfisher/blob/master/Sources/Cache/DiskStorage.swift#L186-L191). The `skipCreatingDirectory` is only used in test cases for an injection purpose. In framework itself and for external users, the directory would be always recreated. (unless you delete the folder manually, instead of using Kingfisher's clear disk cache method. But this behavior should be out of our scape.)

You are right. My case is when content of cache directory was deleted manually.
But the main thing is not that this behavior exist but that it could be invisible during development.
And detected too late :).

> #### For the improvements part
> Thanks again for your PR on DownloadTask!
> 
> > NSData will not be loaded in memory and CGImageSourceCreateWithURL will be used instead of CGImageSourceCreateWithData
> 
> Underlying, `CGImageSourceCreateWithURL` read the data from the URL, and then create the image source from the data. So there should be no memory difference between them.
> 
> I am not 100% sure about it, but you can find some clue from [CGImageSource doc](https://developer.apple.com/documentation/imageio/cgimagesource?language=objc):
> 
> > CGImageSource objects abstract the data-reading task. An image source can read image data from a URL, a CFData object, or a data consumer.
> 
> Let me know if I am wrong with it.

Looks like you are right that there is no difference between CGImageSourceCreateWithURL and CGImageSourceCreateWithData.
But case when we get originalImage from disk cache still can be improved using data instead of image

> 
> > have one processor instead of two DownsamplingImageProcessor and ResizingImageProcessor
> 
> Keeping `ResizingImageProcessor` unchanged is more or less a backward compatibility choice. Downsampling will just accept sizes smaller than the original image, with the same aspect ratio. However, the resizing processor could accept arbitrary sizes (and with any given content mode). So I guess there is not a good way to combine them in a good way and satisfy everyone after all.
> 
> But for most use cases (shrinking the image with the same ratio, that is, aspect fit), the `DownsamplingImageProcessor` should be chosen. For other purposes, such as a different content mode, users can choose resizing or downsampling followed by a resizing.

For example you have image with size 5000x5000 and you need to show it in size 50x100 with .apspectFill. Downsampling will resize that image to 100x100 and only that image will be loaded in memory and after that you 'resize' it to 50x100
In case when .aspectFit is used resize will not be applied (I mean that it can be handled internally)

**Comment by onevcat** [comment]
> In case when there is cached original image .image(...) will be used

Good catch!

> My case is when content of cache directory was deleted manually.

There seem to be two possible options for it:

1. Check folder existence every time and create one if it is not there.

    I am not sure about how it would affect to performance if we check the folder existence every time when storing an image. Do you have any idea on it? Or some benchmark needs to be done before we can add such a check. 

2. Just give some log and information.

    `createFile(atPath:contents:attributes:)` does not throw any error but only return a `Bool` to indicate success or failure. So I am not sure how it would be useful to just see a log like "createFile fails at path xxx".

Or there is another way: trying to check and recreate the folder only when `createFile` fails, and then retry creating the file one more time. But it is a bit "magical" and hiding things, adding internal complexity, which I do not quite like.

What's your option? What kind of error/log/handling do you prefer?

> we get originalImage from disk cache still can be improved using data instead of image

Yes, you are right. It is mainly due to the lack of image source support for `DefaultCacheSerializer`. Currently, only the `DownsamplingImageProcessor` lives in the world of `CGImaSource`, others are playing with `CGContext`. I wonder if there is a good way to unify the provider, without breaking current implementation and behavior. I would investigate more about it.

> I mean that it can be handled internally

So, it seems that you mean to add a `contentMode` parameter to downsampling processor, with appending a normal resizing processor? Is my understanding correct?

**Comment by gabors** [comment]
I also noticed that there is no way to control the location of the disk cache folder.
Which is livable for iOS/tvOS apps, but on macOS the caches folder is created under 
~/Library/Caches/com.onevcat.Kingfisher.ImageCache.default

I would like to be able to store this instead under 

~/Library/Caches/MY_APP_FOLDER/com.onevcat.Kingfisher.ImageCache.default

There is a closure I saw used for generating the directory path but it is marked as internal. Please advise.

**Comment by andrei-kuzma** [comment]
> > My case is when content of cache directory was deleted manually.
> 
> There seem to be two possible options for it:
> 
> 1. Check folder existence every time and create one if it is not there.
> 2. Just give some log and information.
> Or there is another way: trying to check and recreate the folder only when `createFile` fails, and then retry creating the file one more time. But it is a bit "magical" and hiding things, adding internal complexity, which I do not quite like.

For me handling file creation failures is more logical as it will not influence on performance on normal scenarios. It just like a handling errors: something goes wrong, we should check why and restore state (recreate directory, clean disk cache if there is not enough disk space etc.). Probably 'retry' adds more complexity but this step is not required as it is not critical path. The main goal is to avoid new failures

> So, it seems that you mean to add a `contentMode` parameter to downsampling processor, with appending a normal resizing processor? Is my understanding correct?

I'm not sure which option is better: have downsampling with contentMode and resize processors separately or have one resize processor that do downsampling internally if needed.
The goal of this processors is decrease memory usage and minimize image size(that also has influence on memory and performance)
First one gives me ability to decide myself which one is better on each case. The second one just gives me result that I want with best algorithm( I hope :)). 
The final decision can be made only after some tests for big and small images.
Probably when original image is much bigger than final it make sense to combine downsampling and resize and if not resizing is preferred. I don't know. But I think that it would be great if library provide
me processor that already has that algorithm based on tests.
I think we can have downsampling and resize processors separately and another one processor that uses both of them internally (of course if tests give us good results)
(Everything that I wrote are just thoughts. Currently I don't have enough time to test if it really make sense, may be in future I will. It will be great if someone can investigate this question)

Just one more thing.
I'm wondering what is the reason to call completionHandler when task was canceled or result of previous task is applied? Do you have real examples when it's needed?
I my scenarios I should always filter if !error.isTaskCancelled and  !error.isNotCurrentTask.
Probably that cases can be somehow separated from main completionHandler?
What do you think about it?

**Comment by onevcat** [comment]
@gabors 

I believe you could use [this init method](https://github.com/onevcat/Kingfisher/blob/master/Sources/Cache/ImageCache.swift#L225-L228) to create a cache with a given path or closure to customize the cache folder location.

**Comment by onevcat** [comment]
@andrei-kuzma 

Thanks for your kindly explanation. I got your idea and will see how can it be improved.

> Just one more thing.

Currently, every invocation on the `setImage` method would result a calling of `completionHandler`. This is a much more stable and predictable behavior compared to earlier implementation. I am sure it reduces the mental burden in development, you now do not have to think about when the complemetion would get called and when it would not. It also provides more information on every possible cases.

For your case, if you do not care about these two errors, instead of writing the filtering again and again, you could try to add a wrapper to ignore them and use your wrapper method:

```swift
extension KingfisherWrapper where Base: UIImageView {
    func mySetImage(with url: URL, completionHandler: ((Result<RetrieveImageResult, KingfisherError>) -> Void)? = nil) -> DownloadTask?
    {
        setImage(with: url) { result in
            switch result {
            case .success:
                completionHandler?(result)
            case .failure(let error):
                if !error.isTaskCancelled && !error.isTaskCancelled {
                    completionHandler?(result)
                }
            }
        }
    }
}
```

And here are suggestions from me on error handling in Kingfisher:

1. Create a general method or an extension method to make you error handling in the same place as possible as you can. Do not write error handling code everywhere when you call `setImage`, which will lead you to a situation of "repeating yourself".
2. Only pick up the errors you are most interested in, and let the user know what happened. For most image downloading tasks, it is not so critical in failing download or setting an image, especially if you have a retry mechanism (for example, setting the image again when scrolling in a table view). So do not bother your users for an error. (In fact, in my own use cases, I called `setImage` in almost 100 files, but only use the completion handler in two places).
3. If needed, you could also create your helper methods and properties by extending `KingfisherError`. This could more or less make the error handling easier.
