### ISSUE TITLE
unable to load local files in 5.0 using ImageDownloader

### ISSUE THREAD

**Issue by Omgitsu** [onevcat/Kingfisher#1104]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [x] I want to report a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

### Issue Description

# KingfisherLocalBug

In Kingfisher 4.0 you could load images from the local disk without needing a `LocalFileImageDataProvider` provider.  
In Kingfisher 5.0 attempting to load from the disk without a provider will always give you an error stating 
`load failed with error Error Domain=NSURLErrorDomain Code=-999 "cancelled"...`

#### What

while you can load from the disk with a provider using
`LocalFileImageDataProvider(fileURL: url)`

using the ImageDownloader fails with the same `NSURLErrorDomain Code=-999` 
and `ImageDownloader.default.downloadImage(with: url...` does not provide an ability to set a provider.

Is this a bug, or is it something that should be added to the ImageDownloader.

#### Reproduce

Demo project is here:
https://github.com/Omgitsu/KingfisherLocalBug

#### Other Comment

To be honest, I'm unsure if this is actually a feature request for the ImageDownloader class.

**Comment by onevcat** [comment]
Sorry for the late reply.

This behavior is caused by [this line](https://github.com/onevcat/Kingfisher/blob/master/Sources/Networking/SessionDelegate.swift#L147), which only accepts HTTP response when using an `URLSession` to fetch the image.

The original behavior of Kingfisher version 4 and before was unexpected and it just happened to work for local images. In Kingfisher 5, we now have a [local image data provider](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#image-from-local-file) which works better for this kind of images, at the same time, get benefits from Kingfisher's other related features. (Compared to initialize a URL session and load a data in a stream, it is easier and intuitive to handle a file directly.)

**Comment by onevcat** [comment]
Furthermore, the `ImageDownloader`, as the name suggests, is a downloader for images from the Internet. To load an image from a provider, you can just use the `retrieveImage` for `Source` in `KingfisherManager`. Internally, it will check the cache and then ask the image provider to return an image if necessary. Adding a general `Source` "downloading" method to `ImageDownloader` may not be a good idea and more or less violates the single responsibility of that type.
