### ISSUE TITLE
Avoid flickering on reloadData()

### ISSUE THREAD

**Issue by wieseljonas** [onevcat/Kingfisher#114]
I spent quite a while figuring this out. I thought it might be useful for others.

This is how I implemented the image call in my cell to avoid this annoying flick.

```
 if let newURL = mainProfile?.thumbnailImageURL{
            if (newURL == self.cellImage.kf_webURL?.relativeString) && self.cellImage.kf_webURL?.relativeString != nil {
                print("nothing to do")
            } else {
                self.cellImage.kf_setImageWithURL(NSURL(string: newURL)!, placeholderImage: UIImage(named: "no photo"))
            }
        } else {
            self.cellImage.kf_setImageWithURL(NSURL(string: "")!, placeholderImage: UIImage(named: "no photo"))
        }
```

The trick is that you cannot only set the image if nothing needs to be displayed as kingfisher stores the weburl if it was set in the reused cell.

**Comment by onevcat** [comment]
Thanks for pointing it out!

Yes, Kingfisher stores the url to identify the image view to prevent multiple setting image for the same image view. By holding a url, it can only update for the last downloading task. But it is not the real reason about this flicking. The problem seems to be the unnecessary queue dispatching when retrieving an image from memory.

Instead of solving it by checking url, I guess I have a better approach for it.

I will take a look at it later. Thank you！

**Comment by onevcat** [comment]
Fixed in #116

**Comment by wieseljonas** [comment]
I will give it a spin! Thanks

**Comment by wieseljonas** [comment]
Working like a charm

**Comment by onevcat** [comment]
Thanks for the feedback. :)

**Comment by wieseljonas** [comment]
Hi @onevcat I seem to be having this issue again can't really trace back to which version since I updated the library recently in my project

**Comment by onevcat** [comment]
@wieseljonas Tried to reload data but didn't see a flickering in the latest demo project. What's your implementation now?

**Comment by wieseljonas** [comment]
Ignore this it was simple the fact that the cell reloading animation was set to fade, setting it to none fixed it

    tableView?.reloadRows(at: [indexPath!], with: UITableViewRowAnimation.none)

**Comment by onevcat** [comment]
：）
