### ISSUE TITLE
Cannot mutate property 'kf' of immutable value 'image'

### ISSUE THREAD

**Issue by ChardXu** [onevcat/Kingfisher#1149]
Since these two days updated Xcode 10.2, then Kingfisher reported an error, should it be a Swift5 compatibility issue? What should I do, or will you update the version to handle this? As the app is eager to update, look forward to your reply! Grateful!
`Cannot mutate property 'kf' of immutable value 'image'`
And another question：
`Command CompileSwift failed with a nonzero exit code`

**Comment by vermaamit38** [comment]
You are getting this error because you might be using Kingfisher version 5.1.1 and updating your CocoaPods  won't help you either, You need to update to at least version 5.2.0 . for that just download https://github.com/onevcat/Kingfisher/archive/5.2.0.zip and open *Pods>Kingfisher* . You can see Source folder there just replace this **Source** folder with the new **Source** folder from **Kingfisher-5.2.0** one which you have downloaded .  And try to run it will work.

**Comment by onevcat** [comment]
This should be already fixed in an earlier version. Please upgrade Kingfisher to the latest version.
