### ISSUE TITLE
Error fetching files from disk.

### ISSUE THREAD

**Issue by hasankose** [onevcat/Kingfisher#1152]
### Check List
- [x] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), I've found one similiar issue, but I couldn't be sure if they are same.

### Issue Description

I can not load files which have already been saved to disk with Kingfisher V < 5 when I update Kingfisher to V > 5 (I tested with the version 5.3.1).

#### What
The function above always returns true, because the `estimatedExpirationDate` is always less than the current date, so, it is always in the past after I've done the migration to Kingfisher 5. 
DiskStorage.swift, line 143
```swift
if meta.expired(referenceDate: referenceDate) {
    return nil
}
```

#### Reproduce

Save files to disk with Kingfisher V < 5, then update Kingfisher to V > 5. Open the app without the Internet. The files won't be shown up.

#### Other Comment
Probably I need to extend expiration dates in modificationDate for currently saved files if there is a migration to Kingfisher 5 from an earlier version. However, I don't think it is a good idea to change the attribute of a file. 

ie: When I set the expiration config to .never and download a file, the modification date of the file is set to 2062(something like that). It means the file never expires until the date, If I change my config to X days with the new app update, the attribute is not gonna be changed. So the file never expires anymore.

I was gonna create a PR, but the change affects few classes, I wanted to discuss first, what is the reason for writing the date to attributes instead of use expiration attribute in the framework dynamically? or Am I doing something wrong? What might be a reason for the issue?

Also, this issue might be related to the issue (1104).

**Comment by onevcat** [comment]
@hasan-monument 

Thanks for your detail description and pointing out the behavior.

> Save files to disk with Kingfisher V < 5, then update Kingfisher to V > 5. Open the app without the Internet. The files won't be shown up.

As you may already know, both the disk cache and memory cache was fully rewritten in Kingfisher 5. The new version is now using a different strategy to determine cache expiration (by using the modify date attribute of the file), and there are also several image processor changes, which requires an invalidating of old caches.

It is not recommended at all to rely on the image cache for your app logic. The purpose of the cache is only for boosting image loading, and when there are no valid ones, it is expected to download it again. Besides that, the Kingfisher's image cache is under the Cache folder by default. The iOS system could even purge it when the disk is full, without giving your app or Kingfisher any notification. So relying on the cache to build your project is not a good choice.

> ie: When I set the expiration config to .never and download a file, the modification date of the file is set to 2062(something like that). It means the file never expires until the date, If I change my config to X days with the new app update, the attribute is not gonna be changed. So the file never expires anymore.

It might be an issue in some case. In the current implementation, the `extendExpiration` method in `DiskStorage.FileMeta` will just extend the expiration date by the original value when the image was stored. For the `.never` case, `Date.distantPast` is used, so the value remains the same. That means only the first image setting call (which downloads and stores the image) could determine the expiration date, and following calls respect the setting and only extend the duration with the initial setting.

It is not hard to change the behavior to respecting the latest image cache access. However, this would introduce a much more complicated mind model since there would be racing or conflicting between different settings. Consider that you are accessing the same cached file from different parts of your code, but with the different expiration dates, the last-win strategy is quite possible to cause the image expired unexpectedly just due to access from another access, even it is nothing to do with storing the image to cache.

If the expiration change is very important to you, you can always use `ImageCache.removeImage(forKey:)` to remove it from cache then reset it with the new expiration date, or just use another key (for example, with your version information) to create another cache file.

 > what is the reason for writing the date to attributes instead of use expiration attribute in the framework dynamically

Not quite sure about what you mean by "dynamically". Since it is a cache on the file system, we need a way to store the expiration date for each file. Using the file attributes makes no dependency and it is easy to operate, so I chose that (Otherwise, maybe we need a database or another file to persist this information).

**Comment by hasan-monument** [comment]
Thanks for your detailed explanation. I understood your consideration, but I have a concern regarding the new structure.

> That means only the first image setting call (which downloads and stores the image) could determine the expiration date, and following calls respect the setting and only extend the duration with the initial setting.

What I mean by "dynamically" is to calculate the date difference at the time of access. I think the performance is pretty much similar, but this gives us the benefits of:
- being able to change the cache expiration config after the files already have been downloaded and `extendExpiration()` function has been called.
- not losing the real modification date, as well as not using the attribute beyond its intended purpose.

**Comment by onevcat** [comment]
@hasan-monument I fully understood your standpoint. Either (using the settings from first storing calling, or respect every access later) has its own pros and cons. But updating the expiration date every time seems to be more intuitive since it is explicitly set as an option. Let's update that!

But I still wonder in your suggest below:

> not losing the real modification date, as well as not using the attribute beyond its intended purpose.

Now Kingfisher is using file creation date as "last access" date and using modification date as "estimated expiration" date. Using the "last access" with an input `expirationDate` when access can determine an image is expired or not. However, the estimated expiration date is also needed for cleaning the expired disk cache from time to time. Do you mean there is a better way for this purpose without touching the file attributes?

**Comment by hasan-monument** [comment]
I totally understood "last access" and "estimated expiration" purposes in the code. However, I think we lose real modification date and creation date of a file by overwriting file attributes. Using these attributes as "last access" and "estimated expiration date" isn't their intended purpose.

> Do you mean there is a better way for this purpose without touching the file attributes?

My suggestion is to calculate the date difference at the time of file access like old implementation instead of keeping expiration dates for all files in their file attributes:
```swift
let expiredDate: Date? = (maxCachePeriodInSecond < 0) ? nil : Date(timeIntervalSinceNow: -maxCachePeriodInSecond)

if let expiredDate = expiredDate, 
let lastAccessData = resourceValues.contentAccessDate,
(lastAccessData as NSDate).laterDate(expiredDate) == expiredDate {
    // expired file
}
```

In this way, we will have these benefits:
- Being able to change the cache expiration config after it has been initially set
- Preserve current file attributes

**Comment by onevcat** [comment]
The old way prevents the flexibility to set a different expiration period for each image (unless put them to different caches). But I really need this feature in my projects. 😂

For its benefits:

> Being able to change the cache expiration config after it has been initially set

Let's keep current v5 implementation and respect the setting from access, so you can also change the expiration after it is initially set.

> Preserve current file attributes

We really need an easy way to store these related dates, if we want to keep flexibility on the scope of each file. Normally these cache files are managed by Kingfisher and from outside users should not care about them, I think it is acceptable to use file attributes for now. But we'd better provide more information and detail in the doc for it.

How do you think about that?

**Comment by hasan-monument** [comment]
> The old way prevents the flexibility to set a different expiration period for each image (unless put them to different caches). But I really need this feature in my projects. 😂

According to the last sentence, I don't have any other option besides accepting that. 😃 
I don't need to keep separate dates for each file and don't want to lose creation and modification dates, so, I think the only way is to fork the project and use our own expiration date checking.

> But we'd better provide more information and detail in the doc for it.

This will make it more clear.

**Comment by onevcat** [comment]
Now, an option to customize the cache refreshing policy is provided through #1196 and #1287 

I am closing it now. Sorry for the inconvenience!
