### ISSUE TITLE
How are images cached and in what event are they downloaded again?

### ISSUE THREAD

**Issue by pennywise94** [onevcat/Kingfisher#1159]
I have been working with Kingfisher for a couple of months now. I use it primarily to download and cache user profile pictures (small images, approx. 200 kB in size per item). This all works great, so I first want to thank you for the amazing library that has been provided to us. 

However, today I redirected the IP of my backend file storage server to another IP address. Obviously, the images were not available on that new IP address. As soon as I opened my Swift iOS app, the images were blank. This makes me wonder: if the images are cached to disk (set to expire .never) and memory, why would it immediately show this white, blank image instead of the cached one? The IP address of the server did change, but the URL did not: filestorage.com/profile/1/image.jpg is still the same URL as it was before.

When does Kingfisher detect and download cached images again? Shouldn't it have shown the images that have already been downloaded on this existing address instead of the blank images?

To reproduce:

1. Use a backend server that stores files e.g. mystorage.com/files/test.jpg. Load this image in a UIImageView using Kingfisher
2. The image should now be cached and not being downloaded again from the Internet the next time I use or open the application
3. Delete mystorage.com/files/test.jpg - the UIImageView in my app will show a blank image rather than the previous image that had been cached, while I have not reset the cache or anything whatsoever

I am merely looking to avoid downloads when not necessary. Is there a logical explanation for the behavior I am experiencing?

Thanks again for this great library.

**Comment by onevcat** [comment]
Hi,

I tested with your steps and here is what I did and got:

1. Setup a local server and put an image at "http://127.0.0.1:8080/image.jpg"
2. Open an image view and set the image:
    ```swift
    imageView.kf.setImage(with: 
        URL(string: "http://127.0.0.1:4000/assets/images/avatar.jpg")!,
        completionHandler: { 
            result in print(result)
        }
    )
    ```
3. It prints a result with "Kingfisher.CacheType.none", which is good.
4. I stopped the local server and the whole "http://127.0.0.1:4000/" now is down.
4. Then, I call the method above again, it prints "Kingfisher.CacheType.memory" and image loaded.
5. I put the app to background and open it again. Then load the image with the same method. It prints "Kingfisher.CacheType.disk". It is fine because the memory cache will be purged when the app inactive. Loading the image again will fetch the disk cache.
6. Force quit the app and restart it again, load image. It prints "Kingfisher.CacheType.disk" and the image was loaded without issue.

So in my case, everything seems to be good and expected. No issue was found in my attempt.

Some suggestions for you to check and debug:

1. Make sure you are using the same url (and the cache key) every time for the same image. You can use "print(url.cacheKey)" to see what the key is being used. (It is the most possible reason for your case).
2. Setting disk expiration to `.never` does not ensure the images would be in disk forever. Kingfisher is using the "Cache" folder for disk caches, and this folder would be managed by the iOS system. If your disk is full, iOS might remove the cache folder without noticing you. So in this case, the disk cache will not persist.
3. There is also a size limit in disk cache (it is unlimited by default). If you set the limit yourself, it may also trigger disk cache purge from time to time.

**Comment by pennywise94** [comment]
Thank you for the comprehensive answer and your own testing, @onevcat. That's amazing.

I managed to figure it out. First of all, the cacheKey was indeed something I needed to define myself. Now I save the profile picture cacheKey myself (as "userID/imageName.jpg"). This did the trick.

However, something else I encountered, but this is just a thought and I haven't had time to do more testing, but could it be that this only works on physical devices? Meaning, there is no cache on the iOS simulator or it is cleared more often? I noticed just now that it did work on my physical device, but not in the simulator. However it does now, so I am unsure what the reason behind that could be.

For me the cacheKey fixed it. Thank you so much!

**Comment by onevcat** [comment]
> there is no cache on the iOS simulator or it is cleared more often

As far as I know, there is no difference between simulator and device on the cache. Maybe there were just some uncleaned states for your app in the simulator. Feel free to reopen this issue with more information if you can reproduce that in the simulator.
