### ISSUE TITLE
Add prebuilt carthage framework

### ISSUE THREAD

**Issue by gotev** [onevcat/Kingfisher#1179]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [ ] I want to report a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

#### What
Add a prebuilt carthage framework to every Kingfisher release to speed up build times when using it in apps.

## Motivation and Context
I'm using carthage as dependency manager for my projects and I use Kingfisher extensively, thank you for the awesome work! Carthage builds all the dependencies from source every time, unless they have a prebuilt framework attached to the github release. By attaching it, the client simply downloads the framework and build times are much faster.

## Proposed Solution
```
## do this only the first time on your mac or CI
## https://github.com/github/hub
brew install hub

## to create a release, from the project's root
carthage build --archive
hub release create -a Kingfisher.framework.zip -m "tag comment" "tag version"
```
And you will get a release like this (taken from RxSwift)
![Schermata 2019-05-10 alle 11 44 06](https://user-images.githubusercontent.com/16792495/57518274-f480c580-7318-11e9-950e-3e5d831beed9.png)

**Comment by onevcat** [comment]
Hi,

Thanks for the suggestion.

Currently, Swift does not have framework ABI stability, this could easily break if the user is not using a compatible Swift compiler version, so it is not supported. In the very early age of Swift and Carthage, some frameworks supported pre-built binary, but it soon turned out to be not a good idea to do so.

It definitely worths to add it after Swift ships with module stability later this year. For now, you can use the cache build option of Carthage to avoid building Kingfisher every time. In my own experience, it works pretty well without problems.

**Comment by JosephDuffy** [comment]
I came here to check if this has been asked for and I was going to open a PR with a change to the `release` lane in the Fastfile that would do this, but I'm guessing it wouldn't be accepted?

For what it's worth I think it's still useful to provide the prebuilt framework – even if module stability isn't yet available – because Carthage will detect if the prebuilt framework was built with an incompatible version of Swift and rebuild locally (if required).

Of course this is your library so it's your decision, but I'm happy to open a PR if this is something you would like adding :)

**Comment by onevcat** [comment]
@JosephDuffy 

Oh, thanks for the information. So it seems that there is no hard to contain it. 

Yes, I'd like to see a PR for it!

Thank you!
