### ISSUE TITLE
Crash when update last version

### ISSUE THREAD

**Issue by daveleenew** [onevcat/Kingfisher#1190]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [x] I want to report a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

### Issue Description
crash
#### What

self.avatarImageView?.kf.setImage(with: url, placeholder: placeholder)

crash

#### Reproduce

[The steps to reproduce this issue. What is the url you were trying to load, where did you put your code, etc.]

#### Other Comment

[Add anything else here]

**Comment by onevcat** [comment]
We didn't receive this kind of report. Since all the tests are passing so it is not likely a problem inside Kingfisher. 

Please try a clean build and also integrating the latest Kingfisher to your project again. If it is keeping crashing, please also attach a log in which we can know what happens.

**Comment by muzoman** [comment]
I'm experience a crash with a similar line of code:

            imageView.kf.setImage(with: URL(string: imageURL), placeholder: image)

I get a SIGABRT  and the execution of the App stops before I can even get a stack trace.

**Comment by onevcat** [comment]
@muzoman Any chance to try a full clean build?

**Comment by muzoman** [comment]
@onevcat Thanks, a full clean build has fixed the issue. I wonder why not doing a full clean build caused the problem?

**Comment by onevcat** [comment]
Because we have changed some calling convention (by introducing new APIs) in the latest version. However, Xcode (or say Swift compiler) is lack of a way to detect it. It is a bit hard to explain in detail, but it should not happen again when we can have the module stability in near future. (If you are interested in related topics, maybe [this article](https://swift.org/blog/abi-stability-and-more/#module-stability) and this [forum post](https://forums.swift.org/t/plan-for-module-stability/14551) would help.)
