### ISSUE TITLE
Kingfisher vs SDWebImage

### ISSUE THREAD

**Issue by AvdLee** [onevcat/Kingfisher#12]
Good to see the work done to create this purely Swift image framework. I'm using SDWebImage in a lot of my projects, purely because it's known as stable and we're used to it in our projects. As we are now switching to use Swift in our projects, I'm looking for alternatives like Kingfisher.

SDWebImage can be used in iOS 7, what about Kingfisher? This is one important requirement for our projects. 
Furthermore, can you tell anything about the performance difference between using SDWebImage and Kingfisher?

**Comment by onevcat** [comment]
Hi,

Kingfisher does not support iOS 7, since it is using cancelable block object and an option of low priority when downloading, which is iOS 8 feature.

Kingfisher is very young and I suggest you persist in SDWebImage if you need to support iOS 7 for a while. Kingfisher would be a choice if you prefer sure Swift instead of Swift/OC mixed.

About the performance, I did not do a benchmark myself. But the core implementation of both is similar, so I guess you can expect similar performance if you use Kingfisher.

**Comment by AvdLee** [comment]
Thanks, clear answer. Will mark this project to use in the next iOS 8 only project.

**Comment by onevcat** [comment]
:) Thanks!
