### ISSUE TITLE
Image.swift line 202 Crash - specialized DefaultCacheSerializer.data(with:original:)

### ISSUE THREAD

**Issue by soryncrash13** [onevcat/Kingfisher#1213]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [ok ] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [ ok] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [ok ] I want to report a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

### Issue Description
Unfortunately I've just got a missing dsym and upon uploading it I've got this crash (which i've never ran upon before). Even in our testing sessions we never got any crash inside this library's code.
#### What
This is what I have:
Image.swift line 202
specialized DefaultCacheSerializer.data(with:original:)
line 202:  return base.jpegData(compressionQuality: compressionQuality)

#### Reproduce
I'm really sorry but I really don't know how to reproduce it since we never ran into it. Of course we're keep on trying to reproduce it and come back with an update but for now I really don't have anything.

#### Other Comment
If anybody ran into this issue any comment or idea on what to check up might be useful so please feel free to share anything.

**Comment by onevcat** [comment]
Thanks for reporting it.

It's quite hard to say what causes it. The related code indicates that some issue happens when converting an JPEG image to its data representation and it is in the UIKit instead of Kingfisher :(

Maybe it could be due to some not enough memory issue, or it might because a malformed JPEG image. But we need more information before we can get a conclusion.

There is very little we can do now, so I am closing it. If anyone has more info or a sample to reproduce the crash, please feel free to reply and reopen it!

**Comment by soryncrash13** [comment]
@onevcat Thank you. I really don't know how to reproduce it and i don't even have any more details. If i will ever get anything I will return to add more details.
