### ISSUE TITLE
ContentMode switching of UIImageView with animation

### ISSUE THREAD

**Issue by ghazi256** [onevcat/Kingfisher#1217]
I had imageview in tableview set to contentmode equal to center and I am displaying a placeholder image. As the size of image view is dynamic I have to keep contentmode as center. 

When kingfisher is done with the download when success block is called I am switching back to scaleaspectfill (in success block) but a weird animation happens. 

The downloaded image is directly set to center and after the animation, it is switched back to fill mode probably because the success block is called after setting the image.

Any suggestion on how to change contentmode during the animation???

**Comment by onevcat** [comment]
I am not quite sure about the animation. Are you trying to use some transition [provided by Kingfisher as a option (one of these)](https://github.com/onevcat/Kingfisher/blob/master/Sources/Image/ImageTransition.swift#L45-L63)? 

If so, it would be too late for you to update the content mode in the success block. The success block will not be called until the image setting and animation all done.

I myself do not have a chance to try, but I think there are two ways to solve it:

1. [Check whether your images are cached or not first](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#check-whether-an-image-in-the-cache). If already cached, set the content mode to what you want before you call the Kingfisher's image setting method. If downloading is required, you can use [this delegate method](https://github.com/onevcat/Kingfisher/blob/master/Sources/Networking/ImageDownloaderDelegate.swift#L74-L86) to know when the image is prepared, then change the content mode there. It happens just before the image gets actually set to the image view, so you can get rid of the resetting of image.

2. Do you use the built-in transition effect. Kingfisher provides a way to [customize transition](https://github.com/onevcat/Kingfisher/blob/master/Sources/Image/ImageTransition.swift#L63-L66). There you can set the content mode before the transition happens. However, you need to re-implement the transition animation yourself. But it should be not hard since you can refer to the code of other transition effect.

**Comment by ghazi256** [comment]
I am using the KingFisher provided animation. I think the number 1 point that you mentioned might help with my problem thanks I am closing the issue.
