### ISSUE TITLE
Kingfisher return error when load an url contains japanese

### ISSUE THREAD

**Issue by TungVuDuc2805** [onevcat/Kingfisher#1285]
Hello, I cannot load image with url : https://spi-ra.jp/wp-content/uploads/2019/09/あRP27988_1012.jpg

I tried to encode the url to : https://spi-ra.jp/wp-content/uploads/2019/09/%E3%81%82RP27988_1012.jpg

But it still doesn't work.
Can you help me ?
Thank you

**Comment by onevcat** [comment]
Encoding it should work fine.

I can download this image, although the extension is "jpg", but it seems that the real format is WebP. Kingfisher does not support WebP, since it is not a standard image format on iOS platform yet. Please take check [this](https://github.com/onevcat/Kingfisher/wiki/FAQ#can-i-load-some-special-image-format-like-webp) if you want to load and decode a WebP image.
