### ISSUE TITLE
Invalid cache when building with Carthage

### ISSUE THREAD

**Issue by EmDee** [onevcat/Kingfisher#1307]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [x] I want to report a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

#### What

I'm getting `Invalid cache found for Kingfisher, rebuilding with all downstream dependencies` when building `Kingfisher` with the `--cache-builds` parameter.

I tried clearing the `Carthage` cache (`rm -rf ~/Library/Caches/org.carthage.CarthageKit`) and removing all `Carthage` related files before installing, but the error will still up, when running the `carthage bootstrap` command a second time (after the cleanup).

#### Reproduce

Running `carthage bootstrap --platform iOS --cache-builds` will produce the bug every time.

#### Other Comment

I'm not entirely sure with which version this started happening, because we were running a rather old version of `Kingfisher` (`4.10.1`) before upgrading to `5.8.1` and now `5.8.2`.

**Comment by EmDee** [comment]
Good catch!

I'm not too familiar on how the headers are added. Is that something that `Carthage` is doing or can the headers be added in the `Kingfisher's build phase?

**Comment by onevcat** [comment]
@EmDee @igorkulman 

Thanks for the feedback.

Removing the header files was an intended change in Kingfisher v5.8, since the framework cannot be used in ObjC and there should be no need to generate it. However, it seems that triggering a side-effect (or say bug) of Carthage. See https://github.com/Carthage/Carthage/issues/2882

Carthage fixed it in its master branch, but it is now not clear when they could tag it and release a new version.

As a temporary workaround, I will merge #1308 later today and release a new version. I guess we can remove the ObjC header again later.

**Comment by EmDee** [comment]
@onevcat That'd be great! It will probably take `Carthage` to release a version, considering their last release was in April.

**Comment by onevcat** [comment]
Done. https://github.com/onevcat/Kingfisher/releases/tag/5.8.3

**Comment by EmDee** [comment]
Just tested – works! Thanks again.
