### ISSUE TITLE
SwiftUI trhows error when 'import Kingfisher'

### ISSUE THREAD

**Issue by rigroch** [onevcat/Kingfisher#1340]
Xcode: 11.0
Kingfisher: 5.9.0
use Cocoapods

Good case:
![image](https://user-images.githubusercontent.com/939633/68523419-4fad6800-02fc-11ea-9d71-2a64db47d6f6.png)

Bad case: when  import Kingfisher
![image](https://user-images.githubusercontent.com/939633/68523425-694eaf80-02fc-11ea-8c34-d4a55ee16743.png)

I'd try that,
delete DerivedData
clean
pod deintegrate -> pod install
pod repo update -> pod install
Xcode restart
reboot

but keep going this issues..

Please help and fix it...

**Comment by onevcat** [comment]
Kingfisher was using `View`, `Image` and `Button` to express cross-platform types (UIView and NSView for example) for a long time. We cannot remove or change them for now as it is for back compatible. Now, you can choose one as a workaround:

1. If you only use `KFImage` for loading a network image, `import struct Kingfisher.KFImage` instead of importing the whole Kingfisher module.

or

2. Importing Kingfisher in another new file,  and `typealias MyKFImage = KFImage`, then use `MyKFImage` in the files where SwiftUI imported.

or

3. Rename the `View` and other conflicting types to `SwiftUI.View`.

These old cross-platform types are already marked as deprecated in Kingfisher. But we cannot simply remove them until the next major update. So currently there is nothing to do in Kingfisher with it.
