### ISSUE TITLE
Can't set maximum cache size of memory and disk 

### ISSUE THREAD

**Issue by sovanyuthchap** [onevcat/Kingfisher#137]
Hi all developers
The framework work perfect with Swift for downloading images and store in cache. I set cache.maxDiskCacheSize = 30 * 1024 * 1024 and cache.maxMemoryCost = 30 * 1024 * 1024. Max 30 Mb but it still save cache size of memory and disk over than 30 Mb.
How do I set maximum cache size of memory and disk ?

**Comment by onevcat** [comment]
I guess you are doing the right thing. But I just want to notice some detail here.

The memory size will be restricted to the limitation you set. However, instead of the byte size in memory, it is a "cost" related to your image resolution. Currently, Kingfisher is using the pixels count for it. When new data is being stored in memory, the total cost in cache will be checked and compared to your setting. If there is no enough cost for your new image, the largest one already in the cache will be purged.

However, the disk cache will not be purged until you switch your app to background or you call the `cleanExpiredDiskCacheWithCompletionHander` method manually. It will swipe the your disk cache to a size under the limitation.

And of course you need to set these properties on the correct cache. By default, Kingfisher is using the `ImageCache.defaultCache` for the UIImageView extension and default KingfisherManager.
