### ISSUE TITLE
Reduce size of Swift package (currently takes 15 seconds to fetch)

### ISSUE THREAD

**Issue by arielelkin** [onevcat/Kingfisher#1431]
Could anything be done to reduce the size of the Kingfisher Swift package? It takes a relatively long time to fetch:

![image](https://user-images.githubusercontent.com/1756909/79322944-7011cc00-7f05-11ea-84fe-7ff79751d050.png)

15 seconds is a long time when you it's over several clean + build cycles.

**Comment by onevcat** [comment]
Does this happen every time? Or is it just a temporary network/local CPU or memory issue?

The Kingfisher repo size is ~26MB now, I don't think it is a large repo yet. Compared to other packages in the screenshot, for example, `httpswift/swifter` takes ~11MB, but the fetching duration is just 20%.

I am not sure how and what Xcode does when fetching, but maybe the commit count or file count matters more (Kingfisher has 2000 commits, but swifter has only 600). It is not an easy task for us to reduce the size or the commits now (as Kingfisher is already a repo more than 5 years with ~2000 commits). Instead, I guess Xcode and Swift Package Manager should be able to do some optimization for this scale of repos?

Maybe it would be a good idea to open an issue on https://bugs.swift.org/ instead. Since if it cannot handle a repo like Kingfisher well, it would become useless soon when all packages grow to this scale.

> And I have to say there should be no need to do clean build that regularly. Let's trust the compiler 😂

**Comment by arielelkin** [comment]
> Does this happen every time? Or is it just a temporary network/local CPU or memory issue?

It happens every time I wipe the derived data folder. But not on every clean build. 

You're right that the problem seems to lie with SPM. I've raised an issue there as you suggested: https://bugs.swift.org/browse/TF-1247

**Comment by onevcat** [comment]
Maybe it can be due to currently Kingfisher is providing multiple build configurations (which provides a workaround for #1418 and #1423).

With Xcode 11.4.1 released, the workaround should not be necessary anymore. I will try to verify if it affects the fetching time (but I suspect it should not in theory). If reducing the target count can help, I will try to do that soon.

**Comment by arielelkin** [comment]
@onevcat this problem persists in Xcode 11.6

**Comment by sthwicked** [comment]
Yup, also noticed significantly larged fetch times compared to other packages

**Comment by onevcat** [comment]
Reduced the repo side. Now the fetch should be much faster. #1691
