### ISSUE TITLE
Global Image Fetch Failure Behaviour

### ISSUE THREAD

**Issue by mosaic-engineering** [onevcat/Kingfisher#1460]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [x] I want to report a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

### Issue Description

If the image fetch fails, there should be a way to define **global re-try behavior**. The current retry behavior works under the assumption that all previously failed URLs will re-attempt whenever `setImage` is called. However, the user may want to only attempt to fetch an image *once and once only*.

In addition, it would be a waste of networking resources to re-attempt image fetch on a URL failed initially due to problems such as...

- Invalid URL format
- Device being offline
- Endpoint is down

To accomplish this, there would have to be a global cache for failure attempts. With this assumption, the logic would be something like below

```swift
if globalFailureCache.contains(url) {
    return nil
} else { 
    return fetch(url)
}
```

#### Reproduce

```swift
// URL will be pinged every single time even though the request is inherently invalid
imageView.kf.setImage(URL(string: "https://invalid.ur.here")!)
```

#### Other Comment

If this behavior and be implementing via custom caching behaviors, i would love to know! Ty!

**Comment by onevcat** [comment]
Thanks for the feature request. However, I have several doubts about whether it is a feature suitable be in this framework.

In my opinion, this `globalFailureCache` hides too many details and makes a lot of assumptions. Take the cases in your post as examples:

> - Invalid URL format

Basically this would lead to an invalid URL, and you will fail when creating the URL itself. Passing a `nil` to Kingfisher's setting image method will do nothing expect setting the placeholder. So it should be fine enough.

> - Device being offline

Indeed we can detect the device online state before we do the actual request. But the same, it does not waste the networking resource since it is handled at a lower level of the system. It just knows the network status better than us (as a high-level API). More important, generally, you do not want to maintain a state and determine whether the device is going to online and allow these "failed" requests.

> - Endpoint is down

It uses some network resources, but very similar to the one above, the endpoint down could always be a temporary issue and the web resource (images) might be accessible in the next second. We should never assume it as a forever issue or prevent further retries.

---

As a conclusion, I myself do not see much benefit to adding this global re-try behavior. It would dramatically increase the complexity of this framework. Also, it might bring huge confusion to framework users, since sometimes by calling `setImage` does not actual work at all, and it would be too hard to debug.

I am closing this for now. But please feel free to append more comments if there is a better use case and I would be glad to discuss more.

Thank you!
