### ISSUE TITLE
Swift 5 update

### ISSUE THREAD

**Issue by sarrathy** [onevcat/Kingfisher#1461]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [ ] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [ ] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [ ] I want to report a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

#### What

[Tell us about the issue]

#### Reproduce

[The steps to reproduce this issue. What is the url you were trying to load, where did you put your code, etc.]

#### Other Comment

[Add anything else here]

**Comment by onevcat** [comment]
The code should be already Swift 5 compatible. However, since Apple [delayed the requirement of Xcode 11](https://developer.apple.com/news/?id=03262020b), there are still old versions of Xcode 10 being used to build apps with Kingfisher, we cannot drop set Swift version to 5 to the project setting yet.

We will update it as soon as Apple officially stops accepting old SDKs/Swift versions.
