### ISSUE TITLE
Getting a duplicate code error when trying to add Kingfisher 5.15.1 via Xcode 12 GM SPM

### ISSUE THREAD

**Issue by ethanwa** [onevcat/Kingfisher#1512]
<img width="442" alt="Screen Shot 2020-09-16 at 12 14 33 PM" src="https://user-images.githubusercontent.com/1653780/93364222-4ba07f80-f816-11ea-81b7-fd0ef0ac0c5f.png">

Any ideas what the issue may be here? 'collectors' is my project target and name.

**Comment by mpdifran** [comment]
SPM in Xcode only produces static libraries. If you want to include Kingfisher in multiple targets, you won't be able to use SPM at the moment. My guess for your setup is just link to `KingfisherDynamic` instead of `Kingfisher`.

**Comment by onevcat** [comment]
Due to a previous bug of Xcode, Kingfisher defined multiple libraries, including automatic (static) and explicit dynamic ones. Currently that bug was already fixed and there should be no need to separate them. But I choose to keep these targets for a while for back compatibility. If there is no good reason, please ensure you just link the standard one “Kingfisher” to your target, and remove any other ones (“KingfisherDynamic” for example) from your link library phase.

**Comment by ethanwa** [comment]
Setting it to just “Kingfisher” seems to have solved the issue. Thank you.
