### ISSUE TITLE
Parent transitions are not applied correctly after 5.15.1

### ISSUE THREAD

**Issue by windom** [onevcat/Kingfisher#1527]
### Check List

- [X] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [X] I want to report a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

### Issue Description

When a parent/containing view appears with a  transition, the image is not respecting it, but it appears instantly in its final position. See for example this video: https://imgur.com/a/zkh43oq

This was working correctly in 5.15.0, at least when showing the image from cache.

#### Reproduce

Code used to produce the video: 
```import SwiftUI
import KingfisherSwiftUI

struct ContentView: View {
    @State var shown = false
    
    var body: some View {
        ZStack(alignment: .top) {
            if shown {
                VStack {
                    KFImage(URL(string: "https://picsum.photos/100")!)
                        .resizable()
                        .frame(width: 100, height: 100)
                }
                .frame(height: 400, alignment: .bottom)
                .background(Color.red)
                .transition(.move(edge: .top))
            }
            VStack {
                Spacer()
                Button(shown ? "Hide" : "Show") {
                    withAnimation(.linear(duration: 1)) {
                        self.shown.toggle()
                    }
                }
            }
        }
    }
}
```

#### Other Comment

Your library is amazing, thanks for all your great work!

**Comment by onevcat** [comment]
There was no big change in SwiftUI support recently, so I guess it is more likely an issue (or say difference) between SwiftUI 1.0 (Xcode 11) and SwiftUI 2.0 (Xcode 12). I will try to investigate it but since Kingfisher is not touching much on the SwiftUI layout, I guess we'd better focus on how can solve it in SwiftUI side.

**Comment by onevcat** [comment]
Tried to make a minimal reproducible sample for it, as below:

```swift
@State var shown = false
@State var hasImage = false
var body: some View {
    ZStack(alignment: .top) {
        if shown {
            VStack {
                if hasImage {
                    Image(systemName: "gear")
                        .frame(width: 100, height: 100)
                }
            }
            .frame(height: 400, alignment: .bottom)
            .background(Color.red)
            .transition(.move(edge: .top))
        }
        VStack {
            Spacer()
            Button(shown ? "Hide" : "Show") {
                withAnimation(.linear(duration: 1)) {
                    self.shown.toggle()
                    DispatchQueue.main.async {
                        self.hasImage.toggle()
                    }
                }
            }
        }
    }
}
```

As above, the problem happens when the image is set after the transition started. Obviously the code above has nothing to do with Kingfisher and it is a SwiftUI issue (or a limitation) that the view cannot be changing during the transition progress. However, the image loading of Kingfisher is an async behavior so it obviously happens.

When loading from cache, it is a side-effect of changes in #1510. However, these changes are necessary and intended. I will check if there is another way to make things work better here.

**Comment by onevcat** [comment]
A possible (but maybe not ideal) workaround is initializing the `KFImage` earlier. It will start loading as soon as it is created, so when you make a transition, you can have a prepared/loaded image in that view. So everything would go fine.

```swift
import KingfisherSwiftUI

struct ContentView: View {
    let image = KFImage(URL(string: "https://picsum.photos/100")!) // <- Declare here. Be careful, it starts loading as soon as the `ContentView` created.
    @State var shown = false
    
    var body: some View {
        ZStack(alignment: .top) {
            if shown {
                VStack {
                    image    // <- Use the loaded image view here so it will follow the transition.
                        .resizable()
                        .frame(width: 100, height: 100)
                }
                .frame(height: 400, alignment: .bottom)
                .background(Color.red)
                .transition(.move(edge: .top))
            }
            VStack {
                Spacer()
                Button(shown ? "Hide" : "Show") {
                    withAnimation(.linear(duration: 1)) {
                        self.shown.toggle()
                    }
                }
            }
        }
    }
}
```

However, it will start the image loading as soon as the container view created, instead of the original logic of not loading it until you click the "Show" button. Please use it with care.

**Comment by onevcat** [comment]
@windom The core concept is waiting for the image loading done before you start the transition. Maybe you can also try to use the `onSuccess` callback of `KFImage` to wait for a signal before starting the transition. But I am not quite sure how can I implement it in SwiftUI (I am not using it yet in any of my own projects.) 

Let me know if you have any ideas!

**Comment by windom** [comment]
You are right, this broke with XCode12/iOS14 and your code sample makes it perfectly clear that it's got nothing to do with Kingfisher.

Thanks for the ideas; I'm still looking for a good/easier solution, because in my use case, the place where the transition is started and the actual KFImage view are far from each other, the image is nested deep down in reusable views. I'll get back if something comes up, until then I'll close this?
