### ISSUE TITLE
Crash: Disk Cache being created in the wrong location when using custom URLs on MacOS 10.16 Big Sur

### ISSUE THREAD

**Issue by tsfischer** [onevcat/Kingfisher#1538]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [X ] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [X ] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [X ] I want to report a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

### Issue Description
App crashes on launch, in Kinfisher init code, when launching from a custom URL

#### What

We've been using Kingfisher successfully for 3-4 years now. Upon testing our app with MacOS 10.16 Big Sur, we've discovered a problem. When we launch the app normally, all is well. 

However, our app has custom URLs to interact with app features, in the form "myappname://custom/parms/for/the-app  

When I use Safari to launch our app using one of these custom URLs, it crashes, and I receive the following as part of the crash report:

Application Specific Information:
Fatal error: 'try!' expression unexpectedly raised an error: Kingfisher.KingfisherError.cacheError(reason: Kingfisher.KingfisherError.CacheErrorReason.cannotCreateDirectory(path: "/Users/timfischer/Library/Containers/com.apple.Safari/Data/Library/Caches/com.onevcat.Kingfisher.ImageCache.default", error: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “com.onevcat.Kingfisher.ImageCache.default” in the folder “Caches”." UserInfo={NSFilePath=/Users/timfischer/Library/Containers/com.apple.Safari/Data/Library/Caches/com.onevcat.Kingfisher.ImageCache.default, NSUnderlyingError=0x6000003ee460 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}})): file Kingfisher/ImageCache.swift, line 216

So the underlying problem is it's trying to create the underlying disk cache at "/Users/timfischer/Library/Containers/com.apple.Safari/Data/Library/Caches/com.onevcat.Kingfisher.ImageCache.default" and the OS is saying no can do.

We are using KIingfischer.shared for all of our calls, and it wasn't clear to me how to pass a directory down into that.

#### Reproduce

-Mac app which registers custom URL "myCustomURL://"
-Go to Safari and navigate to "myCustomURL://", with the app not already running.
-Crashes with the above-mentioned message.

#### Other Comment
I realize that this will be tough for you to reproduce. However, I think the issue of what is going wrong is pretty clear. If you can let me know how to specify my own cache directory when using Kingfisher.shared, that would be a good enough workaround for me. For the actual problem, it seems that DiskStorage.swift:62 is creating the directory at the wrong location.

Happy to email/text/zoom chat/whatever to get this resolved. Big Sur will be out Any Day Now.

**Comment by onevcat** [comment]
Ummm,

That is quite interesting. I am not installing a beta version on my mac, so I cannot verify it now. But I want to know, does the same issue also happen on macOS 10.15 or earlier (I guess not)? If not, I suggest you send feedback to Apple first. 

Here is what going on:

Kingfisher will try to create a cache folder in the [cache directory](https://github.com/onevcat/Kingfisher/blob/master/Sources/Cache/DiskStorage.swift#L62-L70) of `.userDomainMask`. I am not a developer of macOS myself, but I think it should be located at "~/Library/Caches". So, it is obvious that when launched from Safari, the system thinks the cache folder in Safari's container cache, which is not the user's cache folder, and not correct.

It is possible to replace the cache used in `KingfisherManager.shared`. However, in your case, it is happening when initializing the shared manager so you do not even have a chance to replace it. Instead, you have to use a manager created by you from scratch.

1. First create an `ImageCache` by [this method](https://github.com/onevcat/Kingfisher/blob/master/Sources/Cache/ImageCache.swift#L233-L236)
2. [Create a manager](https://github.com/onevcat/Kingfisher/blob/master/Sources/General/KingfisherManager.swift#L115-L121) with that image cache and the default downloader.

Then always use that manager. Since Kingfisher's image view extensions are all using the manager object, I am afraid you also have to update all `.kf.setImage` code, which would be quite hard.

Another easier way is just fork and modifies the DiskStorage.swift code to make it detect the folder and just specify a correct  "~/Library/Caches" url for macOS. If you find a good and robust way to make it work, a PR is warmly welcomed! (Again, since I am not a macOS developer myself and do not have 10.16 installed now, it is quite a tough work to verify all these things. So I need some help!)

Thank you.

**Comment by tsfischer** [comment]
Thanks for your response.

We verified his was a MacOS beta bug, and it has now been resolved. Closing this issue.
