### ISSUE TITLE
iOS14下，图片加载堵塞主线程

### ISSUE THREAD

**Issue by Toorealistic** [onevcat/Kingfisher#1560]
.kf.setImage(with: resource, placeholder: placeholder)
完全堵塞主线程

.kf.setImage(with: resource, placeholder: placeholder, options: [.callbackQueue(.dispatch(DispatchQueue(label: "com.kingfisher.Queue")))])
图片资源下载时能进入异步线程，但渲染的时候还是会堵塞主线程

系统iOS14.1，控件UITableViewCell上放个UIImageView

**Comment by onevcat** [comment]
The callback queue option is not for decoding the image in a background thread. For that, use [`. backgroundDecode`](https://github.com/onevcat/Kingfisher/blob/master/Sources/General/KingfisherOptionsInfo.swift#L100) instead.

**Comment by Toorealistic** [comment]
再次测试了下，发现好像是模拟器的问题。模拟器首次启动无图片缓存时，异步并行都正常的。但再次启动到列表页时，就会出现如上问题。

**Comment by onevcat** [comment]
What do you mean by async or concurrency? What is your issue?

I guess you are suffering a flickering during loading images from disk? If so, that is due to the disk loading is also an async behavior and you [need this](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#loading-disk-file-synchronously) to load things in the main thread.
