### ISSUE TITLE
Kingfisher Dynamic in SPM removed in 6.0.0

### ISSUE THREAD

**Issue by joeltrew** [onevcat/Kingfisher#1601]
Updating from v5 of Kingfisher through SPM, it seems the dynamic version is no longer available, previously I used KingfisherDynamic to support a nested framework with my app, however with v6 I now get "Swift package product 'Kingfisher' is linked as a static library by 'App Name' and 2 other targets. This will result in duplication of library code."

I looked through the v6 migration guide but there's no mention of the dynamic versions being removed, or what the alternative is.

Is there a new way around this, or am I missing something.
Thanks

**Comment by onevcat** [comment]
It is an intended removal in the new major version since I think it is much proper to let the build system handle how to compile a package instead of specifying it directly in Kingfisher. The original "fix" by adding the dynamic variety was for another Xcode bug and now it should be fixed in recent versions.

To keep using Kingfisher in your project across several targets, you can choose:

1. Remove your current Kingfisher reference from the library phase in all of your targets.
2. Create a Cocoa Framework target (dynamic linking), say "VendorFramework".
3. Add Kingfisher from SPM to the "VendorFramework" target.
4. Add "VendorFramework" to the targets you want to use Kingfisher and link to it.
5. `import Kingfisher`

**Comment by joeltrew** [comment]
Thank you @onevcat for explaining, and for your work on this project. That solution works great 👍
