### ISSUE TITLE
KFImage image disappear when scroll

### ISSUE THREAD

**Issue by kaich** [onevcat/Kingfisher#1618]
Use `KFImage`  in cell of  `LazyVGrid`.  When I scroll the grid, the loaded image disappeared and never show again.

**Comment by dopefaceee** [comment]
yes smae here

**Comment by onevcat** [comment]
Any code snippet? I tried the code below and everything works fine:

```swift
struct ContentView : View {

    let index = 1 ..< 700
    let columns = Array<GridItem>(repeating: GridItem(.fixed(100)), count: 3)
    var body: some View {
        ScrollView {
            LazyVGrid(columns: columns, content: {
                ForEach(index) { i in
                    KFImage
                        .url(URL(string: "https://github.com/onevcat/Flower-Data-Set/raw/master/rose/rose-\(i).jpg")!)
                        .resizable()
                        .scaledToFit()
                }
            })
        }
    }
}
```

**Comment by dopefaceee** [comment]
Using KingFisher v6.1.0

```swift
struct PokedexView: View {
    private let gridItems = [GridItem(.flexible()), GridItem(.flexible())]
    @ObservedObject var viewModel = PokeomonViewModel()
    var body: some View {
        NavigationView {
            ScrollView {
                LazyVGrid(columns: gridItems, spacing: 16) {
                    ForEach(viewModel.pokemon) { pokemon in
                        PokemonCell(pokemon: pokemon, viewModel: viewModel)
                    }
                }
            }
            .navigationTitle("Pokedex")
        }
    }
}
```
```swift
struct PokemonCell: View {
    let pokemon: Pokemon
    let viewModel: PokeomonViewModel
    let backgroundColor: Color
    
    init(pokemon: Pokemon, viewModel: PokeomonViewModel) {
        self.pokemon = pokemon
        self.viewModel = viewModel
        self.backgroundColor = Color(viewModel.backgroundColor(forType: pokemon.type))
    }
    
    var body: some View {
        ZStack {
            VStack(alignment: .leading) {
                Text(pokemon.name.capitalized)
                    .font(.headline)
                    .foregroundColor(.white)
                    .padding(.top, 8)
                    .padding(.leading)
                HStack {
                    Text(pokemon.type)
                        .font(.subheadline).bold()
                        .foregroundColor(.white)
                        .padding(.horizontal, 16)
                        .padding(.vertical, 8)
                        .overlay(
                            RoundedRectangle(cornerRadius: 20)
                                .fill(Color.white.opacity(0.25))
                        )
                        .frame(width: /*@START_MENU_TOKEN@*/100/*@END_MENU_TOKEN@*/, height: 24)
                    KFImage.url(URL(string: pokemon.imageUrl))
                        .resizable()
                        .scaledToFit()
                        .frame(width: 68, height: 68)
                        .padding([.bottom, .trailing], 4)
                }
            }
        }
        .background(backgroundColor)
        .cornerRadius(12)
        .shadow(color: backgroundColor, radius: 6, x: 0, y: 0)
    }
}



```

**Comment by mplanckensteiner** [comment]
same here, any idea how to store the image using Kingfisher? seems like LazyVGrid is causing the problem.

**Comment by fassko** [comment]
Have the same issue, I have Lazy VStack and inside there LazyHGrid.

**Comment by mplanckensteiner** [comment]
I am trying now with SDWebImageSwiftUI and seems like works perfect with LazyVGrid

**Comment by fassko** [comment]
@mplanckensteiner is SDWebImageSwiftUI working fine? For me, it was a bit lagging when scrolling.

I tried using FetchImage and had similar issues, but found this issue https://github.com/kean/FetchImage/issues/7

Maybe this could help out here @onevcat ? I'm long-time Kingfisher user and would like to keep using it in SwiftUI projects. :) At the moment because of lack of time can't help with PR .. :/

**Comment by onevcat** [comment]
I tried a bit more and had some fact. I believe now it is a SwiftUI bug when handling State management in `Lazy` container.

Say, if we have this code:

```swift
struct SampleView: View {
    let index: Int
    @State private var value: Bool = false

    var body: some View {
        Toggle("Toggle \(index)", isOn: $value)
    }
}

struct ContentView: View {
    let index = 1 ..< 10

    var body: some View {
        ScrollView {
            LazyVStack {
                ForEach(index) { i in
                    SampleView(index: i)
                }
            }.padding()
        }
    }
}
```

It is some toggles in a `LazyVStack`, very simple. It gives the correct result:

![ControlRoom-2021-02-07-16-30-31](https://user-images.githubusercontent.com/1019875/107139959-488f6280-6962-11eb-913a-fb676cc486eb.gif)


However, if we make a very tiny and trivial change here. Wrapping  `SampleView(index: i)` into another container, such as `VStack`:

```swift
truct ContentView: View {
    let index = 1 ..< 10

    var body: some View {
        ScrollView {
            LazyVStack {
                ForEach(index) { i in
                    VStack {
                        SampleView(index: i)
                    }
                }
            }.padding()
        }
    }
}
```

You will find the `@State` in `SampleView` is lost:

![ControlRoom-2021-02-07-16-34-45](https://user-images.githubusercontent.com/1019875/107139993-7bd1f180-6962-11eb-9162-f1ddf3470c72.gif)

Unfortunately, Kingfisher uses `@State` to "remember" the image loading result now. Based on the result, it decides to show an empty or placeholder view or the image. This `@State` is now reset by SwiftUI when `KFImage` is embedded inside a stack view, which causes this issue.

The same issue happens for `LazyVGrid`, which is what this issue describes.

Either my understanding of SwiftUI is not enough, or it is a bug of SwiftUI for its lazy container. But since the "directly using way" works fine, but a simple stack embeding causes it, I think it is more possible a SwiftUI bug and maybe we can expect a fix for it in the future from Apple. However, I will also look to see if we can have another way to workaround it without rewrite the whole `KFImage`. (Actually I have already rewritten it for several times and tired with the buggy thing 😂)

Stay tuned, and any help is welcome.

**Comment by onevcat** [comment]
I can have an ugly workaround in this branch [fix/lazy-container-state](https://github.com/onevcat/Kingfisher/tree/fix/lazy-container-state). You can try to see how it works as you need.

However, I personally do not like this one, and some features (such as the newly added `fade` modifier) would not work there.  So I am not sure yet whether that should be in an updated release version. I will see if there would be a better one.

**Comment by gregcotten** [comment]
Just out of curiosity, would [Equatable View](https://swiftui-lab.com/equatableview/) help fix this?

**Comment by bawarkamalqader** [comment]
I dont think it is only related to the way VStack works, since when i tried the same thing but with Kingfisher version 5.18.8, KFImage works fine even when in a VStack which is also in a LazyVStack.

It could be related to changes related to the way KFImage is reimplemented in version 6

**Comment by jkelol111** [comment]
Same issue here, downgraded to 6.0.1 and it works as expected again. I put my KFImages inside a GroupBox, those GroupBoxes are in a LazyVStack. Upon scrolling away the KFImages disappear and never come back.

**Comment by ArifADS** [comment]
I can confirm that downgrading to 5.18.8 or 6.0.1 makes it work great again, My KFImage is inside a view in a List.

**Comment by onevcat** [comment]
A workaround should be applied in 6.1.1. However, a better fix can be only made inside SwiftUI. Once the `@State` lost issue (https://github.com/onevcat/Kingfisher/issues/1618#issuecomment-774629095) can be made, we can revert the workaround in #1631 and have a clean implementation.

**Comment by liseami** [comment]
.anchorPreference(key: PostImageStrAndPostCardInfoPreference.self, value: .bounds) { anchor in
                [.init(attches: [], imageOnTapStr: UUID().uuidString): anchor]
            }
add To KfImage,will fix

**Comment by liseami** [comment]
> ```
>         .anchorPreference(key: PostImageStrAndPostCardInfoPreference.self, value: .bounds) { anchor in
>             [.init(attches: [], imageOnTapStr: UUID().uuidString): anchor]
>         }
> ```
> 
> 添加到 KfImage，将修复
Just add an arbitrary anchorPreference at will and the problem will be solved
