### ISSUE TITLE
iPhone 6s with iOS 14.3, Xcode log warning: unsupported file format 'public.heic'

### ISSUE THREAD

**Issue by iaomw** [onevcat/Kingfisher#1704]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [ ] I want to report a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

### Issue Description
When debugging with iPhone 6s with iOS 14.3, Xcode continue to print the log 
`findWriterForTypeAndAlternateType:119: unsupported file format 'public.heic'`

We know iPhone 6s is using A9 chip. This problem didn't happen with newer device, such as A12.

#### Reproduce

Should be easy to reproduce if you have some old device.

**Comment by onevcat** [comment]
Oh,

Thanks for reporting this!

Can I know what are you trying to do? Say, if you are loading an image from a certain URL, can I know the URL and how it is being loaded? It would be great if you can also provide some code snippet to demonstrate what you are doing.

**Comment by iaomw** [comment]
I think all of them are jpg or png. Any image link from this API under the key name `PreviewSphere `

`https://cc0textures.com/api/v1/full_json`

For the source code, it's a typical use case with SwiftUI & Kingfisher.

```
KFImage(URL(string: preview_link), options: [.transition(.fade(0.2))])
                .placeholder {
                    ProgressView()
                }
                .resizable().scaledToFit().padding(.top, 20)
```

**Comment by onevcat** [comment]
@iaomw 

I can reproduce this warning and tried to dig into it a bit. It seems that this warning is from either the `Data.jpegData` or `Data.pngData` method in iOS SDK. I can even reproduce it by the simple code below:

```swift
let imageData = try! Data(contentsOf: URL(string: "https://cdn3.struffelproductions.com/file/CC0-Textures/media/sphere/1024-JPG-FFFFFF/3DPastry002_PREVIEW.jpg")!)
let image = UIImage(data: imageData)!
let data = image.jpegData(compressionQuality: 0.8)
```

Except for the warning, it seems that all the features are running expected. Other than that, I don't think it is a thing can be fixed in Kingfisher level, but instead it should belong to UIKit. If you are concerning about it, I guess asking for help from Apple or submit a radar would help. 

I am closing it since there is very little we can do with this.
