### ISSUE TITLE
SwiftUI - Image gets blank in Context Menu

### ISSUE THREAD

**Issue by sameersyd** [onevcat/Kingfisher#1723]
Where the SwiftUI `Image` works properly, the `KFImage` get blank white in the Context Menu. Once the context menu dismisses focus, the image get's back.

**Comment by onevcat** [comment]
Ummm. Did you try the `loadImmediately()` method mentioned [here](https://github.com/onevcat/Kingfisher/issues/1660). If it is triggered by the same life cycle issue, maybe that method would solve it.

I have a plan to fix it from root in the next release, but it requires dropping iOS 13 so it still needs some time.

**Comment by sameersyd** [comment]
@onevcat `loadImmediately()` doesn't fix the issue!

**Comment by onevcat** [comment]
Can you paste some of code snippet? So I can try to reproduce this issue and see what can be wrong.

**Comment by sameersyd** [comment]
Hey @onevcat, I did some testing and got to know, it doesn't happen with normal view but when it's inside TabView.

I'll attach the code snippet and video of the app.

<img width="898" alt="Screenshot 2021-06-09 at 8 34 02 PM" src="https://user-images.githubusercontent.com/26275107/121382004-d6587a00-c963-11eb-8bb5-59dc2ce2ec41.png">

https://user-images.githubusercontent.com/26275107/121382033-da849780-c963-11eb-8954-d51f420e40b2.mov

**Comment by onevcat** [comment]
Ummm, I can reproduce this issue in `KFImage`, but at the same time, I can even reproduce the same with `SwiftUI.Image`, which is the underhood thing used to display an downloaded image inside Kingfisher SwiftUI support:

```swift
TabView {
  ForEach {
    Image(systemName: "swift")
  }
}
.contextMenu {
}
```

So I guess there is almost no way for Kingfisher to address this issue, since it apparently a SwiftUI bug. Maybe you can consider to submit a feedback to Apple and see if they can help.

And I find if you move `contextMenu` inside, to the `Image` or `KFImage` instead, the image would not disappear anymore. Is that an option for you?

```swift
TabView {
  ForEach {
    Image(systemName: "swift")
      .contextMenu {
      }
  }
}

```

**Comment by sameersyd** [comment]
It's not possible in my case to add into it. Maybe I'll try to report this to Apple.
