### ISSUE TITLE
Unable to create Build for App Store submission

### ISSUE THREAD

**Issue by ahsanaasim** [onevcat/Kingfisher#1727]
I have manually added Kingfisher in my iOS project. Project runs on my iPhone device. But when I try to make a archived build, it give too much errors. I am using MacBook Air Silicon series.

#### Reproduce
- Add Kingfisher manually in a project. 
- Try to Archive the project

This is where I added Kingfisher

<img width="1112" alt="Screenshot 2021-06-14 at 3 50 01 PM" src="https://user-images.githubusercontent.com/17532073/121873429-30708b00-cd28-11eb-9052-754b6dd18ef5.png">

Errors I am receiving. 
<img width="1057" alt="Screenshot 2021-06-14 at 3 48 54 PM" src="https://user-images.githubusercontent.com/17532073/121873286-09b25480-cd28-11eb-8b8c-c4628e80b700.png">

Asked the question in StackOverflow as well
https://stackoverflow.com/q/67968197/4060672

**Comment by onevcat** [comment]
May I know what is your deploy target? As I know, there is some linker errors that refuse to find the SwiftUI symbols when you set deploy target to iOS 10 or below. If you are targeting iOS 10, maybe you need to change it to iOS 11.

(Or try to exclude armv7, which drops iPhone 5 / 5C, iPad 4th gen/retina, see [this post](https://stackoverflow.com/questions/64389478/cant-archive-app-after-adding-swiftui-view) for more)

**Comment by onevcat** [comment]
If you still have to support those devices, maybe consider to fallback to Kingfisher version 5, which contained a separated target for SwiftUI.

**Comment by ahsanaasim** [comment]
My deployment target is 13.6

<img width="817" alt="Screenshot 2021-06-14 at 5 17 57 PM" src="https://user-images.githubusercontent.com/17532073/121884216-7895aa80-cd34-11eb-9cca-401283e1e9fc.png">

**Comment by onevcat** [comment]
Ummm, that is quite strange..

Can you make sure that you are not overriding this project setting in your app target?

I mean something like this and the final deployment target resolved to an early version:

![截屏2021-06-14 20 29 55](https://user-images.githubusercontent.com/1019875/121885577-48a7d080-cd4f-11eb-99fb-484d556f03c8.png)

**Comment by ahsanaasim** [comment]
No. Its same

<img width="1196" alt="Screenshot 2021-06-14 at 10 10 11 PM" src="https://user-images.githubusercontent.com/17532073/121923987-4c425400-cd5d-11eb-8ec0-fc25b574a4aa.png">

**Comment by onevcat** [comment]
I saw the `KFImage.swift` file in your screenshot and it looks containing some broken code before [this commit](https://github.com/onevcat/Kingfisher/commit/e30efd82368276664b9ffb8a10dc29cd6a6810da) for [this issue](https://github.com/onevcat/Kingfisher/issues/1710) ([ref](https://stackoverflow.com/questions/60073481/my-archive-build-fails-with-error-no-such-module-combine/62085591#62085591)).

Let's make clear that on which branch or tag you are on? Be noted that the `master` branch in under active development. So if you are manually cloning and dragging the Kingfisher project to your own project, I strongly suggest that you only refer to a certain tagged version listed here: https://github.com/onevcat/Kingfisher/releases

**Comment by ahsanaasim** [comment]
I just did what you said but after changing the framework from your latest release, App started crashing.
Here is a video of what I am facing now.

https://www.loom.com/share/facd75ef714845a6949f2ba0921eea83

**Comment by onevcat** [comment]
Hi, if you are going to use the xcframework, you need to drag the whole `xcframework` to your project, and link the same. The xcframework is a bundle of pre-built frameworks for all necessary pieces and Xcode will pick what it needs to use.

Alternatively, if you are going to use the source code and build the Kingfisher project with your project (as shown in your first screenshots), instead of downloading the "Kingfisher-6.3.0.zip" (xcframework which prepared for users need a binary format. Of course you can use that too), you should download the "Source Code (zip)" and add it as a reference to your project. You can refer to the manually section in the ["Installation Guide"](https://github.com/onevcat/Kingfisher/wiki/Installation-Guide#manually) to get to know the following steps after you have the source.

However, I have to say it is not recommend to integrate manually unless you have a good reason. Pick up a dependency manager (such as Swift Package Manager which is built into Xcode) will make your life easier. There are also other suggested installation steps in the same guide above. Hope you can get out soon!

**Comment by ahsanaasim** [comment]
moved to Swift Package Manager and everything is solved.
