### ISSUE TITLE
Custom image processor doesn't work

### ISSUE THREAD

**Issue by YogeshArora338** [onevcat/Kingfisher#1754]
I'm trying to use a custom image processor but it doesn't get call.

I created a separate file for image processor as follows:

```swift
public struct SVGImageProcessor: ImageProcessor {
    public var identifier: String = "svgimageprocessor"
    public func process(item: ImageProcessItem, options: KingfisherParsedOptionsInfo) -> KFCrossPlatformImage? {
        switch item {
        case .image(let image):
            return image
        case .data(let data):
            let imsvg = SVGKImage(data: data)
            return imsvg?.uiImage
        }
    }
}
```

And provided as an option while setting image.

**Comment by onevcat** [comment]
The processor will be only called when the image is downloaded from network and being prepared to show. So a quick answer is, you can use the `.forceRefresh` option to make Kingfisher always download and process the image, then you can try and test your processor. (But obviously you will lose the cache part of Kingfisher.)

So the cause of this issue (processor is not called) can be due to an internal optimization in Kingfisher: If you once have downloaded and cache an image without any process from this URL, it will be stored as an "original version". Later, if a processor is applied to the image loading method, Kingfisher will first try to search it (with processor) in cache. If not found, Kingfisher does a search for the original version of image, then apply the process with `.image` member. I believe at least your processor had been called once, but as soon as Kingfisher gets the correct image (from the `return image` in your `.image` case), it stores that image under with correct processor key and never call the processor again.

The correct and final solution is, this processor is going to converting data into an image, so you need also to provide a `CacheSerializer` (https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#creating-your-own-serializer) to help Kingfisher know how to store it on the disk and load it back from the disk. A possible implementation would be:

```swift
struct SVGCacheSerializer: CacheSerializer {
    func data(with image: Image, original: Data?) -> Data? {
        return data
    }
    
    func image(with data: Data, options: KingfisherParsedOptionsInfo?) -> Image? {
        let imsvg = SVGKImage(data: data)
        return imsvg?.uiImage
    }
}
```

**Comment by YogeshArora338** [comment]
Thank You! Actually I was supplying the query parameters in SVG url so that was causing an issue.
