### ISSUE TITLE
Kingfisher 内存问题

### ISSUE THREAD

**Issue by Tom-Jack-Huang** [onevcat/Kingfisher#1765]
在swift项目中，用 Kingfisher 加载三张图片（单个图片在2M左右）系统内存使用127M，但是 用 SDWebImage 加载同样的三张图 内存在上升到 86.2M后立即下降到 18.1M左右。这是为什么啊？

**Comment by onevcat** [comment]
It is not an issue and without providing further information, there is no way to identify what can be wrong.

For general performance questions, please refer to the [performance tips](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#performance-tips).

**Comment by Tom-Jack-Huang** [comment]
我简单写了个demo   https://github.com/Tom-Jack-Huang/KF_SD.git  你可以运行看一下内存情况  

[http://www.hlajxc.xyz/file/8FD4E19D-E24A-4B03-8F98-463CABFDC592.png](url)
[http://www.hlajxc.xyz/file/97ACD726-46EC-4614-AB63-A12CE499303C.png](url)

**Comment by onevcat** [comment]
Investigated and there is no different in memory usage between two. It is just because the Xcode debug panel not counting SDWebImage's memory in this case.

To get the memory graph and check its detail.  Result from SDWebImage:

```
                                VIRTUAL RESIDENT    DIRTY  SWAPPED VOLATILE   NONVOL    EMPTY   REGION
REGION TYPE                        SIZE     SIZE     SIZE     SIZE     SIZE     SIZE     SIZE    COUNT (non-coalesced)
===========                     ======= ========    =====  ======= ========   ======    =====  =======
Accelerate framework               256K     256K     256K       0K       0K     256K       0K        2
Activity Tracing                   256K      32K      32K       0K       0K      32K       0K        1
CG raster data                    99.1M    99.1M    99.1M       0K       0K       0K       0K        3
CoreAnimation                      112K      64K      64K       0K       0K      16K      48K        5
Foundation                          16K      16K      16K       0K       0K       0K       0K        1
Kernel Alloc Once                   32K      16K      16K       0K       0K       0K       0K        1
```

in this the "CG raster data" takes 99.1M.

While in Kingfisher:

```
                                VIRTUAL RESIDENT    DIRTY  SWAPPED VOLATILE   NONVOL    EMPTY   REGION
REGION TYPE                        SIZE     SIZE     SIZE     SIZE     SIZE     SIZE     SIZE    COUNT (non-coalesced)
===========                     ======= ========    =====  ======= ========   ======    =====  =======
Accelerate framework               256K     256K     256K       0K       0K     256K       0K        2
Activity Tracing                   256K      32K      32K       0K       0K      32K       0K        1
CoreAnimation                     99.6M    99.6M    99.6M       0K      48K      16K       0K        8
Foundation                          16K      16K      16K       0K       0K       0K       0K        1
```

It is the `CoreAnimation` takes 99.6M.

The Xcode memory debug panel is a recent thing and it obviously not counting the CG raster data memory (indeed it is an old way to load and decode image), which is actually also taken by the app. However, Kingfisher is using a moderner way (the image renderer) so its memory is recorded.

I guess profile your sample with Instrument and you will get the same result for both.

**Comment by onevcat** [comment]
BTW, you can check some WWDC sessions to know more detail about memory issue tracking. Just for you as a reference:

https://developer.apple.com/videos/play/wwdc2018/416/
https://developer.apple.com/videos/play/wwdc2021/10180
