### ISSUE TITLE
能否把SwiftUI相关的拆分出来，选择性pod

### ISSUE THREAD

**Issue by lczalh** [onevcat/Kingfisher#1841]
我只需要swift的，SwiftUI相关的暂时用不上。

**Comment by onevcat** [comment]
Sorry but I am too lazy to maintain two parts at the same time. 😂 (Since it should not have much impact to your final product: if you are not using those SwiftUI related symbols, they will be stripped out when doing static linking).

And for building Kingfisher v6 under Xcode 13, please refer to the link above as a temporary workaround.
