### ISSUE TITLE
Images will not load until the cell scroll out of the visible rect and back if enable Downsampling

### ISSUE THREAD

**Issue by Shinolr** [onevcat/Kingfisher#1870]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [ ] I want to report a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

#### What

My app's images are not in the main tableView data source, image is fetched with dataSource[indexPath.row].imageID in a standalone request and then merge back to dataSource[indexPath.row].imagePath.
```swift
// load image and merge into dataSource: ViewModel.swift
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    var model = models[indexPath.row]
    ImageLoader.remoteImage(with: model.imageID) {
        model.imagePath = $0
	self.models[indexPath.row] = model
	self.delegate?.viewModel(self, didUpdate: self.models, at: indexPath)
    }
}

// reload tableView: ViewController.swift
func viewModel(_: ViewModel, didUpdate models: [Model], at indexPath: IndexPath) {
      tableView.reloadRows(at: [indexPath], with: .automatic)
}

// configure cell: Cell.swift
func configure(with model: Model) {
    guard let url = URL(string: model.imagePath) else { return }
    cell.posterImageView.kf.setImage(
      with: url,
      placeholder: placeholder,
      options: [
        // images in the current visible rect of screen not load
        .processor(DownsamplingImageProcessor(size: cell.posterImageView.bounds.size)),
        .scaleFactor(UIScreen.main.scale),
        .cacheOriginalImage,
      ]
    )
}
```
I'd like to use `.processor(DownsamplingImageProcessor(size: cell.posterImageView.bounds.size))` to reduce the memory consuming, but the images of the current visible rect in the screen will not load until scroll the tableView and scroll back.

If I comment this line, the images of the current screen will load without any scroll.
#### Other Comment

Am I using the downsampling in a correct way like sample code above? Is there any way to use downsampling without have to scroll to load images?

**Comment by onevcat** [comment]
I guess you are using the `DownsamplingImageProcessor` correctly. But where are you calling the `configure(with model: Model)` method? 

You are reloading the cells in `didUpdate`, then it triggers another `tableView(_ tableView:cellForRowAt:) -> UITableViewCell`, but I didn't see an invocation of `configure(with:)` so I guess the Kingfisher methods are not yet called. Maybe try to print something to make sure it is called.

**Comment by Shinolr** [comment]
Sorry for the late reply, forgot add the invocation line `configure(with model: Model)` to the sample code. It's in the `cellForRowAt` function. I'm sure the Kingfisher methods are called already.

I found that this issue only occurs when `DownsamplingImageProcessor` and `reloadRows(at:with:)` being used mean time. If I replace `reloadRows(at:with:)` with `reloadData()`, the problem is gone, no need to scroll out of visible rect and scroll back to load images. Also, If I use `reloadRows(at:with:)` and comment the `DownSamplingImageProcessor` line, also behaves as expected.

I guess there is some mechanism beneath the `DownsamplingImageProcessor` that cannot work together with `reloadRows(at:with:)`.

| Downsampling | reloadData() | reloadRows(at:with:) | behaviour |
| ----------- | ----------- | ----------- | ----------- |
| ☑️ | ☑️ |  | ✅ |
| ☑️ |  | ☑️ | ❎ |
|  | ☑️ |  | ✅ |
|  |  | ☑️ | ✅ |

some information may help.
1. load main dataSource: `models` includes title, imageID and etc.
2. reload tableView: display information without images
3. load image:  load image url with `models[indexPath.row].imageID`
4. reload tableView: `reloadRows(at:with:)`

```swift
// load image and merge into dataSource: ViewModel.swift
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    var model = models[indexPath.row]
    configure(with: model)
    ImageLoader.remoteImage(with: model.imageID) {
        model.imagePath = $0
	self.models[indexPath.row] = model
	self.delegate?.viewModel(self, didUpdate: self.models, at: indexPath)
    }
}

// reload tableView: ViewController.swift
func viewModel(_: ViewModel, didUpdate models: [Model], at indexPath: IndexPath) {
      tableView.reloadRows(at: [indexPath], with: .automatic)
}

// configure cell: Cell.swift
func configure(with model: Model) {
    guard let url = URL(string: model.imagePath) else { return }
    cell.posterImageView.kf.setImage(
      with: url,
      placeholder: placeholder,
      options: [
        // images in the current visible rect of screen not load
        .processor(DownsamplingImageProcessor(size: cell.posterImageView.bounds.size)),
        .scaleFactor(UIScreen.main.scale),
        .cacheOriginalImage,
      ]
    )
}
```

**Comment by onevcat** [comment]
Thanks for the information.

I am trying to build a reproducible sample in [this branch](https://github.com/onevcat/Kingfisher/tree/fix/attempt-1870) with change in the demo app [like this](https://github.com/onevcat/Kingfisher/commit/a8315fc16a339c0a0c1e7abc9c3e5f91dee2321a). It should be identical to what you are doing, but instead of a `UITableView`, in a `UICollectionView`. Unfortunately I cannot reproduce this issue there. (You can find the same sample by checking out the `fix/attempt-1870` and run the demo app there. There is a "High Resolution" button which navigates to the changes above.)

I will continue to try a bit to see if I can create a table view and reproduce this issue. However, I doubt that because the behind mechanism of partial reloading should be the same for collection view too.

Is it possible for you to create a minimal sample app in which I can reproduce this problem stably? You can use urls like `https://raw.githubusercontent.com/onevcat/Kingfisher-TestImages/master/DemoAppImage/HighResolution/1.jpg` if you cannot find good ones. And also, maybe it would be helpful if you try to add a completion handler to your `kf.setImage` method and inspect the setting result. Maybe there are any errors?

**Comment by Shinolr** [comment]
Thanks for your help. I also cannot reproduce the issue in your `fix/attempt-1870`. So I folk the branch and did some further dig. Looks like the issue only occurs when layout collectionView/tableView by code and use a dynamic downsampling size.

I print the size of the `cell.cellImageView.bouns.size` two times. One before `kf.setImage` and the other one in the completion handler of the function. The latter get the correct size whereas the former did not. That `reloadRows(at:with:)/reloadItems(at:)` can't get the correct size in some time point in the `cellForRow/cellForItem` which confused me.

I committed a PR that included the reproduce code to `fix/attempt-1870`, please use the 'Basic' button to that vc.

I think you could know what make this happen. Thank you again!

**Comment by onevcat** [comment]
@Shinolr 

Thanks for the demo.

OK! So the problem is you are asking Kingfisher to downsample it to zero size, which does not make sense for the processor. A possible solution is calling `layoutIfNeeded()` on the cell before you use its `bounds`. It is a very common trick to ask iOS to perform layout. For example, the `Cell.init)` would be a good place for it.

![截屏2021-11-26 20 57 06](https://user-images.githubusercontent.com/1019875/143577454-dcf9e068-c675-40b7-aaee-f5697686bd59.png)

**Comment by Shinolr** [comment]
Really helps, saving my day, thanks very much.
