### ISSUE TITLE
Failed to get the image?

### ISSUE THREAD

**Issue by fstrub** [onevcat/Kingfisher#188]
Hello!
I'm confused when i use this url.
"http://img0.imgtn.bdimg.com/it/u=1633104621,3019537675&fm=21&gp=0.jpg"

Did i miss something?

![image](https://cloud.githubusercontent.com/assets/5120848/12076152/6d971a9a-b1da-11e5-8542-3984e7548031.png)
![image](https://cloud.githubusercontent.com/assets/5120848/12076155/7d44d748-b1da-11e5-8c0f-01196fe9a4d4.png)
![image](https://cloud.githubusercontent.com/assets/5120848/12076205/d11162f0-b1db-11e5-9cd7-4ee07b8ab793.png)

**Comment by onevcat** [comment]
You response is a 403 Forbidden, which means the request itself is valid but some restriction is applied and the server refused to response it.  It is usually due to your server is doing some validation on the request and it thinks that the request does not have permission for it.

You may need to investigate what is the restriction. I guess the server might be doing validating on some header field like user agent. If so, you can use the `requestModifier` of `ImageDownloader` to modify your request to match the server exception as a workaround.

**Comment by fstrub** [comment]
Thanks! That works for me.
