### ISSUE TITLE
ImageCache.default image retrieving strange behavior

### ISSUE THREAD

**Issue by jewelboi14** [onevcat/Kingfisher#1936]
### Check List

- [x] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [x] I want to report a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

### Issue Description

Hey guys! Just mentioned the some strange behavior of ImageCache image retrieving

#### What

I wanted to optimize image loading and get rid of cache errors, caching image by its url in the ImageCache from list, to retrieve the same image (using url as a cache key) in details screen. I don't really know, is it designed to be this way, but i think, solution like that is pretty appropriate. What i mentioned was a bug when image cache retrieving wrong image by right key
 
#### Reproduce

Basically, i've printed out in debug console, which key was in the moment when image loaded, but it was exact the same url as the url from list, only image was wrong

My code was: 

**when we caching every image in the list in the image cache using its url as a key:**

```swift
promoImageView.kf.setImage(with: viewModel.imageUrl, options: [.forceRefresh, .targetCache(imageCache)]) { [weak self] _ in
            if let image = self?.promoImageView.image {
                if let urlString = viewModel.imageUrl?.absoluteString {
                    imageCache.store(image, forKey: urlString)
                }
            }
        }
```

**when we retrieving image in the details screen by key using the same image cache**

```swift

viewModel.imageUrl.bind(onNext: { [weak self] url in
            guard let url = url else {
                self?.promoImageView.isHidden
                return
            }
            let imageCache = ImageCache.default
            imageCache.retrieveImage(forKey: url.absoluteString) { result in
                switch result {
                case .success(let imageResult):
                    self?.promoImageView.image = imageResult.image
                default: break
                }
                
            }
        }).disposed(by: disposeBag)

```
#### Other Comment

Also mentioned that this is happening not quite often and more like when user re-installs the app

**Comment by onevcat** [comment]
Not sure why you need this. Kingfisher will do the cache and retrieving automatically for you by default, as long as you use the image extension methods (ones under `.kf`), there is nothing you need to do.

In your case, I suggest you check if the correct image is cached in your list side. There is no guarantee that the `self?.promoImageView.image` would be always the one just downloaded, especially if there is a reuse for the cells. Any previous calls of `setImage` from the same cell will be overridden with a later call, and its callback handler will be invoked with an error. If you insist your way to do the cache/retrieve again yourself (which should not be what you need to do), please use the image in the result parameter of the callback instead of your image view's image:

```swift
promoImageView.kf.setImage(with: viewModel.imageUrl, options: [.forceRefresh, .targetCache(imageCache)]) { 
  [weak self] result in
  // Check `result` and use it instead.
}
```
