### ISSUE TITLE
Does Kingfisher supports animationImages property in UIImageView?

### ISSUE THREAD

**Issue by shahdhiren** [onevcat/Kingfisher#203]
I have looked into the UIImageView extension of Kingfisher (UIImageView+Kingfisher.swift). Didn't found the animationImages property support in it.

I tried to find alternatives with Kingfisher but didn't find much proper ways. Can any one suggest a proper async loading of sequence of images in UIImageView property?

**Comment by onevcat** [comment]
Currently Kingfisher does not support to set a sequence of images once. However, if your image is a GIF animated one, you can just load it with Kingfisher's API and it is supported out of box.

And you can always use the downloader separately to download all of your necessary images and then create and set the `animationImages` manually yourself currently. If it is necessary, you can also use the `ImageCache` to store them somewhere for quicker access later.

**Comment by shahdhiren** [comment]
Thanks for prompt reply. 

Can we have include this as new feature request for the same? For now, I will try to use the alternate solution. But certainly I would try to modify Kingfisher to have this feature. And if successful then I will contribute here...

**Comment by onevcat** [comment]
Sure. It would be cool if we have an API for the key frame images like `animationImages`. However, there are two concerns about it now.

1. We are using `UIImage.animatedImageNamed:duration:` to keep the API the same for animating GIF, which is working perfectly now. It just setup a single image and set it to the `UIImageView.image` property. If we introduce another way for animation images, but with a different property of `animationImages`, it might be a bit confusing. So we may need to consider the API very carefully when implementing this. I guess a new extension on setting `animationImages` from an array of images would promise. If you decide to begin this work, please let us talk and decide what the API for it should look like.
2. I am working on Kingfisher version 2 currently, which contains quite some changes including OS X support and better options. Since it will be merged into master later, there should be no need to do the work again for your modification. I suggest if you decide to contribute, you could make d2076776801773c0811387f2e81fc692d040e057 as a start point, which you could find in the `feature/NSImage-support` branch now.

**Comment by shahdhiren** [comment]
Sure, I will try to incorporate point 1. For now, I don't think I can immediately start working on this, but after 1 month due to other immediate tasks. I will talk to you before I will start working on this.

**Comment by onevcat** [comment]
That's cool. :)
