### ISSUE TITLE
Kingfisher is not compiling for visionOS

### ISSUE THREAD

**Issue by siimon** [onevcat/Kingfisher#2101]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [x] I want to report a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

### Issue Description

We are not running the latest version of Kingfisher so there could be more things, but in our current build there are 2 compile errors when targeting visionOS.

#### What

* ` UIActivityIndicatorView.Style.gray` is missing in the `ActivityIndicator`
* `UIScreen` is unavailable in visionOS

#### Reproduce

Download latest XCode 15 beta and add native visionOS as targeted platform, and you get compile errors.

**Comment by onevcat** [comment]
Basic visionOS support will be added soon.

**Comment by onevcat** [comment]
Basic visionOS support was added in [feature/visionOS](https://github.com/onevcat/Kingfisher/tree/feature/visionOS) branch. If you are using SPM, then it should be already possible to point to that branch and give it a try. Other dependency manager support is not yet done and I have to focus on some other stuffs for now.

The Xcode 15 related changes will be eventually merged to the `xcode-15` branch, with more other feature updating (including the privacy manifest). However, since it adds a build target, the project might become fragile. I will find a good time to merge the changes to master and create a release when prepared, but do not expect it happens too soon.

**Comment by siimon** [comment]
Thanks for a quick and fast reply 😍
