### ISSUE TITLE
dyld[769]: Library not loaded: @rpath/lib/libswiftCoreGraphics.dylib

### ISSUE THREAD

**Issue by zt-zhang** [onevcat/Kingfisher#2257]
Xcode Version 16.0 beta (16A5171c)

**Comment by onevcat** [comment]
![截屏2024-06-11 20 30 25](https://github.com/onevcat/Kingfisher/assets/1019875/c5e15f4b-11de-4534-88f0-64eefe99aa8f)

Since the sample app runs well on the iOS 18 simulator under Xcode 16.0 beta 1, I guess this is more likely an environment thing and/or an iOS beta issue (if you are running under an iOS 18 device).

I am closing this for now since there is not likely anything Kingfisher should do in this phase yet.
