### ISSUE TITLE
Add loading image indicator while downloading image

### ISSUE THREAD

**Issue by michaelbina** [onevcat/Kingfisher#230]
I'm currently using the LoadingImageView library (https://github.com/ggamecrazy/LoadingImageView) to display a loading indicator in place of the image while its downloading.  I see that there is an option to get the progress of the download so technically I could probably build this pretty easily on my end, but I think this would be a great feature to build directly into the library itself.  Let me know your thoughts.

**Comment by onevcat** [comment]
Hi, @michaelbina 

Thanks for this. Kingfisher itself is a library, it is generally not a good idea for an image download/caching library to have another UI library as a dependency. As you said, Kingfisher supplies a progress callback so you could implement this quite easily yourself. However, built-in support for `LoadingImageView` or any other UI libraries will not be introduced into Kingfisher.

And in case you missed it, I want to mention if you only need a loading indicator instead of a percentage indicator, you could just set `kf_showIndicatorWhenLoading` property of your `UIImageView` to `true` to enable a default system indicator.

Best regards & good luck.
