### ISSUE TITLE
Attach archived framework to releases

### ISSUE THREAD

**Issue by kylejm** [onevcat/Kingfisher#251]
To speed up CI builds, please could you attached a framework archive to the GitHub release tag?

It's easy to make one using Carthage:

```
$ cd path/to/project/root
$ carthage build --no-skip-current
$ carthage archive Kingfisher
```

Then add the Kingfisher.framework.zip (saved in the project root) to the release tag. Speeds up CI builds a ton when projects have several dependancies.

**Comment by onevcat** [comment]
Thanks for it. 

However, Swift ABI is not stable yet, and every new build of Swift (Xcode) would break the earlier built framework, even when the syntax keeps the same. You cannot use the old one once you upgrade your Xcode. Since that, there is high risk that the build breaks when different versions of Xcode are used (it always happens when Xcode upgrade, because some developers would like to insist on the older version, but some would upgrade to latest.) Only one framework file could be supplied in release for Carthage to download, but there might be different Swift versions.

So, a better way now, at least for framework creators, is only supplying the source code and let the users to build it with their own Swift version. It is also a high voted feature for carthage to build some specified frameworks only. Now it is quite slow and painful to use Carthage, I believe they should do something to improve it.

Anyway, thanks for your suggestion on it. I will add the pre-built framework **after** Swift ABI reaches stable. But until then, there is no plan to contain a framework zip in release. I hope you could understand that.

**Comment by kylejm** [comment]
Thank you for the details response, that's a really good reply. I respect your decision, it's very well thought out.

In regards to your comments on Carthage being able to build specified frameworks, do you mean being able to specify a platform? So for example saying you want an iOS version of the framework as apposed to Mac? If so, you can do this. Or are you meaning to specifying something else?

**Comment by onevcat** [comment]
No, I mean building only one framework out of many. The most wanted now would be something like this, for example:

```bash
carthage update --framework Kingfisher
```

So when you adding a framework in your Cartfile, you could leave others untouched and just build the newly added one.

Another lack feature of Carthage now is that it could not skip the already built framework, even the environment is all the same. That is also the main reason why Carthage is so slow. It will always try to build it from scratch, instead of checking and using the built ones.

So instead of the framework developers to add framework zip file every time when releasing a version, it would be great help if Carthage could implement these lacked feature. So ALL the frameworks could benefit from the speed boosting.

**Comment by kylejm** [comment]
Yeah I agree with all of these points.

I kinda feel like Carthage is been a bit slower since Justin Spahr-Summers went to Facebook. 

Perhaps it will slow in momentum more as SPM gets closer to being integrated with Xcode.
