### ISSUE TITLE
Memory cache expiration period not synced with disk expiration

### ISSUE THREAD

**Issue by borut-t** [onevcat/Kingfisher#264]
I am using maxCachePeriodInSecond property to define for how long images are stored on disk.
But how can I force that expiration on memory cache?

For an example:
1) maxCachePeriodInSecond is set to 1 week
2) image is downloaded and stored on disk
3) after one week image should not be fetched from disk
4) user did not kill an app and has resumed it a few hours after disk cache expired

Result: Image is still fechted from memory cache however disk cache expired.

Is there a way to force memory cache expiration to be tied with disk cache expiration period?

**Comment by onevcat** [comment]
Hi.

There is no time period limitation for memory cache. Different from disk cache, the memory cache is not persisted, so there is no need to set something like "expired date" for it, IMO.

Kingfisher will handle the memory cache automatically, in most cases you could leave the work to Kingfisher. However, if you need to clear the memory cache, you could use the `clearMemoryCache` method in `ImageCache` to force empty the memory cache.

**Comment by borut-t** [comment]
@onevcat What about for an example when disk cache expired but images are still in the memory? I will always get old images until memory is purged. But that can last hours or even days. 
There should be a mechanism that if you defined cache expiration in general than cache on all levels should expire.

**Comment by onevcat** [comment]
Hi, @borut-t 

It makes sense and might be a better approach to invalidate the corresponding memory cache too. I will do it later.

The purpose of expiration date of disk cache is limiting the disk size used. It should not be used for invalidating and updating an image since there is no guarantee to clear disk cache in an accurate time (the disk cache cleaning will only happen when the app being about to be switched to background or you call the cleaning methods explicitly). 

So if you want to updating an image after some time interval accurately, a better way would be use a URL with some time stamp appended. Kingfisher will recognize it as a new image, then download/cache it.

**Comment by onevcat** [comment]
After some consideration recently, I believe it is not a good idea to remove the memory cache when expired disk cache gets cleaned.

If we only change current implementation, we will suffer from a separation of API's name and its behavior, which is not acceptable. So I decide to leave it to a later major update and then I will reconsider about this.

Currently, you may observe the `KingfisherDidCleanDiskCacheNotification` and clear the memory cache, if the disk expiration is really critical for you. As mentioned above, the design purpose of disk cache is just a soft limitation of disk size, instead of accurate validation.
