### ISSUE TITLE
Decompress asset image in background thread

### ISSUE THREAD

**Issue by borut-t** [onevcat/Kingfisher#273]
Is there a way to use backgroundDecode for assets images?

**Comment by onevcat** [comment]
Does the `BackgroundDecode` option work for you?

**Comment by borut-t** [comment]
@onevcat It does for fetched images. But have no idea how to load images from asset catalogues?

**Comment by borut-t** [comment]
I've implemented custom background decode without Kingfisher. Code bellow can run on background thread.

```
UIGraphicsBeginImageContextWithOptions(image.size, true, 1)
image.drawAtPoint(CGPoint.zero, blendMode: CGBlendMode.Copy, alpha: 1)
let decompressedImage = UIGraphicsGetImageFromCurrentImageContext()
UIGraphicsEndImageContext()
```

**Comment by mmonroe86** [comment]
@onevcat I am unable to decompress gzipped files post download, with the .backgroundDecode option set. Is this the correct option to use in this instance?

**Comment by onevcat** [comment]
@mmonroe86 It is not what `backgroundDecode` does. It refers to decode the image from a certain data format (JEPG or PNG) to a raw pixel representation for faster rendering. But it does NOT mean to unzip your data from a format (like ZIP or GZIP) to a plain uncompressed format.

It is not recommended to gzip a binary (like an image) when sending the response to the client since they are already in compressed format. If you choose to compress it again with gzip, maybe you need to implement your own `ImageProcessor` to decompress it first before it can be sent to Kingfisher's built-in image processor. 

You can find some guide on `ImageProcessor` in [this wiki page](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#processor).
