### ISSUE TITLE
How can i check image already in cache 

### ISSUE THREAD

**Issue by mitesh21** [onevcat/Kingfisher#277]
Hello,

How can i check image already in cache or not. if image already exist in cache memory than it's good for use that. Like sdwebimage already provide same functionality.

Hope question valid and suppose to get answer as well.

**Comment by onevcat** [comment]
There is no need for that. Kingfisher will check both memory and disk cache for a URL, and if it is there, the cached image will be used instead of downloading again. So probably the thing you want is already implemented in Kingfisher.

However, in case you really need it, you can use the `isImageCachedForKey:` method in `ImageCache`.

And I just want to mention that it is not a good idea to ask question in GitHub issue. If you find any problem and/or have a feature request, issue would be a good place. But for a question like this, a proper place for this would be in Stackoverflow :)

Good luck!

**Comment by AhmadFayyas** [comment]
Referring to your answer, could you please advice about [this question](https://stackoverflow.com/questions/43049041/whats-the-kingfisher-default-cache-behavior)?

**Comment by onevcat** [comment]
@AhmadFayyas Answered it and hope it could help you!
