### ISSUE TITLE
Using  ' [unowned self] ' in the completionHandler results in a crash "attempted to retain deallocated object"

### ISSUE THREAD

**Issue by jasnig** [onevcat/Kingfisher#318]
Hello , I am really appreciate to your good job ! I was using the Kingfisher but I encounter an error when I was using  ' [unowned self] ' in the completionHandler which results in a crash "attempted to retain deallocated object" ( pop ). Then I found that the reason is that I used 'self' in the completionHandler, but the 'self' had already been released. So I looked up your source code, I found this `            completionHandler: {[weak self] image, error, cacheType, imageURL in
                
                dispatch_async_safely_to_main_queue {
                    guard let sSelf = self where imageURL == sSelf.kf_webURL else {
                    // self had already been released but the [unowned self] in the completionHandler leading the error
                        completionHandler?(image: image, error: error, cacheType: cacheType, imageURL: imageURL)
                        return
                    }

then I use [weak self] to solve my problem  but can I just only use [weak self] in the completionHandler but not [unowned self] ?    Thanks for your answer!

**Comment by onevcat** [comment]
Hi,

I suggest to always use weak instead of unowned if you are not sure about the reference relationship, especially when doing some async networking request. I believe it should be totally OK to use weak in your `completionHandler`, the only side effect is that your `self` will be released a bit later when the image request finished.

However, for this particular case, I guess it could be an improvement for Kingfisher. If the weak self does not exist any more, it should not call the completion handler since the owner of image view was already released and it does not care about it anymore.

I will make a patch for it soon.

**Comment by jasnig** [comment]
Thanks a lot! I am agree to your suggestion that 'always use weak instead of unowned if you are not sure about the reference relationship, especially when doing some async networking request ' . It's a safer way! Thanks again! have a good day.

**Comment by onevcat** [comment]
Fixed in #319
