### ISSUE TITLE
pre-completion block feature idea?

### ISSUE THREAD

**Issue by shams-ahmed** [onevcat/Kingfisher#326]
Current implementation only has completion block once the image has been applied, what do you reckon of execution another block just before applying a image.

one use-case i have is changing the ```contentMode``` before i set the new image. with the current methods it's not possible.

Another possible solution could be to use ```KingfisherOptionsInfoItem``` with set contentMode?

What your thoughts? am happy to start a PR with this feature...

**Comment by onevcat** [comment]
As #320 
Feature in plan.

**Comment by onevcat** [comment]
Implemented in Kingfisher 3. Check [`ImageProcessor`](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#processor) for more.

**Comment by lucasecf** [comment]
Hi @onevcat @shams-ahmed , I came across this issue because I want to implement the same user case as first mentioned in the description.

Checking the suggestion, I understand that the ImageProcessor's `process` method is invoked before the image is set, but changing the contentMode is an operation in the imageView, not in the image itself. Is there any cleaner way to achieve this result? Only thing I came across so far is creating this custom processor: 

```
struct TestProcessor: ImageProcessor {
        let imageView: UIImageView

        var identifier: String {
            return "test.processor"
        }

        func process(item: ImageProcessItem, options: KingfisherOptionsInfo) -> Image? {
            imageView.contentMode = .scaleAspectFill
            return DefaultImageProcessor.default.process(item: item, options: options)
        }
    }
```

**Comment by onevcat** [comment]
@lucasecf Maybe it worth to check https://github.com/onevcat/Kingfisher/issues/810, although it is  not implemented yet.
