### ISSUE TITLE
Couldn't find platform family in Info.plist 

### ISSUE THREAD

**Issue by ArtisOracle** [onevcat/Kingfisher#329]
# Abstract
Whenever I try to submit to the App Store using Kingfisher lib, I receive the following error:

## Error message
When submitting our app using Xcode 7.3.1, I get the following message:

```
An error occurred during upload

Couldn't find platform family in Info.plist CFBundleSupportedPlatforms or Mach-O LC_VERSION_MIN for Kingfisher
```

I installed kingfisher using Carthage. I have not yet tried what the error has suggested, however this is probably something I should not have to do.

**Comment by ArtisOracle** [comment]
My cartfile has `github "onevcat/Kingfisher" ~> 2.4`

**Comment by onevcat** [comment]
Hi, @ArtisOracle 

May I know for which target you are developing for, iOS or OS X?

**Comment by ArtisOracle** [comment]
Yes, I am targeting iOS.

**Comment by onevcat** [comment]
Just did some search and [this post](http://stackoverflow.com/questions/34529583/couldnt-find-platform-family-in-info-plist-cfbundlesupportedplatforms-or-mach-o) suggests to check whether you are copying the dSYM into your app bundle.

Not quite sure what happened yet, since I myself submitted a version with Carthage installed Kingfisher recently without any problem.

Would you mind to check that post and make sure there is no dSYM file in wrong place?

**Comment by ArtisOracle** [comment]
Wow, that appears to have been the issue. I'm not sure how they got into the copy bundle resources. I guess just carelessly dragging in the Carthage folder into Xcode will do this...

Sorry to waste your time.

**Comment by onevcat** [comment]
:) Never mind. Could you close this issue now?

**Comment by Yamilquery** [comment]
Please help me. I have the same issue, but I'm using Nativescript. I get the following error:

Couldn't find platform family in Info.plist CFBundleSupportedPlatforms or Mach-O LC_VERSION_MIN for phantomjs
