### ISSUE TITLE
Swift 3 Support 

### ISSUE THREAD

**Issue by indrajitsinh** [onevcat/Kingfisher#343]
does Kingfisher support Swift 3 and new API changes in IOS SDK ?

**Comment by onevcat** [comment]
There is already a swift3 branch for it. However, it is just a auto migration and not following Swift 3 API guide at all.

Kingfisher will not support Swift 3 in such an early stage, since it is only the first preview. There could be quite a lot of additional changes in Swift 3 and now no one could use Swift 3 in their product.

Maybe we will work on it from next month.

**Comment by kvnbautista** [comment]
@indrajitsinh Swift 3.0
Refer to the adjustment changes here
https://github.com/ideago/MouQu

**Comment by onevcat** [comment]
Swift 3 support is in progress in #371

**Comment by Tulleb** [comment]
`swift3`branch needs a new update for the Xcode 8 Beta 6 compatibility.

**Comment by onevcat** [comment]
Swift 3 supported from Kingfisher 3, and in master branch now.
