### ISSUE TITLE
How can I get the current size of expired cache?

### ISSUE THREAD

**Issue by jasonji84** [onevcat/Kingfisher#355]
I want to show the expired cache size, but I haven't find some function supporting this. Who can show me the correct way to handle this? Thanks.

**Comment by onevcat** [comment]
Does [calculateDiskCacheSizeWithCompletionHandler](http://cocoadocs.org/docsets/Kingfisher/2.4.2/Classes/ImageCache.html#/s:FC10Kingfisher10ImageCache43calculateDiskCacheSizeWithCompletionHandlerFFT4sizeSu_T_T_) work for you?

**Comment by onevcat** [comment]
There is a [calculateDiskCacheSizeWithCompletionHandler](http://cocoadocs.org/docsets/Kingfisher/2.4.2/Classes/ImageCache.html#/s:FC10Kingfisher10ImageCache43calculateDiskCacheSizeWithCompletionHandlerFFT4sizeSu_T_T_) method to show you the size of the whole disk cache. But now there is no method or property exposed for the expired cache size. The cache system is more likely a black box and generally speaking you could use it without worrying this. It is really a rare need to show the expired cache size (since they will be cleaned out from disk when the user switch you app to background).
