### ISSUE TITLE
Proper collection view Image cell load

### ISSUE THREAD

**Issue by kwstasna** [onevcat/Kingfisher#400]
Hello.
Although you have been answering to all the questions except mine (lol) I would like some help by implementing your library to this tutorial

http://sweettutos.com/2015/12/31/swift-how-to-asynchronously-download-and-cache-images-without-relying-on-third-party-libraries/

Because this tutorial's cache is being deleted as soon as the app is closed.
So with your library and some lines of code you could make a simple tutorial of how to keep images in disk and not to force reload when the collection view / table view is scrolling.

Could you help me along with this please?
Thanks a lot!

**Comment by onevcat** [comment]
Hi, sorry for not noticing your question. LOL. I am always getting a bit busy so sometimes I could forget to answer a question. Could you give me a link so that I could have a look.

I had a brief look at the tutorial, it seems in that tutorial only an `NSCache` is used for caching. `NSCache` is a memory cache, and it will be lost when you quit your app. If you use Kingfisher, there is no need to worry about this problem, since Kingfisher already has a disk cache layer built-in. Generally speaking you could just use the image extension method to set the image and you've done. As mentioned in the read me file:

```swift
imageView.kf_setImageWithURL(NSURL(string: "http://your_image_url.png")!, placeholderImage: placeholderImage)
```

**Comment by kwstasna** [comment]
The problem by using this for a cell is that it makes slow the scroll of the collection view....
If i run "Instruments" i can see that rendering of the image takes a lot of time (AppleJPEG), and also it takes some time to show the image from the disk cache.
https://github.com/onevcat/Kingfisher/issues/389

Then i tried 'BackgroundDecode' inside Options. It solved the problem of rendering the images but still if an iPhone is old and has lots of memory used, when it tries to scroll up and down it still takes some time 0.9ms to load the image from Memory Cache this time (cause of background decode i guess).

I really don't know what to do about it.

**Comment by onevcat** [comment]
What's the size of your image?

**Comment by kwstasna** [comment]
it varies from 40kb to 4-5mb (the images above 4mb are just for testing period.. although it has to work smoothly for those too)

**Comment by onevcat** [comment]
You cannot expect to load an image of several mega bytes so fast unless you do some preloading it to memory. The disk speed of iPhone is at 200MB/s so it will take almost 25ms to load a single 5MB image from disk to memory, it will take more time to decode and render it (which means you cannot scroll at 60 fps and suffer from a frame dropping).

For your 0.9 ms loading from memory cache, there is no problem, since you will have 16.7ms per frame to keep your UI at 60FPS. So it is a tradeoff between loading time and memory usage. You could get faster loading time if the images are already in memory (you could use `ImagePrefetcher` to load them from disk before you need to display them).

So, I believe you should make your image size smaller. Since you are showing it in a collection view, they should not be so large.

**Comment by kwstasna** [comment]
Yes you are right. Thought that we had more memory available but it's ok. I will make a column for thumbnail that will have the minimum size so it can load faster.
Thanks for the advice!
