### ISSUE TITLE
Allow set custom activity indicator

### ISSUE THREAD

**Issue by dluksza** [onevcat/Kingfisher#407]
Currently there is no way to set custom activity indicator. This way we are limited to only standard ios/osx indicators.

It would be nice if one can set any subclass of UIActivityIndicatorView as kf_indicator.

**Comment by onevcat** [comment]
Hi, @dluksza 

Thanks for the suggestion.

Instead of exposing it, I prefer that the framework users could add what they need to the image view themselves. You can easily add your customized indicator view (even not a `UIActivityIndicatorView` subclass) to your image view and then control its appearance and animation all as you like. There is also a progress block and a completion block of the image extension method, to notify the image downloading/setting process, so there should be no problem to add a highly customized wrapper for it.

As a framework, Kingfisher will only supply a most common solution (with plain `UIActivityIndicatorView`) and keep its as simple as enough.
