### ISSUE TITLE
Image Prefetcher async-ness

### ISSUE THREAD

**Issue by morisk** [onevcat/Kingfisher#411]
Hi, 
Thank you for the awesome framework I'm using!

```Swift
    public func start()
    {
        // Since we want to handle the resources cancellation in main thread only.
        dispatch_async_safely_to_main_queue { () -> () in
        ....
    }
```
*imageprefetcher.swift:146*

Why Image prefetcher doing his job on main thread? 

>Since we want to handle the resources cancellation in main thread only.

But how do I prevent hooking UI?
Probably I also don't care from what thread i will cancel the queues. 

Maybe more general question is - why everything is in main queue?

**Comment by onevcat** [comment]
All image resources management will happen in main thread, since under hood Kingfisher is using something like mutable array to manage it, which is not thread safe in Cocoa. Think that you are adding a new task while some code is trying to cancel one, if we do not specify a serial thread, there will be race condition. So here we need to dispatch to main thread.

As a framework user of Kingfisher, you could always start/cancel your task in any thread. It will not block the UI since all time-consuming parts (like downloading and caching) are happened in other threads. So it is not "everything" in main queue, but just that race-condition things.

**Comment by hifall** [comment]
Just curious -- can you dispatch to a serial thread other than the main thread?

**Comment by onevcat** [comment]
Sure, you could. But I guess it will be a premature optimization. Or even worse. Since thread dispatching itself is not free after all.

**Comment by morisk** [comment]
Hi onevcat,
Thank you for the thorough answers(just saw it). I think maybe we can make better, 
I patched Kingfisher version to behave on background thread. Since I don't need safety it was easy and I have much improved results.

 I'll make PR with proper thread handling and i will be glad if you could take a look.

**Comment by hifall** [comment]
@onevcat, thanks for your kind reply.

But that doesn't answer my question. Since you call dispatch_async_safely_to_main_queue to dispatch to the main queue, it incurs costs as well, just like dispatching to a background thread (I assume).

Since ImagePrefetcher has an optional completionHandler, a time-consuming completion handler passed in by the caller can still block the main UI, right?

**Comment by morisk** [comment]
@hifall you right and this is what I moved away from main thread.

**Comment by onevcat** [comment]
@hifall Hi,

`dispatch_async_safely_to_main_queue` will not do any dispatch if invoked from main thread. So there is no overhead if the users start a prefetch from main thread (which will always happen for most of framework users).

Since the prefetcher is using `ImageDownloader` internally to download images, so all time consuming things are already in background. If you add another serial queue for the callbacks, there could be quite some additional dispatch things happening.

The `start` method is fairly simple, I don't believe it could cause performance issues, unless you set the `maxConcurrentDownloads` to a huge number as well as you have a very large `prefetchResources`.

For the time-consuming completion handler passed in, it is not a framework problem but a users one. So it should be another story.

**Comment by hifall** [comment]
I see. Thanks!

**Comment by morisk** [comment]
At first I tried to direct all Kingfisher extra -"controlling" operations to background thread away from main. 

The reason for that is maybe my edge case: I am running TableView and I am forward caching n images. My original code using Kingfisher framework was:
````swift
let prefetcher = ImagePrefetcher(urls: productsPrefetching)
prefetcher.start()
````
And I had noticeable  performance issues when scrolling. So I went back to simpler code, only storing into Kingfisher cache and doing my own fetching:

````swift
            dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0)) {
....
				let manager = KingfisherManager.sharedManager
				for imageUrl in imageUrlArray {
					if manager.cache.cachedImageExistsforURL(imageUrl) == false {
						NSURLSession.sharedSession().dataTaskWithURL(imageUrl, completionHandler: { (data, response, error) in
							if let data = data where manager.cache.cachedImageExistsforURL(imageUrl) == false {
								if let image = UIImage(data: data), let absoluteUrl = imageUrl.absoluteString {
									manager.cache.storeImage(image, forKey: absoluteUrl)
								}
							}
						}).resume()
					}
				}
          }
````
While NSCache is thread safe NSFileManager is not and it seems handled well in `storeImage(_:)`.
