### ISSUE TITLE
When used with Siesta, class name "Resource" is a conflict

### ISSUE THREAD

**Issue by deanq** [onevcat/Kingfisher#419]
"Resource" is too generic that this was bound to happen.

**Comment by onevcat** [comment]
Did you try something like `Kingfisher.Resource`?

**Comment by onevcat** [comment]
Since we should be able to solve it by adding module name (and it is more about the Swift design pattern), so I am closing it.

**Comment by wxxsw** [comment]
I have a protocol called Resource. When I try to use Kingfisher.Resource, the compiler tells me:
`Type 'Kingfisher<_>' has no member 'Resource'`

**Comment by onevcat** [comment]
Ummm, I guess it is this https://forums.developer.apple.com/thread/47421 and https://bugs.swift.org/browse/SR-898

Swift compiler is trying to find the Kingfisher class instead of as the framework namespace.

If only a statement like "import Kingfisher as kf" would solve it though, it does not exist in Swift yet. So I guess the only fix would be renaming current `Kingfisher` class to another name, with breaking the API in this version. (I guess we would do it later in Kingfisher 5.x, with Swift 5.0).

Currently, if you are using your `Resource` protocol in your app bundle, I suggest to rename it temporarily. If the `Resource` protocol is from another module beside of your main app, you could create a separated file in which only Kingfisher imported, and do a `typealias` to Kingfisher's `Resource` there.

**Comment by wxxsw** [comment]
Thank you very much for your super quick reply, my `Resource` protocol is in the `Utils` module. Now I'm dealing with this `Kingfisher.Resource` extension in a separate file in the main module, and waiting for Apple to fix this problem.

**Comment by onevcat** [comment]
In Kingfisher 5.0, the duplicated name `Kingfisher` (as the module name) and `Kingfisher` (as the compatible protocol name) is refactored. So this issue should be solved.
