### ISSUE TITLE
文件写入成功回调

### ISSUE THREAD

**Issue by eilianlove** [onevcat/Kingfisher#424]
let URL = NSURL(string: "https://raw.githubusercontent.com/onevcat/Kingfisher/master/images/kingfisher-1.jpg")!
       KingfisherManager.sharedManager.retrieveImageWithURL(URL, optionsInfo: nil, progressBlock: { (receivedSize, totalSize) in
            print(receivedSize,  totalSize)
        }) { (image, error, cacheType, imageURL) in
            print("success")
        }

猫神，我想在下载完成之后并且获取本地化的回调，但是我看源码中NSFileManager的回调直接传入的nil，这里有什么办法能够让我获取到这个存储完图片之后的回调吗？
因为我要获取当前图片的字节来判断是否支持查看原图模式，谢谢

**Comment by onevcat** [comment]
`KingfisherManager` or the extension methods on `UIImageView` encapsulate most details of downloading and caching an image. So, instead of using the highly wrapped types, you may need to use the downloader and cache separately for your purpose. You can get the original data in [this callback](https://github.com/onevcat/Kingfisher/blob/master/Sources/ImageDownloader.swift#L37) by using [the download API](https://github.com/onevcat/Kingfisher/blob/master/Sources/ImageDownloader.swift#L257) in `ImageDownloader`.

**Comment by eilianlove** [comment]
对的，我也知道可以单独用ImageDownloader来获取下载成功的回调， 但是其他的逻辑比如缓存，存入本地，这些都是和你写的`retrieveImageWithURL`这里面就一模一样了。那就意味着我只能重新将缓存以及下载还有存沙盒都重新自己在方法中实现吗？

**Comment by onevcat** [comment]
That's right.

Another possible workaround would to be using the `ImageDownloaderDelegate`, in which there is [a delegate method](https://github.com/onevcat/Kingfisher/blob/master/Sources/ImageDownloader.swift#L104) to inform you about the downloading response. From there you might be able to build a list your own to hold the information you need. So you could keep using the `KingfisherManager` or extension methods.

**Comment by eilianlove** [comment]
OK, Thank you very much！
So would you tell me the reason why completionHandler doesn't provide original data or file path?

**Comment by onevcat** [comment]
Most of users do not care about it, for them, it is just noise and implementation detail. So by hiding it could make the APIs of framework easier to use and understand.
