### ISSUE TITLE
Building xCode 8 Swift 3.0

### ISSUE THREAD

**Issue by iLucas97** [onevcat/Kingfisher#443]
When i build xCode returns swift syntax errors (48 syntax error)  inside the library. Any idea??
I thought of downloading different versions, but cocoapods takes directly 3.0.1 (compatible with swift 3. right?)
(https://cloud.githubusercontent.com/assets/5815778/18615460/0b8ca000-7da8-11e6-9ae9-e3dc44426bf5.png)
This is my pod. 
> pod 'Kingfisher', :git => 'https://github.com/onevcat/Kingfisher',  :branch => 'master'

**Comment by wangghon** [comment]
I have the same issue as iLucas97 mentioned above

**Comment by thieu75** [comment]
I also have the same problem. 
CocoaPods install 2.x when using Pod 'Kingfisher'.

Pod 'Kingfisher', '~> 3.0' generate an error during pod install

So I also use
`pod 'Kingfisher', :git => 'https://github.com/onevcat/Kingfisher', :branch => 'master'`

104 issues for me. 👍  !!
Thanks,
Matthieu

**Comment by Sundin** [comment]
`pod 'Kingfisher', :git => 'https://github.com/onevcat/Kingfisher.git', :tag => '3.0.0`
solved the issue for me.

**Comment by onevcat** [comment]
@Sundin Thanks for the solution. 

@thieu75 @iLucas97 I believe it should be a CocoaPods issue when using branch to build instead of tag. Maybe it misses some config when using a branch.

Besides of that, I suggest always to use a tag (released version) in your Podfile and/or Cartfile. Although it should work, there is no guarantee that the master branch would always work. Since it is a dev branch, it might break from time to time, so it is not a wise decision to depend on that branch.

Just use this should works fine:

```
pod 'Kingfisher', '~> 3.0'
```

**Comment by onevcat** [comment]
It turned out to be an error in Kingfisher master branch, which causes it could not pass the cocoapods lint. Maybe we should add cocoapods lint to daily CI instead of only doing it when releasing. I will improve the CI integration later. https://github.com/onevcat/Kingfisher/issues/449

The master branch should also work now. But as the same, I suggest to use a released version instead of a branch, to get benefit from semantic version and better compatibility.

**Comment by jaimeagudo** [comment]
It still happens today
