### ISSUE TITLE
Unauthorized status code using SSL connection

### ISSUE THREAD

**Issue by gregorpichler** [onevcat/Kingfisher#452]
Hi,

first of all I really love this library. However I'm facing some troubles trying to load images with an HTTPS connection with a self signed certificate.

My current setup looks like this

```
let configuration = URLSessionConfiguration.default
configuration.httpAdditionalHeaders = [
      "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=1.0" : "Accept",
      "Bearer \(tokens.accessToken) " : "Authorization"
]

let imgManager = ImageDownloader.default
imgManager.sessionConfiguration = configuration
imgManager.trustedHosts = Set(["staging.mywebsite.com", "api.mywebsite.com"])
        
KingfisherManager.shared.downloader = imgManager
```

However `setImage`always returns with a 401 status code.

**Comment by phimage** [comment]
Maybe you swap key and value
```swift
configuration.httpAdditionalHeaders = [
     "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=1.0" ,
     "Authorization":  "Bearer \(tokens.accessToken)"
]
```

**Comment by gregorpichler** [comment]
Hi @phimage, thanks for your very good hint! Unfortunately I'm still having the same authorization problem

**Comment by onevcat** [comment]
@gregorpichler Can you access your resource with a plain `URLSession` task?

Kingfisher is using a very simple `URLSession` way to download image data, so if you can download the images by a session you create yourself, it should also work in Kingfisher.

And instead of modifying the session configuration, would you like to try to use the `requestModifier` to add the header? It is a suggested way to do such things like header modification. You can find some sample [here](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#modify-a-request-before-sending).

**Comment by gregorpichler** [comment]
@onevcat thanks for your answer. I've changed my code from modifying the session configuration to `requestModifier`. 

I think the problem is that I need to tell `URLSession` that it should trust my self-signed certificate, I somehow thought that the option `trustedHosts = Set(["testing.mywebsite.com", "api.mywebsite.com"])` will solve the problem. Am I doing something wrong with this setting?

**Comment by onevcat** [comment]
@gregorpichler If your server return you a 401, it means your authorization information is not correct. IMO, that is not the self-signed certification issue here (I am not sure though).

So, you could first try whether you could access your image data by creating your own `URLSession` and with the token you are using. If the server turns to 200, there must be something wrong in Kingfisher's downloader. Otherwise, it might just because your bearer token is not correct or there is something wrong with your server.

The `trustedHosts` property should already handled the self-signed certificate for you. Or for a more advanced usage, you could set the [`authenticationChallengeResponder`](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#authentication-with-nsurlcredential) of downloader and supply your own implementation for the challenge (in this case, `trustedHosts` will be just ignored)

**Comment by gregorpichler** [comment]
@onevcat I'm not sure if it works with `URLSesssion` due to the self-signed certificate. What I can confirm is, that it works with Postman if I turn off SSL certificate verification and use the same bearer token that I'm using in the app.

**Comment by onevcat** [comment]
Is it a POST request or a GET one? By default Kingfisher will use GET method. If your server expects a POST request, you also need to change it in modifier.

**Comment by gregorpichler** [comment]
Yeah just double checked it, it's a GET.

**Comment by onevcat** [comment]
Ummm.

I turn back to suggest you to try to implement a demo of getting the data with `URLSession` first. Once you can get the image by an `URLSession`, we could get to know where the problem exactly happens and give it a fix.

You could ignore the self-signed certification check by setting the session delegate and supply a proper method for challenge (see [this](http://stackoverflow.com/questions/19507207/how-do-i-accept-a-self-signed-ssl-certificate-using-ios-7s-nsurlsession-and-its) for more, the same approach is now used in Kingfisher if you set the `trustedHosts`). 

However, as I mentioned before, it's more likely a token problem instead of certification one, since you already received a 401 from server instead of a certification `NSURLError` (NSURLErrorDomain Code=-1202). If the issue happens with the certification, you should not have a chance to get a server response at all.

**Comment by gregorpichler** [comment]
Hmmm I doubt that it has something to do with a token issue, as I'm performing a couple of other requests to the server that are working. For other network requests I'm using Moya, where I set the following manager

`    class func trustCaCert() -> Manager {
        
        let policies: [String: ServerTrustPolicy] = [
            "testing.mywebsite.com": .pinCertificates(
                certificates: ServerTrustPolicy.certificates(in: Bundle(for: self)),
                validateCertificateChain: true,
                validateHost: true
            ),
            "api.mywebsite.com": .pinCertificates(
                certificates: ServerTrustPolicy.certificates(in: Bundle(for: self)),
                validateCertificateChain: true,
                validateHost: true
            )
        ]
        
        let manager = Manager(
            configuration: URLSessionConfiguration.default,
            serverTrustPolicyManager: ServerTrustPolicyManager(policies: policies)
        )
        
        return manager
    }`

Is there some similar option in Kingfisher?

**Comment by onevcat** [comment]
Nope. Kingfisher is not a networking request framework at last. It only supplied simple server trust certification. If you need to use a certification in the app bundle, you may need to implement the [`authenticationChallengeResponder`](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#authentication-with-nsurlcredential) and create it from your bundle cert with `SecCertificateCreateWithData` yourself. :(

**Comment by onevcat** [comment]
@gregorpichler Hi, any news for this?

**Comment by gregorpichler** [comment]
@onevcat Unfortunately I'm not having any success on this. I've replaced my self signed certificate with a SSL certificate from a trusted CA and now I can access the image resource with Postman.

However Kingfisher still returns an unauthorized error code. I'm using the code below and if I'm using the `accessToken` in Postman everything works fine (so it can't be a token issue).

```
let modifier = AnyModifier { request in
            var r = request
            r.setValue("text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=1.0", forHTTPHeaderField: "Accept")
            r.setValue("Bearer \(accessToken)", forHTTPHeaderField: "Authorization")
            
            return r
        }
        
        let url = URL(string: "https://www.mywebsite.com")
        self.kf.setImage(with: url, placeholder: placeholder, options: [.requestModifier(modifier)], progressBlock: nil) { (image, error, cacheType, url) in
            if let img = image {
                self.image = img
            } else {
                self.image = placeholder
            }
            
            completion?(image, error, cacheType, url)
        }
```

**Comment by gregorpichler** [comment]
UPDATE

I've now replaced `requestModifier` by the following code and now it works.

let configuration = URLSessionConfiguration.default
configuration.httpAdditionalHeaders = [
     "Authorization" : "Bearer \(user.userData.tokenAuthentication!.accessToken!)"
]
        
let imgManager = ImageDownloader.default
imgManager.sessionConfiguration = configuration

**Comment by onevcat** [comment]
So it means the issue comes from the "Accept" field in the header? Your server does not expect an accept field but you were sending one? 

Would you mind to confirm it so we could decide whether we need to dig it deeper to see where the issue lives indeed.

Thanks! :)

**Comment by gregorpichler** [comment]
Oh my god, I think I've found the issue (not sure if it would also solve the initial issue with a self signed certificate), the accessToken I've set as value was interpreted as `Optional("...")` by Swift so I had to force unwrap it. Now it's working fine :)

Many thanks for your patience and keep up the good work

**Comment by geraldeersteling** [comment]
Sorry to open up this issue again, but I'm having similar issues.

I keep getting a `401` even though I verified that manually downloading  the binary data (with a `URLSession` and data task) works, I get a `200` and the bytes I expect.

I'm not sure why the downloader fails, I double checked that the session token I send is attached through the `.requestModifier` and I send the correct credentials in the authentication challenge.

I've implemented the ImageDownloader's delegate methods and keep seeing: 

`Optional(Error Domain=com.onevcat.Kingfisher.Error Code=10002 "unauthorized" UserInfo={NSLocalizedDescription=unauthorized, statusCode=401})`

even though I logged the request just before sending: 

request: `Optional(https://{PATH_TO_IMG_BINARY})`
headers: `Optional(["{A_SESSION_TOKEN}": "Session-Token", "image/png": "Content-Type"])`

> `PATH_TO_IMG_BINARY` and `A_SESSION_TOKEN` above both contain valid values. When I use a REST client (PAW) and execute the same request I get the correct image back

I've made an convenience extension on `UIImageView`:

``` swift

func imageFromEndpoint(_ url: URL, request: URLRequest) { 
        kf.cancelDownloadTask()

        let modifier = AnyModifier {
                var modified = $0
                modified.httpMethod = request.httpMethod
                let _ = request.allHTTPHeaderFields?.compactMap {
                        modified.setValue($0.key, forHTTPHeaderField: $0.value)
                }
                return modified
        }
        kf.setImage(with: ImageResource(downloadURL: url),
                             options: [.requestModifier(modifier)])
}
```

Am I doing something wrong here?

**Comment by onevcat** [comment]
It is not correct here: `modified.setValue($0.key, forHTTPHeaderField: $0.value)`

I believe which should be `modified.setValue($0.value, forHTTPHeaderField: $0.key)` instead.

**Comment by geraldeersteling** [comment]
Woops, sorry forgot to update my comment. I already figured my own noobish mistake...sigh sorry for wasting your time, but thanks for responding!
