### ISSUE TITLE
RoundCornerImageProcessor white background color in the corner

### ISSUE THREAD

**Issue by xspyhack** [onevcat/Kingfisher#458]
I am sure that the white color is not imageView's background color.

And this bug just be catch in sometimes event if the same image.

![img_1189](https://cloud.githubusercontent.com/assets/5518285/18873889/16f7bf26-84f4-11e6-8a69-62a17e0c2f6c.PNG)

**Comment by xspyhack** [comment]
It seems that this issue just happen when the image had be cached in the disk.

**Comment by onevcat** [comment]
By default, Kingfisher will follow your image format when caching (serializing) your image. If you are using a JPEG, the transparency of round corner will be lost when saving as a JPEG, which leads the bg color to be the default white.

A possible solution would be supplying PNG images instead of JPEG, or creating a `CacheSerializer` which always convert an image object to png data by using `PNGRepresentation` methods.

**Comment by xspyhack** [comment]
It works well with `CacheSerializer`, thanks for your help! 💐
