### ISSUE TITLE
I few questions to get started

### ISSUE THREAD

**Issue by LarsWith** [onevcat/Kingfisher#473]
Thanks for sharing this!

1. I wonder if I have to clear cache manually? - Coz I've seen tickets here with people saying that their app crached when scrolling to fast 

2. Should I set a max disk cache size in viewdidload Eg: `ImageCache.default.maxDiskCacheSize = 50 * 1024 * 1024` or it it safe to go with the default value?

**Comment by onevcat** [comment]
1. We are using Kingfisher heavily in a commercial app ourselves. We didn't encounter a memory issue for now, so it should not be a problem and we didn't do any cleaning cache things manually. If you are trying to load a lot of images in a table/collection view, you may want to load the thumbnail version of it, instead of the original one. And you can cancel the task when the cell disappeared to reduce pressure.
2. It depends to you. We choose unlimited disk size in our project and it works well. Since there is a two weeks expiration time by default, it usually not a big problem with the cache size. But if you really need one, just go ahead and set it.

**Comment by LarsWith** [comment]
@onevcat thanks!
Right now I am using it like this in my tableview:
`myImage.kf.setImage(with: thumbUrl, placeholder: placeImg, options: [.transition(.fade(0.2))])`
- It downloads a thumbnail like you said

And in `didEndDisplaying` I call `myImage.kf.cancelDownloadTask()`

I have not seen any issues with memory/cache I just wanted to double check :)

Two questions:

How do I call `clearMemoryCache()` `clearDiskCache()`  the example file shows:

```
KingfisherManager.shared.cache.clearMemoryCache()
KingfisherManager.shared.cache.clearDiskCache()
```

whyle the Cheat-Sheet shows:

```
cache.clearMemoryCache()
cache.clearDiskCache()
```

I was thinking on calling them inside 

```
override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
}
```

And lastly I am thinking of setting maxDiskCacheSize in viewdidload but do you set durtion and size in the same function?
```

ImageCache.default.maxDiskCacheSize = 60 * 60 * 24 * 3
// Default value is 60 * 60 * 24 * 7, which means 1 week.
```

```
// 50 MB
ImageCache.default.maxDiskCacheSize = 50 * 1024 * 1024
// Default value is 0, which means no limit.
```

I got a bit confussed with with those examples.

Thanks in advance!

**Comment by onevcat** [comment]
For the clean/clear cache things, Kingfisher will do that in memory warning automatically, so you do not have to do it yourself (and twice). 

For the code in cheat sheet, it just demonstrates you could use these APIs, there is no relationship and no need to set them both. I am sorry for the confusion it caused.
