### ISSUE TITLE
A question about dispatch_sync

### ISSUE THREAD

**Issue by mrahmiao** [onevcat/Kingfisher#5]
In the initializer of `ImageCache`:

    dispatch_sync(ioQueue, { () -> Void in
        self.fileManager = NSFileManager()
    })

Why not use `self.fileManager = NSFileManager()` directly?

**Comment by onevcat** [comment]
While `NSFileManager.defaultManager()` is thread-safe, the file manager created by `NSFileManager()` is not. So there is a possibility of creating the file manager in a thread, but using it in another. An `ioQueue` could ensure all file IOs are in the same thread.

**Comment by mrahmiao** [comment]
Do you mean that `self.fileManager` may be used when initializing an instance of `ImageCache`?

**Comment by onevcat** [comment]
Hi, in fact here there should be no problem to just use `fileManager = NSFileManager()`, or even use a `defaultManager`. But if you want to add some delegate later, you will need a new created file manager and consider the thread problem.

Here I prefer a new file manager since Kingfisher is a framework and should be isolated in the io operations from the "host" app, which might be using the shared file manager.
