### ISSUE TITLE
duplicate photos when i use Kingfisher with TableView

### ISSUE THREAD

**Issue by chungkol** [onevcat/Kingfisher#513]
Hi,
I have 2 bug :
+ duplicate photos when i use Kingfisher with TableView
+ when i scroll image there also change until load data of table success

[
![image](https://cloud.githubusercontent.com/assets/14126029/20293379/6cda4b8e-ab28-11e6-9e6d-ae83d098b979.png)
](url)

**Comment by monica18p** [comment]
I am also facing similar issue.
I have a view where the images get loaded correctly.
Then when i go to another view which is not having any image(image url is not having any image) then, the previous' view's images are shown in this empty image view instead of placeholder image.

**This happens when i use [.forceRefresh] option. with no options this isn't happening.**

I think its something related to incorrect indexing while storing in disk/memory

**Comment by onevcat** [comment]
@chungkol I can not fully understand what's your situation. But in your code you were trying to set `.cacheMemoryOnly` when you using the downloader. It will take no effect since it is just related to the cache instead of downloader.

@monica18p Can you build a demo project for it? I am glad to dig into it.

**Comment by onevcat** [comment]
@chungkol I can not fully understand what's your situation. But in your code you were trying to set `.cacheMemoryOnly` when you using the downloader. It will take no effect since it is just related to the cache instead of downloader.

@monica18p Can you build a demo project for it? I am glad to dig into it.

**Comment by giannigdev** [comment]
Has this been resolved?

**Comment by onevcat** [comment]
@giannigdev I don't think it is an issue of Kingfisher and I never received any similar report from then on.

If you are facing the same problem or more information, please open a new issue.
