### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by Sol88** [onevcat/Kingfisher#520]
Hi! And thank you for your great library!

I have profiled your demo project for memory leaks and found out more than 90 leaks in demo project. Maybe something has changed in recent xcode updates (I am using xcode 8.1)? 

<img width="1266" alt="2016-11-20 18 02 36" src="https://cloud.githubusercontent.com/assets/5029909/20463820/cd6c92b8-af4c-11e6-8ebc-564eaab3b04e.png">

[Kingfisher.trace.zip](https://github.com/onevcat/Kingfisher/files/602098/Kingfisher.trace.zip)

**Comment by onevcat** [comment]
Hi,

Thanks for reporting this. I can verify the same in both iPhone simulators and devices with iOS 10. But if I switches to iOS 9, the leak checks are all green. So I believe it might be related to some iOS internal change.

It seems that most leaks are from creating a URL session and its configuration. All of them are UIKit code and not accessible in Kingfisher. I will take a deeper look to see what happened.

**Comment by onevcat** [comment]
Not sure whether it is related to this issue in Alamofire. Just for ref. https://github.com/Alamofire/Alamofire/issues/1717

**Comment by Sol88** [comment]
Thank you very much! I've also checked on iOS 9 and everything is ok.

**Comment by onevcat** [comment]
After some investigation, I discovered some interesting fast.

1. The leak will happen when you access the `ImageDownloader.default`, which will create one for you if there is no one. Leaks always happen just in the `ImageDownloader.init`, even you never do a network request. This code will simply cause it: `let _ = ImageDownloader.default`

2. The `var fetchLoads = [URL: ImageFetchLoad]()` will cause the `_NativeDictionaryStorageOwner` and `_NativeDictionaryStorageImp` leaks, which are the same case in Alamofire issue above. As said by @cnoon, we have to wait for Apple to fix it.

3. When I comment out the line `open var requestsUsePipeling = false`, more than half of the leaks disappeared.

Before:
![snip20161121_3](https://cloud.githubusercontent.com/assets/1019875/20473062/6878e0d6-b001-11e6-95ca-f5c66a42c8aa.png)

After:
![snip20161121_2](https://cloud.githubusercontent.com/assets/1019875/20473066/6ea54148-b001-11e6-80dc-d134643118e2.png)

The `requestsUsePipeling` is nothing more than a Bool flag. However, quite some of the url session leaks get fixed by removing a Bool property. This does not make sense to me at all.

4. I continued and get a minimal case for the leak. Consider to store a `URLSessionConfiguration` in an `NSObject`:

```swift
class ViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        let _ = Downloader.default
    }
}

class Downloader: NSObject {
    var sessionConfiguration = URLSessionConfiguration.ephemeral
    static let `default` = Downloader()
}
```

Yes, it is all the code. And try it in a new iOS project and profile it. Guess the result?

![snip20161121_5](https://cloud.githubusercontent.com/assets/1019875/20473571/f10e537e-b004-11e6-87b0-cd01d2841676.png)

It's still "leaking"!

Everything goes fine if I remove the `Downloader`'s super class and make it a Swift class. This code will not leak:

```swift
class Downloader: NSObject {
    var sessionConfiguration = URLSessionConfiguration.ephemeral
    static let `default` = Downloader()
}
```

### Conclusion

Do not trust Instrument with iOS 10. It cannot work well with Swift + Cocoa. If you need to check the memory issues, use the memory graph in Debug panel, or find an iOS 9 device.

I will fire a radar and hope Apple could fix it soon.

**Comment by Sol88** [comment]
Oh... I see. Thank you very much for such detail investigation! And one more time thanks for your lib!!!

**Comment by onevcat** [comment]
There is a workaround to drop `NSObject` superclass for `ImageDownloader` to make the Instrument happy. It would be merged later, since I think it is reasonable to drop OC support now.

**Comment by onevcat** [comment]
Updated:

The code above: 

```swift
class ViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        let _ = Downloader.default
    }
}

class Downloader: NSObject {
    var sessionConfiguration = URLSessionConfiguration.ephemeral
    static let `default` = Downloader()
}
```

is not leaking anymore in the latest iOS simulator (10.3) in Xcode 8.3.3.
