### ISSUE TITLE
内存暴增问题

### ISSUE THREAD

**Issue by zhnnnnn** [onevcat/Kingfisher#531]
喵神，我现在现在项目中是一个collectionview加载一些图片。用到了kingfisher的 setImage 方法。但是在滑动的时候内存暴增。用instrument看了下有50%指向kingfisher。然后我用了sdwebimage 替换了setimage方法，发现内存问题就消失了。不知是不是我使用方法的问题，最近才开始写swift项目。
xcode8.0 swift3.0 iOS10.0 kingfisher是3.1.1
![image](https://cloud.githubusercontent.com/assets/11436094/20836433/28933eda-b8da-11e6-9eee-c86f330acc3e.png)

**Comment by onevcat** [comment]
Kingfisher will cache all the downloaded images by default, so it is not surprising that it will take some memory even if you are not displaying the images, especially when you are displaying some large images. Generally, there is no worry about it, since Kingfisher will release these cached memory when a memory warning received.

If it is important to you, you could just set the `maxMemoryCost` property of `ImageCache.default` to customize it.

And since SDWebImage is an Objective-C project, sometimes the Instruments cannot track it properly. Instead of using Instruments, you could try the Debug panel in Xcode. As I know SDWebImage is also caching all images in memory, so both should share the same behavior on this.

**Comment by zhnnnnn** [comment]
谢喵神~

**Comment by abellee** [comment]
@onevcat so I also could clear memory cache by myself, right? 
but after do that, seems the disk cache was disappear too? so how to clear the memory cache in right way?

**Comment by onevcat** [comment]
@abellee 
No, purging the memory cache should not clear disk cache. If this happened to you, please open a new issue and give more details.

**Comment by abellee** [comment]
@onevcat sorry, I don't know if this is an issue. I just found the memory will increased almost 40mb after I opened a large image yesterday, so I tried to clear the memory cache with kingfisher, and it works. but when I offline for a while and reopen the app, some images can not display even though I have showed before. but it won't happened before I do clear the memory cache.
