### ISSUE TITLE
OverlayProcessor not working with custom UIColor

### ISSUE THREAD

**Issue by AndreMarvell** [onevcat/Kingfisher#533]
Hi guys,

It seems like OverlayImageProcessor doesnt work with custom color. This is my code 

```swift
let color = UIColor(red:0.34, green:0.34, blue:0.44, alpha:1.0) 
let processor = RoundCornerImageProcessor(cornerRadius: CGFloat(radius))
                       .append(another: OverlayImageProcessor(overlay: color, fraction: 0.7)
                        .append(another: ResizingImageProcessor(targetSize: CGSize(width: 3*self.width, height: 3*self.height))))
self.kf.setImage(with: URL(string: url)!, options: [.transition(.fade(0.2)), .processor(processor)])
```

But it works pefectly when using classic UIColor like .red etc...

Do you know what i am doing wrong?

Thank you for your help

**Comment by onevcat** [comment]
I just tried your color (which is likely a dimmed gray with a little blue), and it looks fine for me. It does work but maybe you need to decrease the `fraction` to make it more obvious.

And if what you want is a tint instead of color overlay, you could also try the `TintImageProcessor`. Or you could even implement your own filter effect very easily.

**Comment by AndreMarvell** [comment]
I tried with the TintImageProcessor and it did the job. 
Thank you for you help, you can close the ticket
