### ISSUE TITLE
Xcode lost connection to iPhone 5 when loading large images using kingfisher on iOS 9 and above.

### ISSUE THREAD

**Issue by bmughal** [onevcat/Kingfisher#539]
Using Kingfisher library when I try to download large images, Xcode says lost connection to iPhone5. Is there any way in kingfisher to to show image chunk by chunk. ? as loading a large image causes to much spike in memory.

**Comment by onevcat** [comment]
No, it is not supported in Kingfisher now.

**Comment by bmughal** [comment]
ok, is there any workaround to show big images using kingfisher?

**Comment by onevcat** [comment]
What the size of your image, and how can you show it without Kingfisher?

I am not sure what you want, but Kingfisher is made only as a shortcut to display normal images in an image view, instead of a specified domain (such as showing very large images). If you are using some other method to decode and show the image, maybe you could implement your own `ImageProcessor` to process the image data by chunk and then show it.

**Comment by bmughal** [comment]
Size of image vary from iPhone to iPhone, capturing images via phone camera then uploading to S3.

Aim is to download list of above type images in Scrollview using memory efficiently.

**Comment by onevcat** [comment]
So you mean a photo from camera? It should be no problem by using Kingfisher.

And the losing connect to your iPhone should have nothing to do with Kingfisher and the network, maybe it is something related to your device or cable?

**Comment by onevcat** [comment]
Unless you are trying to load multiple photos at the same time...

**Comment by bmughal** [comment]
Yes I am loading multiple photos at same time.

**Comment by bmughal** [comment]
Right now what I am doing is, loading list of views in paginated scrollview, and load the respective image of view when that specific view is in front, rest all view images gets cancel download request, 

Is that correct way sir. ?

**Comment by onevcat** [comment]
If you want to show a list of small images, instead of loading the original ones, I suggest you upload a smaller version of your photos and load them. Whenever you need to show an image as thumbnail, use the smaller version. It is never a good idea to use an extreme large and detailed photo as a thumbnail. 

A thumbnail is a thumbnail, while the large image should only be used in the detail view when user is interested in it.

Or you can try to resize it to a smaller version by using the `ResizingImageProcessor`. However, it could be a waste of network.

**Comment by onevcat** [comment]
Why do you use a scroll view? It would be better to use a collection view for that. So you could get benefit from cell reusing and only the image in cell being displayed will be loaded. It will be much easier compared to adopting to a plain scroll view and managing all states yourself.

**Comment by bmughal** [comment]
Actual the aim to to make horizontal media gallery using scrollview, where user can swipe left or right to view the next or previous media.

**Comment by onevcat** [comment]
So isn't it perfect to use a collection view with paginate enabled?

**Comment by bmughal** [comment]
Yes, I understand.

**Comment by bmughal** [comment]
I will try UIcollectionView horizontal scroll

**Comment by bmughal** [comment]
Thankyou for guidance.

**Comment by onevcat** [comment]
:) I will close this for now. If there is still an issue on memory, you could also try to set `ImageCache.default.maxMemoryCost` to a small value (like 1) to disable the memory cache.

**Comment by bmughal** [comment]
Sure, Thanx again.
