### ISSUE TITLE
Image size stored on cache is greater than the actual image size.

### ISSUE THREAD

**Issue by abhaverma** [onevcat/Kingfisher#552]
Upon debugging, I found that the method
**data(with image: Image, original: Data?) -> Data?**
inside DefaultCacheSerializer was returning data which is bigger in size than the _original_ data. This method internally is calling UIImageJPEGRepresentation(image, compressionQuality) or the equivalent class for png or gif types.

Trying a simple experiment on converting original data to image to data again like this:
UIImageJPEGRepresentation(UIImage(data: original!)!, 0)!.count
shows that size of data is increased. And it has got to do with the way image transformation from one to another format works. Here's a stackoverflow link explaining the same:
http://stackoverflow.com/questions/15054016/nsdata-length-of-an-image-compressed-with-uiimagejpegrepresentation

Possible solution:
1. We store the _original_ data directly instead of converting to image and then data. 
Problem with this approach: Post processing done by ImageProcessor would not get saved, and might have to be done every time in memory. 
Advantage of this approach: We save time of converting to UIImage and then serializing it to jpeg.

**Comment by onevcat** [comment]
Yes, you are right on the `ImageProcessor`. The main idea of storing the data converted from image instead of original data is for `ImageProcessor`. Kingfisher prefers to using more disk space instead of  applying the processor filter every time. CPU time and filter applying is much expensive and should be reduced as much as possible, compared to disk space. So, I guess the `DefaultCacheSerializer` now plays well in most situation.

However, since you could implement and specify a new serializer as you like, it could be a performance improvement to store the original data, as long as you are not using any special processor. It depends on your choice.
