### ISSUE TITLE
RoundCornerImageProcessor output image 

### ISSUE THREAD

**Issue by ro6lyo** [onevcat/Kingfisher#563]
Any idea why it keeps white background around the image?

![screen shot 2017-01-17 at 11 04 09 am](https://cloud.githubusercontent.com/assets/13335070/22014315/c8d122ce-dca5-11e6-9dc9-013168af3004.png)
![screen shot 2017-01-17 at 11 04 54 am](https://cloud.githubusercontent.com/assets/13335070/22014322/cf2a339a-dca5-11e6-8521-f97a30d29d0b.png)

**Comment by onevcat** [comment]
It seems that you are applying this processor to an image without alpha channel (for example, jpg files). When you caching that file to disk, Kingfisher will keep the format and use a nearest presenting way, which means stored as jpg.

You could implement a customized `CacheSerializer` to store the processed image as png to keep the alpha channel. Here is some code snippet for it:

```swift
struct PNGCacheSerializer: CacheSerializer {    
    public func data(with image: Image, original: Data?) -> Data? {
        return UIImagePNGRepresentation(image)
    }

    func image(with data: Data, options: KingfisherOptionsInfo?) -> Image? {
        return UIImage(data: data)
    }
}

let s = PNGCacheSerializer()
test.kf.setImage(with: url, options: [.processor(procesosor), .cacheSerializer(s)])
```

Or, just ask your server to give you PNG files instead of JPEGs.

**Comment by ro6lyo** [comment]
Right its JPEG. Thanks for help appreciated!
