### ISSUE TITLE
ImageCache.swift:479:62: error:

### ISSUE THREAD

**Issue by IAskWind** [onevcat/Kingfisher#572]
- ERROR | [iOS] xcodebuild:  Kingfisher/Sources/ImageCache.swift:479:62: error: result values in '? :' expression have mismatching types '_' and 'Date'

**Comment by onevcat** [comment]
It's a bug of Xcode 8. Please upgrade to Xcode 8.2, or you can just use an earlier version of Kingfisher (3.2.4) for a while until you upgrade your Xcode version.

**Comment by borut-t** [comment]
@onevcat You are right. This is solved in 8.2. But on older versions this causes an error. We are using CircleCI and they obviously have older version. Tests fails because of this issue.

You could make this right on older versions like this:
```swift
let expiredDate: Date? = (maxCachePeriodInSecond < 0) ? nil : Date(timeIntervalSinceNow: -maxCachePeriodInSecond)
```

That way property doesn't need to infer data type and will not cause error on older versions.

Could you make a fix asap?

**Comment by borut-t** [comment]
@onevcat CircleCI did upgrade to version 8.2 and there is no more problem.

**Comment by onevcat** [comment]
Indeed, I think we'd better modify it to support some (not so) early Xcode version. I will take look at it later. Thanks for the feedback!
