### ISSUE TITLE
cancelDownloadTasks() causes memory leak

### ISSUE THREAD

**Issue by jjjeeerrr111** [onevcat/Kingfisher#594]
I have a horizontal scrolling collection view that loads images from the network. I load the images using imageView.kf.setUrl(with: url) but if the user scrolls quickly through the collection view I dont want to waste the network calls so I call imageView.cancelDownloadTask() on collectionView:didEndDisplayingCell in my collectionViewDataSource method.

However when looking at the memory graph I can see that the cells are held in memory instead of being dequeued so I started looking into it. Here is a stack trace image of my collection view cell count reference with the cancelDownloadTask() still in my code:

<img width="260" alt="screen shot 2017-02-14 at 7 16 48 pm" src="https://cloud.githubusercontent.com/assets/7354919/22955620/0a035284-f2eb-11e6-9b88-4b80575a7e5e.png">

Here is the reference count when i remove the line from my code:

<img width="232" alt="screen shot 2017-02-14 at 7 18 44 pm" src="https://cloud.githubusercontent.com/assets/7354919/22955626/1602bf8e-f2eb-11e6-8664-4f59eeb9e7ad.png">

which is around the number that are in view at any given time

Not sure what the issue is but this was causing many OOM crashes for me.

**Comment by onevcat** [comment]
Hi, I cannot reproduce this in the demo project, everything goes well and no cell is retained. The demo project is also using a collection view and with cancelling of downloading in didEndDisplayingCell.

![snip20170215_1](https://cloud.githubusercontent.com/assets/1019875/22956288/70fa0bbc-f364-11e6-814a-636dc96e4538.png)

1. Are you using some `ImagePrefetcher` for these cells? By default the prefetcher would use the same default downloader and it can will hold the download progress.

2. Have you tried to upgrade Kingfisher to the latest version? We have a fix on the cancel behavior recently in version 3.4.0 (although I don't think it's related on this)

3. Try to test in iOS 9 or 10, since there is a queue memory bug for debug environment of iOS 8.

If none of them solve the problem, would you like to try to reproduce it in the demo project? (Remember to disable the prefetcher things)

Since I cannot see the issue, so it would be great if you could build a sample to reproduce it and I'd like to dig it to find what's going wrong.

**Comment by jjjeeerrr111** [comment]
ok ill look into it and build a sample. thanks

**Comment by jjjeeerrr111** [comment]
1. not using a prefetcher
2. im on the latest pod, i tried updating to fix this issue
3. I tried on both

Maybe its worth noting that by collection view is in a tableview cell.

**Comment by sham3k** [comment]
+1 
Same Problem.
Horizontally scrolling CollectionView in a TableView Cell.
Memory Usage jumps to 250MB from 10-20MB when scrolling this CollectionView.

**Comment by Sundin** [comment]
Hi @jjjeeerrr111 and @sham3k. I don't know if this helps you, but I faced a similar issue and in my case it was caused by a retain cycle in my completionHandler. So if you reference `self` inside the completionHandler, you need to make it a weak reference like this:

```
completionHandler: { [weak self] image, error, cacheType, imageURL in
    self?.doSomething()
}
```
