### ISSUE TITLE
Contentmode = .center ignored by AnimatedImageView?

### ISSUE THREAD

**Issue by rkittinger** [onevcat/Kingfisher#612]
this worked in version 3.1.1. Loaded animated GIFs into collection view cells. Now they all appear big and fill the entire cell, instead of keeping image size and centering in cell.

**Comment by rkittinger** [comment]
using option .preloadAllGIFData seems to help now

**Comment by onevcat** [comment]
Only `aspectFit` and `aspectFill` now is supported in a `AnimatedImageView`. All other cases will fall into the `scaleFill`. This is an aggressive optimization for large size gif, which will resize them to the image view size instead of wasting memory by a render scaling.

You can set `needsPrescaling` on `AnimatedImageView` to `false` to disable it, then Kingfisher will respect your content mode setting on the image view.

**Comment by rkittinger** [comment]
Thank you.
