### ISSUE TITLE
Crash at 'static Kingfisher<A where ...>.image(data : Data, scale : CGFloat, preloadAllGIFData : Bool, onlyFirstFrame : Bool) -> UIImage?'

### ISSUE THREAD

**Issue by genadyo** [onevcat/Kingfisher#621]
Here is the trace:
http://crashes.to/s/20f85252193

**Comment by onevcat** [comment]
This crash is deeply in the `NSAllocateMemoryPages` and I guess it is more or less related to a low level memory problem. Maybe it happens when the device has a low memory. In fact there is little we could do in Kingfisher for it. 

Maybe you could try to set a smaller memory cache value (or disable the memory cache) to get some trade off on memory usage.

**Comment by genadyo** [comment]
Thanks for the feedback, I'll test it!
