### ISSUE TITLE
ImageDownloader urlSession crash

### ISSUE THREAD

**Issue by jovan90jovanovic** [onevcat/Kingfisher#627]
Hi Everyone,

I'm getting this crash very often and I wasn't able to track it down. Basically, it happens in ImageDownloaderSessionHandler.urlSession(URLSession, dataTask : URLSessionDataTask, didReceive : Data) -> () at /Users/jovanjovanovic/Documents/Xcode/MoodChimp/Pods/Kingfisher/Sources/ImageDownloader.swift:402
and I've tried some logging but all I can see is that it gets EXC_BAD_ACCESS when it tries to use fetchLoad(for: URL) on ImageDownloader. Any ideas would be appreciated.
![screen shot 2017-03-21 at 10 57 25 am](https://cloud.githubusercontent.com/assets/6358616/24142105/d9925f2c-0e25-11e7-9914-5ba00653c269.png)

**Comment by onevcat** [comment]
Not sure what happened because this crash is deeply in Apple's codebase.

Maybe related to https://github.com/AFNetworking/AFNetworking/issues/2468

However, it seems that there is little we could do in Kingfisher.

P.S. Does this always happen in iOS 8 only? If so, I guess it might be an system issue which was already fixed recently.
