### ISSUE TITLE
Limit disk cache size

### ISSUE THREAD

**Issue by ecristerna** [onevcat/Kingfisher#629]
Hi,

I'm trying to limit the disk space used by the default cache, but I don't know where to set this property. I'm doing it on the AppDelegate, but this does not seem to work, the cache folder keeps saving images, even when the size has overpassed the limit i've set.

`Used disk size by bytes: 30076928 / 10485760`

I've set the limit to 10MB, but the cache is already ~30MB

**Comment by onevcat** [comment]
The disk cache size limit is a "soft" limit instead of a "hard" one. Calculate the whole cache size before determine whether to store it or not would be a performance cost behavior. Kingfisher will only check the disk size and remove some older caches which exceed size limit when you switch the app background.

**Comment by ecristerna** [comment]
Oh, i get it. So, id I set my cache limit to 10MB, and the `maxCachePeriod` to -1, this will cause to only delete files from disk once the 10MB capacity has been overpassed?

Also, is the AppDelegate the correct place to put this code?

**Comment by onevcat** [comment]
Yes, you are correct. The files will be checked and cleaned when user click Home button to switch your app background, or when you call the `cleanExpiredDiskCache` manually.

I guess it is a reasonable place to set it in AppDelegate.
