### ISSUE TITLE
Downloading large amount of images

### ISSUE THREAD

**Issue by alibasta** [onevcat/Kingfisher#634]
Hi,

I'm using Kingfisher to downloading a large amount of images and put them after download into the cache. My problem right now is, that the CPU usage is very high because of the large amount of images. 

I would love to change the `delegateQueue`to background but the URLSession is private in Kingfisher. Would love to manipulate the `delegateQueue` in Kingfisher. 

Are you open for a pull request?

Best

Alex

**Comment by onevcat** [comment]
@alibasta Yes, you are right. There should be no need to delegate the session to main queue. Maybe we could just pass `nil` when creating the session object and let the system creating one for us, according to [doc](https://developer.apple.com/reference/foundation/urlsession/1411597-init):

> If nil, the session creates a serial operation queue for performing all delegate method calls and completion handler calls.

What do you think about it? If you feel that this is OK, a p-r on it is warmly welcome!

**Comment by onevcat** [comment]
Instead of change the access level of url session or delegate queue, I prefer to keep a minimal interface to framework users unless it is really necessary. Hope you could understand it. (If you think it would be better to make the url session `open` or `public`, feel free to leave a comment and discuss more. :] )

**Comment by alibasta** [comment]
Hi @onevcat 
thanks for your fast response! I think the problem is somewhere else. 
My CPU usage is higher than 100% using the following code to download more than 1000 Images:

```
    func cacheImages(_ urls: [URL], completion: (() -> Void)? = nil) {
        var imagesProcessed = 0
        let downloader = ImageDownloader(name: "imageDownloaderJob")
        downloader.sessionConfiguration.httpMaximumConnectionsPerHost = 1
        urls.forEach({
            let cacheKey = $0.absoluteString
            let isImageCached = ImageCache.default.isImageCached(forKey: cacheKey).cached
            if !isImageCached {
                downloader.downloadImage(with: $0, options: [], progressBlock: nil) {
                    (image, error, url, data) in
                    if let image = image {
                        // cache image
                        ImageCache.default.store(image, forKey: cacheKey)
                    }
                }
            } else {
                imagesProcessed += 1
                if imagesProcessed == urls.count {
                    completion?()
                }
            }
        })
    }
```

Do you have experience using Kingfisher to download this large amount of urls?

Best

Alex

**Comment by onevcat** [comment]
Instead of downloading them like this, I suggest to use the `ImagePrefetcher` for this purpose, which is wrapped to a better API and limited the concurrent jobs at a time. You could just feed your urls to it and wait for the result:

```swift
ImagePrefetcher(urls: urls).start()
```

There are also progress and completion callbacks for you to know the result of downloading. Refer to the [wiki on it](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#prefetch) for more.

**Comment by onevcat** [comment]
And another delegate queue instead of main queue could definitely be an improve too!

**Comment by alibasta** [comment]
@onevcat Sorry for the late response. I was afk a few days. 

I changed the code to use the `ImagePrefetcher` and the performance looks better now.  I think the next step is to test Kingfisher with changing the queue in Kingfisher. Have you already done some tests?

**Comment by onevcat** [comment]
Maybe you could try this branch: https://github.com/onevcat/Kingfisher/tree/fix/non-main-queue-delegate

(Not merged into master yet)

**Comment by onevcat** [comment]
But I guess the improvement of it might be trivial. It would be appreciated if you could tell me about the result when you have any progress.

**Comment by alibasta** [comment]
CPU is still over 100%. I'm starting the `ImagePrefetcher` from a background DispatchQueue.

**Comment by alibasta** [comment]
RAM is also exploding. More than a gig. I'm downloading 10806 images right now in the ImagePrefetcher.

**Comment by onevcat** [comment]
Do you know what is the most CPU consuming method? Could you do a profiling in Instruments for that?

And since you are not likely to using them, I guess you could also disable the memory cache by setting `ImageCache.default.maxMemoryCost = 1` to limit the RAM.

After all, Kingfisher is not designed as a raw data downloader for huge amount of files (which I believe you are seeking for). Instead of just giving you the raw data (what is needed in your case), the default downloader of Kingfisher also creates and prepares the images to be displayed. It could be a waste. IMO, if you are in bottleneck on this, it would be better to use or implement a specified version of file downloader.
