### ISSUE TITLE
memory usage increased with update

### ISSUE THREAD

**Issue by viktorwillmann** [onevcat/Kingfisher#637]
i noticed that since i updated the kingfisher pod, using 
    cell.picture.kf.setImage(with: item.imageURL, placeholder: placeholderImage)
in my tableView at cellForRowAt causes an increased memory usage with each image. Before that the memory was freed when the cell disappeared. If i remove the line, everything works fine and this worked before perfectly fine. 

Did something changed regarding the usage? Might this be a bug with XCode 8.3?

**Comment by onevcat** [comment]
Hey, what was the version you were using before upgrade? Recently there should be no change on memory management in Kingfisher so I guess it would be some other reasons.

BTW, it is normal that the memory usage keeps going up when you show more images, since there is a memory layer of cache in Kingfisher which would hold your images in memory. The in-memory cache follows some rules so generally you should have no worry about it. When the size limitation hit or a memory warning received, Kingfisher will release the resources automatically. 

You could try to call [`ImageCache.defalt.clearMemoryCache()`](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#clear-cache-manually) to see whether the memory usage drops. Or you could set `maxMemoryCost` to a value (default is 0, means unlimited) to change this behavior. But as I mentioned before, it should not be necessary since Kingfisher would purge the cache itself.

**Comment by viktorwillmann** [comment]
You are right, the memory does drop if i simulate a warning or put in the background so i guess i have never noticed it before. Where do i set the maxMemoryCost? Will it work like FIFO, kicking out the oldest unrecently used image from cache? We can close this issue then.

**Comment by onevcat** [comment]
It is an `NSCache` underhood, so it will refuse new cache once upper limit is reached. You could set the `maxMemoryCost` at any place you want. A general place could be the app did finish launching delegate method in AppDelegate.
