### ISSUE TITLE
UIBarButtonItem extension

### ISSUE THREAD

**Issue by pepejeria** [onevcat/Kingfisher#640]
Is there an easy way to set the background image of an UIBarButtonItem? An extension for like the UIImageView would be nice.

**Comment by onevcat** [comment]
We have to be prudent to add such an extension method to the framework, unless it is a very widely-used feature. Now Kingfisher supplies an ImageView extension since almost all use cases is targeted to an ImageView. However, `UIBarButtonItem` should not be in this case.

Of course you could wrap an extension for your own project if you are using it for `UIBarButtonItem`. Thanks to the `KingfisherManager` it would not be hard. Basically, you just use the `retrieveImage` method in the `KingfisherManager` to get the images from cache or web, then set it in the completion handler. 

You could find reference on that in [this page](http://cocoadocs.org/docsets/Kingfisher/3.6.0/Classes/KingfisherManager.html#/s:FC10Kingfisher17KingfisherManager13retrieveImageFT4withPS_8Resource_7optionsGSqGSaOS_25KingfisherOptionsInfoItem__13progressBlockGSqFTVs5Int64S3__T__17completionHandlerGSqFTGSqCSo7UIImage_GSqCSo7NSError_OS_9CacheTypeGSqV10Foundation3URL__T___CS_17RetrieveImageTask).

**Comment by pepejeria** [comment]
Alright, sounds good.
