### ISSUE TITLE
A suggestion: Make DiskCacheSize as a property

### ISSUE THREAD

**Issue by jerry0317** [onevcat/Kingfisher#643]
Are there methods that I'd use the calculated size of DiskCacheSize as a property instead of closure?
At this point I can only
```swift
var cacheSize: Int{
	var rawSize = 0
	ImageCache.default.calculateDiskCacheSize { size in
		rawSize = Int(size)
	}
	return rawSize
}
```
which doesn't work.

It'd be helpful if I could just use the DiskCacheSize as a property. Just like SDWebImage, where I can:
```swift
var cacheSize: Int{
	return Int(SDImageCache.shared().getSize())
}
```
And really, thanks a lot for your work!

**Comment by onevcat** [comment]
Hi,

It is intended to have only async method for getting disk size. If there are quite a few (like thousands) files in the disk, getting the total size of them could be a time-consuming work and it might cause your UI freezing if not used properly. Making it an async method instead of a sync one could be a tip for users for that.

You code will fail since the return statement happens before the block has a chance to be invoked. If you need to get the size (and maybe display it in UI), you need:

ImageCache.default.calculateDiskCacheSize { size in
    print("size is \(size)");
    self.label.text = "Size \(size)" // The callback is already in main thread so you have no need to dispatch it again.
}

If this could not solve your problem, could you tell me why do you need a sync way to get the size?

**Comment by jerry0317** [comment]
Thanks! This solves my problem.
