### ISSUE TITLE
Crash when loading images too frequently

### ISSUE THREAD

**Issue by bmetitiri** [onevcat/Kingfisher#648]
I have a control that updates a preview image whenever it is manipulated. When an update occurs I call `imageView.kf.cancelDownloadTask()` to cancel the previous image download if it hadn't finished, then I call `imageView.kf.setImage(imageUrl)` to set the new preview image. If I manipulate my control too frequently for too long, I get this crash in NSURLConnectionLoader, specifically with CFURLRequestCopyContentDispositionEncodingFallbackArray: 

<img width="1280" alt="screen shot 2017-04-10 at 1 32 04 pm" src="https://cloud.githubusercontent.com/assets/14278459/24881863/023fbdf6-1df4-11e7-8959-41e08dc0153b.png">

I've been trying to debug this crash for days and I can't get Instruments to give me any more useful information. I'm not entirely sure this is a Kingfisher issue in particular, but I was hoping you might have some advice. I get the same crash loading images in a large collection view and scrolling too fast.

**Comment by onevcat** [comment]
Thanks for reporting this. However, there might be very little Kingfisher could do since the crash lays deeply in Apple's code.

Maybe we could dig it deeper by setting the NSZombieEnabled, MallocStackLogging and some sanitizers to get more detailed information.

BTW, does it still happen when you comment the `cancelDownloadTask()`? I guess we need to shrink the search area down first.

**Comment by bmetitiri** [comment]
Actually, it seems to be perfectly stable if I remove canceling entirely.

**Comment by onevcat** [comment]
Fine. At least we have some clue.

**Comment by Killectro** [comment]
Is there any update on this? I've also seen this issue in our production app.

**Comment by onevcat** [comment]
@Killectro Hi, no idea on this now. Could you find a stable way to reproduce it?
