### ISSUE TITLE
Prebuilt Binaries - Carthage 

### ISSUE THREAD

**Issue by jwelton** [onevcat/Kingfisher#655]
### Issue Description
Submit prebuilt binaries with releases to improve CI performance when using Carthage.

#### What
I think it would be really useful to include Carthage prebuilt binaries with releases. This means when using Carthage, the binary can be downloaded rather than needing to recompile the entire library. This enhancement would be much appreciated when running CI builds, as currently some of the largest time for a project can be taken with building dependencies.

**Comment by onevcat** [comment]
Hi, @jwelton 

Thank you for proposing it. However, it is intended to not include a binary version when releasing, at least until the ABI stability of Swift.

The reason is simple. Since you can only use a framework with the same version of your Swift, an earlier version will not be able to use when new Swift version released. That would mess things up if the user need to pin to a specified version of Kingfisher while they want to upgrade to new Swift. Also, any one still using an older Xcode/Swift could not be benefit from newer version of Kingfisher either. It also adds unnecessary complexity when using and maintaining the framework. Quite a few frameworks are uploading binaries in release, but the result and feedback is not so good as I know.

From Carthage 0.20, there is a `--cache-builds` flag to skip build when there is no change for the framework, which would boost the build process. Maybe you could keep your git repo and previous built artifacts for dependency, and use `--cache-builds` to make your build faster.
