### ISSUE TITLE
Error code == 10000

### ISSUE THREAD

**Issue by khuong291** [onevcat/Kingfisher#657]
I want to download this image from this url:

https://lh3.googleusercontent.com/CmBFji9kfApEsEsfGlVIr5FKcC6QbhvT9jBGNagSYOTQgzQrM8Ue5jiQYrsSjLTULA=w300-rw

But it gave me error code == 10000

**Comment by onevcat** [comment]
WebP is not supported in Kingfisher by default. You may implement your own processor and cache serializer to use WebP. See #54

**Comment by ShaharHD** [comment]
@khuong291 You might want to take a look at: [KingfisherWebP](https://github.com/Yeatse/KingfisherWebP)

I've got it updated with latest libwebp [0.6.0](https://cocoapods.org/pods/libwebp) and just submitted a PR to support animated webp (for now just the 1st frame).

@onevcat Are you willing to consider adding built-in support for webp? I think it might be beneficial to have it as a supported type as it is starting to get more popular.
I think I might be able to assist with that.

**Comment by onevcat** [comment]
Hi, @ShaharHD 

Thanks for considering it. However, we have no plan to add built-in support for WebP in Kingfisher currently. In fact it is still a not-so-widely used feature on iOS platform, Apple does not support it yet either. To support WebP, we have to introduce some dependency into Kingfisher, which is not a good idea for now. 

Since we have `ImageProcessor`, it should not be a hard thing for framework users to implement their own solution, or they could just use KingfisherWebP for a quick solution.

Once Apple supports WebP decoding and encoding in iOS, we could support it too quite easily.

**Comment by ShaharHD** [comment]
@onevcat created #663 to allow for more generic naming support via `ImageProcessor`
