### ISSUE TITLE
Server caching directive ignored? 

### ISSUE THREAD

**Issue by Pe-te** [onevcat/Kingfisher#67]
Hi, currently we can only change the maxCachePeriodInSecond inside our app.

It would be more comfortable to change it on the server and send an "Expires"-Header, but Kingfisher seems to ignore this header.

Are there plans to add this feature in the future?

**Comment by onevcat** [comment]
Hi, @Pe-te 
Kingfisher now follows only local rules on cache and will ignore the expire date in response header. 

Instead of a discrete file cache expiration duration control, Kingfisher prefers to manage it per cache now, that is the `maxCachePeriodInSecond` in the cache object. In my opinion, it is simpler to use and understand, compared to both of local cache expiration duration and the server instruction exist at the same time.

Moreover, there is rarely a chance that a resource expiration duration would change in my opinion. If you need different expiration duration for different types of resource (for example avatar may need a shorter cache duration, while static images could be cached for a longer time), you can setup multiple caches with different cache duration and send your images to the correct cache. You can have a look at #18 for more on it.

So, I am sorry but I guess there is little chance to add it into Kingfisher, since the core concept is client-managed cache here.

**Comment by Pe-te** [comment]
We can work around it then and send the current maxCachePeriodInSecond from the server. Just thought you might be working on the header thing. ;) Thanks for the information and for the great library!
