### ISSUE TITLE
Need option to disable cache on per image basis

### ISSUE THREAD

**Issue by r-a-o** [onevcat/Kingfisher#670]
Currently, I believe there is no option to disable cache of a particular image. This is useful when image is known to change and there is no need for caching such image.

Expect this as an option of `KingfisherOptionsInfo` that can be passed in the `setImage` call.

**Comment by onevcat** [comment]
I don't think it worth to add such an option, since Kingfisher's main purpose is Downloading & Caching images. That the image view extension doing is combining all these parts together. So I cannot see a good reason to have an option opposing against this.

For your case, you could just use the `ImageDownloader` method to download an image (see the [wiki](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#use-imagedownloader-to-download-an-image-without-caching)). It should also be very easy to write your own wrapper to set an image view without caching by using `ImageDownloader`.

**Comment by mxp7064** [comment]
It is definitely a good idea to have an option to disable cache for specific images which change frequently!

**Comment by onevcat** [comment]
@mxp7064 In Kingfisher 5, you can use this to prevent (or override the cache option with per image bias):

```swift
imageView.kf.setImage(
    with: url,
    options: [.memoryCacheExpiration(.expired), .diskCacheExpiration(.expired)]
)
```

**Comment by ufukkosker** [comment]
in SwiftUI:

KFImage.url(URL(string: url))
          .resizing(referenceSize: CGSize(width: 50, height: 50), mode: .aspectFit)
          .loadDiskFileSynchronously()
           .memoryCacheExpiration(.never)
           .fade(duration: 0.25)
