### ISSUE TITLE
Gif leaks memory

### ISSUE THREAD

**Issue by luannguyenkhoa** [onevcat/Kingfisher#675]
Thanks for great lib.

I was encountering a big problem when using AnimatedImageView that the memory increases like crazy. Because Github doesn't support video file, so please see the recorded video at this link:
https://www.dropbox.com/s/99i2hv888f8x9gk/Untitled.mov?dl=0
Noted that I'm using CollectionView for rendering list of gifs and a few texts. I have set `framePreloadCount = 1` in `func awakeFromNib`
Any recommendation to resolve this issue? I'm looking forward to seeing your reply.
Thanks and best regards.

**Comment by onevcat** [comment]
Your description is not enough for me to know what's going wrong. Could you tell me more about your situation? A demo project which could reproduce the issue and/or some steps which could reproduce it would be a great help.

**Comment by luannguyenkhoa** [comment]
Tks for your enthusiastic support.
[TempTestKingfisher.zip](https://github.com/onevcat/Kingfisher/files/999993/TempTestKingfisher.zip)
The attached file is my demo. Debug with Instrument you can see the memory goes up continuously as the video above.
Best.

**Comment by onevcat** [comment]
@luannguyenkhoa Just tried you demo and everything goes fine to me:

https://i.gyazo.com/63af8b7546eb71c6b99866ffd7ef394c.mp4

Is there any special steps to reproduce this? 
Or could it be a version specified issue? On which versions of Xcode or iOS devices you tried it?

**Comment by onevcat** [comment]
I guess you set the allocation life span to "All Allocations"? You may need to use "Created & Persiatent" to see the used memory. (And it is normal to keep going up in "All Allocations" when using `AnimatedImageView`, since it is DOES allocating all the time.)

![snip20170515_3](https://cloud.githubusercontent.com/assets/1019875/26045358/c9c2b738-3984-11e7-90d8-7d4b2b613542.png)

![snip20170515_4](https://cloud.githubusercontent.com/assets/1019875/26045360/cb16557c-3984-11e7-9835-f3352f905ec2.png)

**Comment by luannguyenkhoa** [comment]
Yah. You're right. I just tried "Created & Persiatent", everything goes fine.
Sorry for bothering. I'm gonna close this issue.

Best.
