### ISSUE TITLE
Low memory and crash when using background decode

### ISSUE THREAD

**Issue by ruipfcosta** [onevcat/Kingfisher#687]
I've been experiencing random crashes on my app due to low memory issues. I was able to track down the issue to the `.backgroundDecode` option when setting images through Kingfisher.
The code I'm using is pretty standard:

```swift
...

var optionsInfo: KingfisherOptionsInfo = [.transition(.fade(0.3)), .backgroundDecode, .downloader(ImageDownloader(name: downloaderName))]

if cacheResult.cacheType == .disk {
    optionsInfo.append(.forceTransition)
}
        
self.kf.setImage(with: resource, placeholder: .none, options: optionsInfo, progressBlock: .none, completionHandler: .none)
```

These are the results I obtained after opening a screen with ~10 images (JPG format with sizes between 100-300KB), with and without the background decode option set (the former one leading to a crash).

<img width="1280" alt="with background decode" src="https://cloud.githubusercontent.com/assets/1910006/26462471/d9fbf050-4178-11e7-9010-dd1f5896227c.png">
<img width="1276" alt="without background decode" src="https://cloud.githubusercontent.com/assets/1910006/26462470/d9fac98c-4178-11e7-84ed-788465a7a397.png">

**Comment by onevcat** [comment]
Hey, @ruipfcosta 

We didn't see difference in memory between a normal decoding and a background decoding in our sample project.

We didn't receive any reports on this before, so I am not sure what happened now. Is it possible for you to build a demo project which could reproduce this stably? I'd like to have a deep look at it if I could reproduce it.

Thanks!

**Comment by rlaguilar** [comment]
Hi @onevcat,
I've experienced this kind of random crashes (**without** using Kingfisher) when working with `UIGraphicsBeginImageContextWithOptions`. In my case I was using `UIGraphicsGetImageFromCurrentImageContext ` for retrieving the image, which retrieves an autoreleased image. This means that all the images you create during a single iteration of the Run Loop will be released *after* this iteration finishes, so if you are decoding too much images during the same iteration you can experiment memory issues. The solution that I found was to enclose my drawing code inside an `autoreleasepool` block, so the autorrelased images would be released just before my code returns. 
In your case you are using `CGContext.makeImage` for retrieving the image, so I don't know if in this case the returned image is an autorreleased object too, in which case the problem the problem here could be the same.
Regards

**Comment by qiusuo8** [comment]
Same situation. In iOS 10.3.3, easy to reproduce in my project.
![qq20170803-131243](https://user-images.githubusercontent.com/1579259/28906955-fa69ff88-784d-11e7-9e8a-7a6fe14f99c6.png)

**Comment by qiusuo8** [comment]
Sorry, it's my fault. The JPGs are too large.
