### ISSUE TITLE
Remote images with different URL but same file name renders the last downloaded image

### ISSUE THREAD

**Issue by c-sharma** [onevcat/Kingfisher#690]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [ ] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [ ] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did find a same one.
- [ ] I want to reoprt a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

### Issue Description

In case of multiple image load request in a UIImageView using Kingfisher library, remote images with different URL but same filename renders a single image instead of different images. Ideally, the different images shall render as such irrespective of file name.

#### Reproduce

Try setting two UIImageViews in UICollectionViewCell(s) with following URL patterns
URL1 - https://url_a/abc.png
URL2 - https://url_b/abc.png

**Comment by onevcat** [comment]
It should not happen if you are trying to set the image view with urls since Kingfisher will use the hashed value of `absoluteString` of `URL` as the [cache key](https://github.com/onevcat/Kingfisher/blob/master/Sources/Resource.swift#L72).

If you are using some other `Resource` instead of the default implementation, please check that you are doing things right and these two resource have different cache key.

Another possible reason might be you are setting the wrong image view. You could check the image url in image setting completion handlers to see whether you are setting the correct ones. 

If you cannot solve this, it would be appreciated if you could supply a demo to reproduce it and I am glad to have a deeper look into it.
