### ISSUE TITLE
Application crashes when downloading large images (more than 10MB files).

### ISSUE THREAD

**Issue by dev-fuad** [onevcat/Kingfisher#739]
### Issue Description

Downloading large images with Kingfisher crashes the app. For reference trying these links -

[https://farm6.staticflickr.com/5720/22076039308_4e2fc21c5f_o.jpg](https://farm6.staticflickr.com/5720/22076039308_4e2fc21c5f_o.jpg)
[https://s-media-cache-ak0.pinimg.com/originals/19/e9/58/19e9581dbdc756a2dbbb38ae39a3419c.jpg](https://s-media-cache-ak0.pinimg.com/originals/19/e9/58/19e9581dbdc756a2dbbb38ae39a3419c.jpg)
[https://orig11.deviantart.net/1062/f/2015/315/9/6/abstract__7_by_thejsyve1-d9gciwk.jpg](https://orig11.deviantart.net/1062/f/2015/315/9/6/abstract__7_by_thejsyve1-d9gciwk.jpg)

downloading these images crashes the app with a memory issue.
I've tried setting `maxMemoryCost=1` but no success.

#### Reproduce

Use the links above in Example app.

**Comment by onevcat** [comment]
@dev-fuad I just tested your images in my device and all of them loaded without problem to me.

I am using an iPhone 7 Plus with the largest memory so it behaves fine, but it really could be a problem if you are loading them in an older device. Each of the images in your links takes 200~300 MB memory, which is expected according to their pixel count. I did not find any memory leak or unintended usage in Kingfisher.

However, loading a single image once a time should not be a problem, since the memory usage is reasonable. So if you cannot load even one image, please check the memory usage of your app (you may need at least 300MB to load such a big image at one time.)

Kingfisher is doing nothing special for large images like that. It just respect all the data and decode it then render in image view. If you need to improve the memory usage, a general way is titling them into small pieces and only loading the visible part. But this should not be the scope of Kingfisher, which is mainly designed for loading frequently used images like user avatars.

If you just want to load them in a list as thumbnails, you'd better to use a smaller version instead of the full resolution ones.

**Comment by dev-fuad** [comment]
@onevcat Thanx for the reply. I've tested it on iPhone 6 and older devices and it does crash on them.
One thing I've noticed is that the download have no problem but as soon as I set that image to an `UIImageView`. 
For now I'm using `KingfisherManager.shared.retrieveImage` to get the image and resize it before setting it to `UIImageView`. Is there a better option! cause I don't have access to the server or thumbnail url.
Anyways Thanks again.

**Comment by onevcat** [comment]
It should be fine if you just set one image, and probably if you are setting multiple.

And it is normal that you could download them all since the most memory consuming process is decoding the compressed image data to raw pixel and show in image view.

Maybe you could try to use the `ResizingImageProcessor` to resize your huge images to smaller ones if you plan just use them as thumbnails. However, I am not sure whether it could and maybe you also need to process them one by one to avoid memory problem.

**Comment by dev-fuad** [comment]
That works good. Thanks
