### ISSUE TITLE
Is Kingfisher doing this or something else?

### ISSUE THREAD

**Issue by emadd** [onevcat/Kingfisher#743]
I've got a UITableViewCell subclass with a UIImageView and a label that are dynamically tall via UITableViewAutomaticDimension.  Kingfisher is loading the image into the ImageView from a remote URL.  

The first time the cells are rendered it looks perfect.  If I reload the table or unload thew view and return, the cell ends up as tall as the image, rather than as tall as the label.  If I do not use Kingfisher and set the image by some other means or do not load an image into the view at all, it looks fine.

[Screenshots](https://i.stack.imgur.com/dJRUe.png)

**Comment by onevcat** [comment]
At the first time, your cell height is determined by the original image view height, and setting an image to the image view will not change its layout anymore. When you reloading the table view, since the image view already has an image set, it has an `intrinsicContentSize` and the cell layout itself with this size.

So basically it is what the UIKit works and I believe it should not be an issue in Kingfisher. (and Kingfisher is not touching anything about view layout or dimension at all. It is just setting the `image` property)

**Comment by emadd** [comment]
I have my doubts.  Like I said, when I set the image to a local asset, this doesn't happen.  Also, the height of the image is dynamic to match the resulting height of the cell, which is dynamically tall depending on the height of the label.
