### ISSUE TITLE
iOS Simulator: Color blended layers shows UIImageView in red.

### ISSUE THREAD

**Issue by jovanpreet** [onevcat/Kingfisher#757]
Hi @onevcat after applying RoundedCornerProcessor the color blended layer shows it in red color. While if I manually round the image it is green. Is there anything to di with alpha channel??
![simulator screen shot 29-aug-2017 10 42 43 am](https://user-images.githubusercontent.com/11874620/29805328-cf03e896-8ca6-11e7-83c6-931121ac4d14.png)

**Comment by onevcat** [comment]
The round corner has to be transparent or it would contain a background color. So it is normal to be red in blender layer instrument.

**Comment by jovanpreet** [comment]
Will this impact scrolling performance

**Comment by onevcat** [comment]
Yes, it could bring overhead, but I believe it should be totally fine in a device you could find in real world.

If you seek a all green in instrument, you could try to add parameter in the RoundedCornerProcessor to indicate a color to use when round the image and strip out the alpha channel to avoid blending. I am glad to see a p-r on this as long as keep current default behavior (clear background color).

**Comment by SebastianCrow** [comment]
FYI, I had a slightly different problem. After applying a RoundCornerImageProcessor to the Image, it has been ending up with the white background color. It turned out that the JPEG image format is a reason because it obviously doesn't have an alpha channel. The PR like that could also "fix" this case so it would be possible to at least specify the background color instead of white (not saying about a more fancy stuff like converting the source image so it has an alpha channel so the clear background color would be possible).
