### ISSUE TITLE
iOS8 URLSessionConfiguration issue, same as #685

### ISSUE THREAD

**Issue by Maru-zhang** [onevcat/Kingfisher#778]
### Issue Description

In my project, I use both [Kingfisher](https://github.com/onevcat/Kingfisher) and [Bugtags](https://work.bugtags.com).However, when I open the feature of `trackingNetwork` in bugtags,`Kingfisher` will go wrong with image display.

Look like this:

![wx20170927-131459](https://user-images.githubusercontent.com/9351818/30896900-e972a352-a385-11e7-87d7-7c99a8e996f7.png)

There is some Triggering conditions：

1. iOS8
2. Specific resources (like this: https://tfs.alipayobjects.com/images/partner/T1yk0dXdFpXXXXXXXX)
3. Turn on network tracking in Bugtags

#### What

I guess it is about `URLSessionConfiguration`, because it never happen again after I write code like this:

```
let config = URLSessionConfiguration.background(withIdentifier: "com.maru")
ImageDownloader.default.sessionConfiguration = config
``` 

#### Reproduce

My Bugtags Code:

```
        let options = BugtagsOptions()
        options.trackingNetwork = true
        options.channel = APP_CHANNEL
        Bugtags.start(withAppKey: BUGTAGS_APP_KEY, invocationEvent: BTGInvocationEventNone, options:options)
        Bugtags.setUserData(UserCenter.defaultCenter.iid, forKey: "userId")
        Bugtags.setUserData(UserCenter.defaultCenter.token, forKey: "token")
```

Any other settings of `Kingfisher` is default.

Thanks for your great project.

**Comment by onevcat** [comment]
It seems that the `urlSession(_:task:didCompleteWithError:)` delegate method is never called on iOS 8 with `URLSessionConfiguration.ephemeralephemeral` or `URLSessionConfiguration.default` when `trackingNetwork` to be `true`. Only the `background` configuration could work fine with the Bugtags.

Currently, Kingfisher just uses an `ephemeral` without any modification. I guess it is not an option for Kingfisher to adopt to a `background` configuration due to this issue. It is more likely that `trackingNetwork` is doing something bad and causing the url session delegate broken on iOS 8, or it is a problem in the old iOS 8 system.

I believe there is no fix needed or should be applied in Kingfisher. You may report this to Bugtags support instead.
