### ISSUE TITLE
前后台切换，进入页面刷新图片（url不变）图片会先空白再出现，给人一种闪的感觉

### ISSUE THREAD

**Issue by OstrichRunning** [onevcat/Kingfisher#793]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [ ] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [ ] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [ ] I want to reoprt a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

#### What

[Tell us about the issue]

#### Reproduce

[The steps to reproduce this issue. What is the url you were trying to load, where did you put your code, etc.]

#### Other Comment

[Add anything else here]

**Comment by onevcat** [comment]
Kingfisher is using `NSCache` for caching images in memory, which will be purged by system when your app being switched to background. It means Kingfisher needs to load it again from disk, which is now an async operation happens in another thread (for not blocking main thread when loading huge files). So basically it is what Kingfisher and iOS works. It is expected and design choice instead of an issue.

Since there is no plan to change this behavior now, I am closing it.

**Comment by OstrichRunning** [comment]
ok.

**Comment by lehom** [comment]
这个问题真的没有修改的计划吗？退后台进前台如果reload tableView的时候会造成不好的体验，如果用loadDiskFileSynchronously又会卡主线程 😭

**Comment by onevcat** [comment]
A `keepWhenEnteringBackground` option was added to the memory cache and will be released soon.
