### ISSUE TITLE
How to retrieve correct image when image url did not change but image changed such as Twitter or GitHub?

### ISSUE THREAD

**Issue by cp3hnu** [onevcat/Kingfisher#803]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [x] I want to reoprt a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

#### What
How to retrieve correct image using Kingfisher when image url did not change but image changed such as Twitter or GitHub.

SDWebImage has a option [SDWebImageRefreshCached] to solve the problem.
```
   /**
     * Even if the image is cached, respect the HTTP response cache control, and refresh the image from remote location if needed.
     * The disk caching will be handled by NSURLCache instead of SDWebImage leading to slight performance degradation.
     * This option helps deal with images changing behind the same request URL, e.g. Facebook graph api profile pics.
     * If a cached image is refreshed, the completion block is called once with the cached image and again with the final image.
     *
     * Use this flag only if you can't make your URLs static with embedded cache busting parameter.
     */
    SDWebImageRefreshCached = 1 << 4,
```

**Comment by onevcat** [comment]
I am afraid this is not supported in Kingfisher now. Kingfisher is not using `NSURLCache` system so there is no way to refresh the cache in that behavior.

**Comment by onevcat** [comment]
A new option `fromMemoryCacheOrRefresh` was [added](https://github.com/onevcat/Kingfisher/blob/master/Sources/KingfisherOptionsInfo.swift#L74)  in version 4.3.0 as a "similar" solution in Kingfisher cache. Instead of checking the cache setting for URL response (in the `NSURLCache`), this option will always download the image and cache it to memory. Once it is in memory, the same image will not be downloaded again (as the behavior of  `forceRefresh`) until it disappears from memory cache.

Since Kingfisher is not using the URL cache system, it also ignore the cache policy provided by the response. If you want a behavior like that, to respect the cache control tag of response header, you might want to just use a plain URL session and do not do anything additional on the data.

**Comment by kaaaaai** [comment]
> A new option `fromMemoryCacheOrRefresh` was [added](https://github.com/onevcat/Kingfisher/blob/master/Sources/KingfisherOptionsInfo.swift#L74) in version 4.3.0 as a "similar" solution in Kingfisher cache. Instead of checking the cache setting for URL response (in the `NSURLCache`), this option will always download the image and cache it to memory. Once it is in memory, the same image will not be downloaded again (as the behavior of `forceRefresh`) until it disappears from memory cache.
> 
> Since Kingfisher is not using the URL cache system, it also ignore the cache policy provided by the response. If you want a behavior like that, to respect the cache control tag of response header, you might want to just use a plain URL session and do not do anything additional on the data.

I encountered the same problem, is the current version optimized for this situation？
