### ISSUE TITLE
Lag when caching images

### ISSUE THREAD

**Issue by Pocito** [onevcat/Kingfisher#804]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [OK ] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [OK] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [OK ] I want to reoprt a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

### Issue Description

Hello, I download about 30 images at once but my CPU goes over 100 (127% for example), I don't understand really why. Here is the Instruments data showing that it's because of pngrepresentation when I cache the images, and the code where I cache the images. Do you have any idea?

I tried to force JPGrepresentation but I have exactly the same lag on my phone and Instruments.
I also tried to put ImageCache.default.store(image!, forKey: "photo-\(number)") in a Dispatch.main.async but it doesn't change anything.

Instruments 

![screen shot 2017-11-13 at 18 37 18](https://user-images.githubusercontent.com/16222485/32739977-c107e062-c8a1-11e7-8235-1df9a8dd6728.png)

Actual Code

```
                ImageDownloader.default.downloadImage(with: url!, options: [], progressBlock: nil) {
                    (image, error, url, data) in
                    
                    if error != nil{
                        completion(error)
                    } else {
                        ImageCache.default.store(image!, forKey: "photo-\(number)")
                        
                        photosSaved += 1
                        
                        if (photosSaved == maxNumberPicsToLoad){
                            completion(nil)
                        }
                    }
                    
                }
```

**Comment by onevcat** [comment]
Hi. When you want to cache an image to disk, the image would be encoded to a binary data format. This is what `pngRepresentation` or `jpegRepresentation` does. 

It is unavoidable but it should not cause your UI lag, since it happens in a background queue, unless you are doing some other heavy work at the same time.

**Comment by Pocito** [comment]
Thank you for your quick reply @onevcat ! I have been trying to Dispatch other UI elements processing at the same time, but didn't how to fix it for now. I will keep trying and comment down here if I find why.

**Comment by onevcat** [comment]
The performance on this should be improved by #805 
Since maybe I have some other fix before I could tag a new version, you could try the master branch to see whether it could solve your issue. Please notice that you also need to modify your code to also send the `originalData`, otherwise the change will not apply for your case. For your code, you should change 

```swift
ImageCache.default.store(image!, forKey: "photo-\(number)")
```

to 

```swift
ImageCache.default.store(image!, original: data, forKey: "photo-\(number)")
```

after you upgrade Kingfisher to master branch.

**Comment by Pocito** [comment]
Thank you, I just tried but I have the exact same lag.

**Comment by Pocito** [comment]
I made some new tests, my bad .pngrepresentation is not used anymore most of the time and not on Instruments anymore, I have other stuff that lags but this is fixed, thanks 💯
