### ISSUE TITLE
Can I change the implementation of MD5 into CommonCrypto?

### ISSUE THREAD

**Issue by chdzq** [onevcat/Kingfisher#821]
### Issue Description
Can I change the implementation of MD5 into CommonCrypto?
like：
```
    var md5: String {
        if let data = self.data(using: String.Encoding.utf8) {
            let str = cString(using: .utf8)
            let strLength = CUnsignedInt(lengthOfBytes(using: .utf8))
            let digestLen = Int(CC_MD5_DIGEST_LENGTH)
            let result = UnsafeMutablePointer<CUnsignedChar>.allocate(capacity: digestLen)
            defer {
                result.deallocate(capacity: digestLen)
            }
            CC_MD5(str, strLength, result)
            var hash = ""
            for i in 0 ..< digestLen {
                hash = hash.appendingFormat("%02x", result[i])
            }
            return hash
        }
        return self
    }
```
it work correctly in cocoapod and framework.
thanks!

**Comment by onevcat** [comment]
@chdzq  Thanks for considering of that!

The reason of current MD5 implementation is that in early age of Swift, CommonCrypto (or some other C library) cannot be used in a framework target (like Kingfisher), although you could import it in a bridge header and use it in an application target.

I am not sure about current state, should we add a Swift wrapper of CommonCrypto and link to it if we want to use `CC_MD5` or other C APIs? If so, I think I'd prefer to staying in current implementation instead of importing another layer of complexity.

If it is easy enough and we could do it without huge changes, I'd like to see a p-r on it and then we could see how it works.

Thank you!
