### ISSUE TITLE
can i change class Kingfisher<Base> into struct

### ISSUE THREAD

**Issue by chdzq** [onevcat/Kingfisher#824]
### Issue Description
I think Kingfisher<Base> should be struct type.
so for the purpose， i will change the organizational relationship between Kingfisher and UIImageVIew. will change many files.
this is a tentative idea.

I like Kingfisher,  i think  better.

**Comment by onevcat** [comment]
Hi,

Probably no. This type is intended to be a class since it will hold reference types like image view or image. It's not likely to be a good idea to use struct here, which might misleading users to think it could be a value type. Additionally, a struct could introduce unnecessary difficulty in property setting or mutating.
