### ISSUE TITLE
框架似乎有内存泄露的问题

### ISSUE THREAD

**Issue by buginux** [onevcat/Kingfisher#85]
最近在写一个练手的项目，用了Kingfisher，发现图片加载得越来越多，内存也嗖嗖往上涨，后来换成SDWebImage试了下，好像就没这问题了。我用instrument测试了下，好像确实有点问题，不过我不太会用，只是大概测试了下。不知道需不需要提供什么信息好帮助定位到问题？

**Comment by onevcat** [comment]
因为默认的话图片会保存在 memory cache 中，不到 memory warning 的话是不会主动去释放的，这样对性能会是最好的。你可以试试看模拟个 memory warning 或者一直到触发 memory warning 看看会不会下降。

当然也确实有可能有问题，如果可能的话，能提供一个 demo project 是最好的，因为我这边测试的情况是并没有 unbounded increasing。

**Comment by buginux** [comment]
我刚刚按照您的建议测试了几遍，现在情况是这样的：
* 第一次运行程序的时候，似乎都不会进行回收，内存会一直增加到100M+
* 在我手动触发 memory warning 之后，内存会减少到 40M 左右
* 之后的回收不太确定，我试验过好多次，有时会保持在40~50M之间，有时还是会往上涨到80+

以上的测试都是在模拟器中进行的，没有在真机中测试过。Xcode 版本是 6.3。

如果要提供测试程序的话，应该以何种方法提供呢。

**Comment by onevcat** [comment]
@buginux 比如可以把您测试的这个项目放到 GitHub 上。不过如果只是很简单 set image 这种的话就不用了..我也检查过，图片的话应该是没有泄露的。其他部分倒确实有可能，我会再看看。您也可以帮助在检查下，如果能找到的话提交 p-r 来修复是最好的。

**Comment by buginux** [comment]
OK，好的，那我再测试下，尽量找到出问题的地方。

**Comment by lorrykiko** [comment]
我也遇到这个问题了＝。＝，有邮件么 我可以把我做的项目发给你看看

**Comment by onevcat** [comment]
我的资料页面上就有邮箱。谢谢

**Comment by lorrykiko** [comment]
不好意思 周末没看到你的回复 项目发给你 麻烦你看下

Date: Fri, 31 Jul 2015 03:23:40 -0700

**Comment by onevcat** [comment]
@lorrykiko 您好，不好意思，但是一直没有收到您的邮件..

**Comment by onevcat** [comment]
再次查证了一下，在 Instruments 里并没有发现 Kingfisher 的泄露。暂时先关掉了。

**Comment by lizzie8023** [comment]
喵神,我也遇到Kingfisher不主动释放内存的问题,不断的上下滚动cell,最后内存都飙到600M了

**Comment by onevcat** [comment]
@lizzie8023 If you are operating a large amount of cells and images, it is an expected behavior since Kingfisher will try to cache the used images as much as possible to improve performance (by default). Until a memory warning is received, Kingfisher will not purge the memory cache. So, once you triggered a memory warning, you will be able to see the memory drop (if you implement your reusing logic correctly).

If it happens when you scroll several cells up and down, maybe you encountered [this issue](https://github.com/onevcat/DispatchMemoryLeakDemo) of Xcode.

**Comment by lizzie8023** [comment]
Sorry, I just found, because I "canEditRowAtIndexPath" which used the wrong method to determine the cell, which leads to my cell memory soared when I found this error came back immediately ready to delete the previous question, and found that already reply I, thank reply

**Comment by onevcat** [comment]
@lizzie8023 Glad to hear that you solved it. 🍻
