### ISSUE TITLE
ImageCache类初始化方法中没必要将fileManager的初始化放在IOQueue上执行吧？应该不会引起多线程问题吧！

### ISSUE THREAD

**Issue by yuexygoodman** [onevcat/Kingfisher#909]
ioQueue.sync { fileManager = FileManager() }

**Comment by onevcat** [comment]
For now, it should be fine since the file manager delegate is not in use. However, the decision of using a unique file manager instead of the shared one in another thread might cause problems if later we want to inspect some events. The `FileManager` class is not thread-safe after all.

According to the documentation, I think it would be better to create it within the using thread as well.
