### ISSUE TITLE
Question | Improvement

### ISSUE THREAD

**Issue by cuzv** [onevcat/Kingfisher#943]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [ ] I want to report a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

### Issue Description

According to [WWDC 2018 Session 416](https://developer.apple.com/wwdc18/416)
- Start or keep using `UIGraphicsImageRenderer` instead of `UIGraphicsBeginImageContextWithOptions` since `iOS 10` due to couple of reasons
- UIImage is expensive for sizing and to resizing, recommended use `downsampling`

For the first one, there may be a chance to re-implement `func draw(cgImage: CGImage?, to size: CGSize, draw: ()->()) -> Image` in `Image.swift`

As the second. I saw many complain about Kingfisher could be cause crash when deal with large image. If we use `downsampling` to load large image's thumbnail directly, instead of decode whole image then resize to target size, it may reduce those situations. Should be complete by changing implementation of `ResizingImageProcessor` 's `process` function when generate image using raw data.

These are just my thoughts, correct me if I was wrong.

**Comment by onevcat** [comment]
@cuzv Yes, thanks for the suggestion.

There are quite a few of legacy code in Kingfisher and there is indeed a lot of space to improve. Currently, Kingfisher supports from iOS 8.0. We may have to drop it and 9.0 if you want to adapt to `UIGraphicsImageRenderer`. We could use some compilation condition to support both, but it also causes some inconsistency between iOS versions, which is not quite desired now. Maybe we could consider to drop iOS 8 and 9 after iOS 12 comes out!

For the downsampling with ImageIO, I totally agree that we could reimplement the `ResizingImageProcessor` to save memory. Any chance to give a PR for it? Since I am not quite easy to find some time for this. :[ (But feel free to say no!) 

Thanks!

**Comment by cuzv** [comment]
@onevcat Thanks for your reply.

I'm so glad you agree with me. Would love to support `downsampling` feature when it's ready.

**Comment by worthbak** [comment]
We just finished adding a downsampling step to our Kingfisher render pipeline in order to save memory (also inspired by some of the sessions from WWDC). In doing so, we were able to keep our app's memory usage below an acceptable threshold consistently when viewing many large images. 

However, it did require a bit more customization than expected, since you need to try and prevent Kingfisher from ever allocating a full image buffer for large images (as that image buffer's memory footprint is exactly what we're trying to avoid) , and by default Kingfisher will do this on both when an image is downloaded and when it is serialized from the disk cache. Caching was also a bit of an issue, since we never want to fully serialize and cache the original image as a `UIImage` - instead, we only want to cache downsampled versions of the original image. 

In any case, getting it to work involved using a custom `ImageProcessor` both in the render phase and also in a custom `CacheSerializer`, and also using separate caches for original files (on disk) and downsampled images (in memory). The final option set looks like this:

```swift
// will render the image downsampled to the given dimension
let dimension = max(size.width, size.height)
let cacheSerializer = DownsamplingImageCacheSerializer(dimension)

let options: KingfisherOptionsInfo =  [
    .targetCache(memoryCache),
    .originalCache(originalCache),
    .cacheOriginalImage,
    .cacheSerializer(cacheSerializer),
    .processor(cacheSerializer.pipeline) // share the render pipeline from the serializer
]
```

I'd be happy to try and contribute some of this work back into Kingfisher, but I'm not quite sure how to slot it into the library, since our implementation is more like a custom configuration of the library, and not something that would lend itself to a single custom type or processing step. @onevcat any thoughts or suggestions on that? Let me know if I'm missing some obvious step that would have made this work a bit easier! Also, thanks for making the library so open to customization 👍

**Comment by onevcat** [comment]
@worthbak 

Wow, great work!

It make sense that you need some additional steps to make it work. However, I have a question on the cache side, especially the necessity of separating `targetCache` and `originalCache`. 

If you set `.cacheOriginalImage` on, Kingfisher will in fact cache both the downsampled one by the processor, as well as the original one. But as you said, "since we never want to fully serialize and cache the original image as a UIImage - instead, we only want to cache downsampled versions of the original image". So maybe we don't want/need the `.cacheOriginalImage` at all? Otherwise it would make Kingfisher to store the original image.

And it is a bit strange to me to pass a `cacheSerializer.pipeline` as a processor. I think it would be more reasonable to be a `DownsamplingImageProcessor` instead, and the sharing part of downsampling cache serializer and processor could be extracted to a third type like `DownsamplingPipline` or so.

If we could understand whether indeed we need separated caches or not, we could decide whether we need to provide a "bundled option" for downsampling. It would make it easier for users who want to adopt it, instead of creating the correct options following documentation.

**Comment by worthbak** [comment]
@onevcat thanks for the feedback! The main reason we want to try and cache the original image is that, for our purposes, we download a large original, and then reuse that image in various places / sizes in our app. So it’s not quite good enough to only cache the downsampled versions, since we’d have to fetch the original over and over. 

One detail I didn’t mention was the limits we set on the caches - we try to lock the originals cache to only store on-disk (so that it only deals in `Data`, not `UIImage`), and lock the memory cache (for downsampled images) to memory only: 

```swift 
ImageCache.memoryCache.maxMemoryCost = 20 * 1024 * 1024
ImageCache.memoryCache.maxDiskCacheSize = 1
        
ImageCache.originalCache.maxMemoryCost = 1
ImageCache.originalCache.maxDiskCacheSize = 100 * 1024 * 1024
```

The desired effect here is to a) ensure that the originals are always cached (as `Data`), and b) try to never make a `UIImage` from the original data. While this seems to work ok, a better solution might be to add a `.cacheOnlyData` option to `ImageCache`, wherein it would only stick the `Data` blobs for the original images into the memory or disk cache, but still keep them around for serialization into a downsampled version. Instead of locking the originals cache to disk-only, it would just know to only store `Data` in memory or on disk. Does that make sense? 

As far as the cache serializer goes, that makes sense, and is kinda what we’re doing already - we need to ensure that the original image being serialized from the disk cache goes directly into its downsampled form, and not into its full-res form. As such, we simply share the downsampling code from the processor, which for us meant sharing the pipeline code (and only initializing one pipeline). Open to suggestions on that front. 

If you like that `.cacheOnlyData` option I mentioned, I can get to work on a PR for that - IIRC, the `NSCache` used by `ImageCache` is typed as `AnyObject`, so it shouldn’t be a ton of work (no need for a separate managed cache or anything). Let me know! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gmogames** [comment]
@worthbak Any chance you could share the updates you did to include the new downsampling suggestions from Apple into Kingfisher? Starting that process now on my project and would be awesome to see what has been done before.

**Comment by onevcat** [comment]
Downsampling processor was implemented in Kingfisher 5. The `UIGraphicsImageRenderer` requires more work and there is a plan for it in the future.

And now, `ImageCache` has a method to accept store raw data to disk.

Since most of the discussion was done, and the left things are on my ToDo list, I close this issue for now.
