### ISSUE TITLE
Flickering of image when calling setImage()

### ISSUE THREAD

**Issue by renshaw1** [onevcat/Kingfisher#993]
#### What

I have a UIImageView and set the image through _kf.setImage()_.
It works fine, except that the ImageView is flickering once each time I call _kf.setImage()_ again on the same Image View, even if the image is exactly the same and loaded from the Cache.

Is there a way to turn this off or avoid re-setting the image?

Thanks!

#### Reproduce

[The steps to reproduce this issue. What is the url you were trying to load, where did you put your code, etc.]

**Comment by onevcat** [comment]
This is due to the image is already released from memory cache and will be loaded again from disk cache, with a `nil` placeholder. You could try to set images with `.keepCurrentImageWhileLoading` to see whether it could work:

```swift
imageView.kf.setImage(with: url, options: [.keepCurrentImageWhileLoading])
```

**Comment by renshaw1** [comment]
Hi @onevcat, thanks for the answer.
This fixes the "flickering", but unfortunately messes up my TableView. I have this ImageView inside a TableViewCell and set the image in cellForRow. After scrolling cells have images set that don't belong to them....

**Comment by hernangonzalez** [comment]
Hi @onevcat ,

I am also seeing this even with `keepCurrentImageWhileLoading`.  

I think my issue is with the transition. Since even with that flags it tries to set to nil the placeholder. Or am I using it wrong there?

Thanks,
H.

**Comment by hernangonzalez** [comment]
Nevermind, @onevcat. I was not using that flag on my second call.

**Comment by onevcat** [comment]
@hernangonzalez  👍 

@renshaw1 
BTW, if you are using it in a reusable cell in table view or collection, maybe the flickering comes from the cell reusing. You could also try:

```swift
cell.imageView.kf.setImage(with: url, placeholder: cell.imageView.image)
```

to use the current image as your loading placeholder to prevent it.

**Comment by hellaandrew** [comment]
.keepCurrentImageWhileLoading seems to work.
In my situation, I got a blink because I called `collectionView.reloadSections(indexSet:)` on a section that contains a cell that displays an image. The problem with that is `reloadSections` forces the collectionView to create *new* cells (as in new pointers) for these sections. Since it's displaying a *new* cell, the imageView starts off as its backgroundColor, then fades in the image.

**Comment by fukemy** [comment]
@hellaandrew hi buddy, did u have any solution? Ofcourse we need reload section for avoid reload other cell

**Comment by onevcat** [comment]
If the problem happens due to lack of memory cache, another solution worths to try is adding a [`.load​Disk​File​Synchronously` option](https://kingfisher.onevcat.com/kingfisheroptionsinfoitem/#kingfisheroptionsinfoitem.loaddiskfilesynchronously. It turns the async loading from disk to sync behavior and prevents the possible flickering.

**Comment by nnsaori** [comment]
I've also had this problem. In my case, it came because extra call `DispatchQueue.main.async {}` despite it being called in the main thread.
