### ISSUE TITLE
Memory issue  - Loading gif in collection view cell.

### ISSUE THREAD

**Issue by mohdsafadsaal** [onevcat/Kingfisher#996]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [ ] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [ ] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [ ] I want to report a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

### Issue Description
Loading gif in collection view cell takes lots of memory.
#### What
We are loading gif from url in our collection view cell. Each gif takes 150mb, This might lead into memory issue. Is there any solution to solve this memory problem?
[Tell us about the issue]

#### Reproduce

[The steps to reproduce this issue. What is the url you were trying to load, where did you put your code, etc.]

#### Other Comment

[Add anything else here]

**Comment by onevcat** [comment]
I suggest you could try the `AnimatedImageView` instead of the normal `UIImageView` for this purpose. In `UIImageView`, all GIF data will be loaded at once, which is a memory consuming operation if your GIF is large or contains lots of frames. `AnimatedImageView` will take care of the preloading for only several frames to save the memory. (However, it asks for more CPU time and battery energy, it is a trade off.)
